### PR TITLE
Switch to travis for Windows testing

### PR DESCRIPTION
**Pull request by djhoese**
The ci-helpers project is deprecating appveyor soon. This PR removes appveyor and instead uses travis CI for our Windows environment. Includes enabling mamba package manager in ci-helpers.

 - [x] Tests added 
 - [x] Passes ``flake8 satpy`` 
 - [x] Fully documented

### CODE REVIEW

**Comment by mraspaud** [comment]
Are the lock files created automatically? or do we need to update them? I that case when?

**Comment by djhoese** [comment]
Lock files are manually generated. I should have marked this WIP. I need to add a README. I originally was just going to use mamba but then was told about lock files on twitter (see conda-lock) package. The problem is ci-helpers doesn't support lock files yet. I didn't realize that until after I started switching to them. There are also weird bugs where I can't generate the windows lock file because of the CUDA drivers on my laptop or something.

**Comment by djhoese** [comment]
It may be mostly a ci-helpers limitation but even after doing what I thought I could to benefit from the lock files the builds are still slower than just using mamba from the start (no lock files). I may close this and create a new PR from my first couple commits in this branch.

**Comment by mraspaud** [comment]
Sounds good

**Comment by djhoese** [comment]
Replaced by #1376. I'll keep the branch around so we can look at this in the future if ci-helpers makes more improvements (shortcuts) for handling lock files.

**Pull request closed without merging**
