### PR TITLE
Fix gcps type for newer rioxarray versions

### PR DESCRIPTION
**Pull request by mraspaud**
This PR introduces a fix for the backwards incompatibility introduced in https://github.com/corteva/rioxarray/pull/787, and thus should make the tests for SAR pass again.

### CODE REVIEW

**Review by pnuu — APPROVED** [review]
LGTM

**Review by djhoese — APPROVED** [review]
This is marked as enhancement, should it be bug fix? It is a "compatibility" fix technically right?

**Comment by mraspaud** [comment]
> This is marked as enhancement, should it be bug fix? It is a "compatibility" fix technically right?

I was seeing it as an enhancement as it is not a bug in satpy... but I'm not picky, bug works if you prefer it.

**Comment by djhoese** [comment]
Yeah it could be seen either way. I guess it depends what you want it released as.

**Pull request merged**
