### PR TITLE
Fix expected test results for pyorbital 1.7.2

### PR DESCRIPTION
**Pull request by djhoese**
In https://github.com/pytroll/pyorbital/pull/99 which was released in pyorbital 1.7.2, fixes were added for how earth sun distance were calculated (described [here](https://github.com/pytroll/pyorbital/issues/97)). Due to these fixes some of Satpy's tests started failing because the results are now more correct.

 - [ ] Closes #xxxx 
 - [ ] Tests added 
 - [ ] Fully documented 

CC @depion who made the pyorbital fix. Also CC @ameraner who works with SEVIRI. I'm not sure who else should be CC'd. @gerritholl and @pnuu?

### CODE REVIEW

**Review by mraspaud — APPROVED** [review]
LGTM, thanks for taking the time to switch to pytest.

One open question though: In the tests that are not calling pyorbital directly (so here test_seviri_l1b_calibration) should we mock the relevant pyorbital functions? My meaning is that right now, the tests are failing not because we broke something in the reader, but because of something outside satpy, and I think these tests should not fail in that case. To detect unwanted behaviour of external libraries, we can just use the tests like the ones in TestSunEarthDistanceCorrection.

I don't mean though that action should be taken in this PR, so feel free to merge.

**Review by gerritholl — APPROVED** [review]
Looks good to me

**Comment by ameraner** [comment]
LGTM too.

**Comment by djhoese** [comment]
@mraspaud I don't think so. If we mocked every external library that could change the results of a test then we wouldn't be testing anything useful. To me the tests are not only testing satpy but satpy's compatibility with its dependencies. We've had times in the past where certain tests were mocked in the way you mention and interfaces were changed in that external library and we didn't catch it until those changes were released and users complained about it. The mocked interface was fine, the real interface was not.

You could make an argument that the tests should find a way not to need exact values, but satpy is a library dealing with numbers, we need to make sure those numbers are somewhat consistent.

**Comment by mraspaud** [comment]
ok.

**Comment by djhoese** [comment]
> So in this case we would have only one test failing, the one defining the interface between pyorbital and satpy.

Eh, I still don't like the extra mocking. I'd rather know I'm using what I think I'm using when writing the tests. It also teaches new contributors that they should mock dependencies in their tests (if they were only looking at the seviri tests). And it requires knowledge of the interface to the external library in multiple locations, one of which is just for testing (if I'm understanding what the utils tests were doing).

**Pull request merged**
