### PR TITLE
Facilitate selection of calibration coefficients in seviri_l1b_hrit

### PR DESCRIPTION
**Pull request by sfinkens**
Allow the user to choose between nominal & GSICS calibration coefficients (both file-internal) and/or specify external calibration coefficients for the conversion from counts to radiances. Depends on #543 for the ``reader_kwargs`` to be passed to the file handler. Example usage:

```python
import satpy
import glob

filenames = glob.glob('H-000-MSG3*')

# a) Choose GSICS calibration coefficients for IR channels and nominal coefficients for
#    VIS channels
scene1 = satpy.Scene(filenames,
                     reader='seviri_l1b_hrit',
                     reader_kwargs={'calib_mode': 'GSICS'})
scene1.load(['VIS006', 'IR_108'])

# b) Specify external calibration coefficients for VIS channels and GSICS coefficients
#    for IR channels
coefs = {'VIS006': {'gain': 0.0236, 'offset': -1.20},
         'VIS008': {'gain': 0.0297, 'offset': -1.51},
         'IR_016': {'gain': 0.0228, 'offset': -1.16}}
scene2 = satpy.Scene(filenames,
                     reader='seviri_l1b_hrit',
                     reader_kwargs={'calib_mode': 'GSICS',
                                    'ext_calib_coefs': coefs})
scene2.load(['VIS006', 'IR_108'])
```

 - [x] Tests added 
 - [x] Tests passed 
 - [x] Passes ``git diff origin/master -- "*py" | flake8 --diff`` 
 - [x] Fully documented

### CODE REVIEW

**Comment by sfinkens** [comment]
@djhoese No, it doesn't

**Comment by sjoro** [comment]
Looks solid to me, good work @sfinkens !

**Comment by ColinDuff** [comment]
dont see any problem with this

**Comment by sfinkens** [comment]
@martin Oh snap! I'll fix this

**Pull request merged**
