### PR TITLE
ABI l2 reader

### PR DESCRIPTION
**Pull request by jhbravo**
Related with the [#767](https://github.com/pytroll/satpy/pull/767)
I also work a bit with a reader for abi l2, this can access cmip data and also products
cmip: obtained from AWS or Google
Products: obtained from [unidata servers](https://thredds-test.unidata.ucar.edu/thredds/catalog/satellite/goes16/GOES16/Products/catalog.html)  

 - [ ] Closes #xxxx 
 - [ ] Tests added and test suite added to parent suite 
 - [ ] Tests passed 
 - [ ] Passes ``flake8 satpy`` 
 - [ ] Fully documented 
 - [ ] Add your name to `AUTHORS.md` if not there already

### CODE REVIEW

**Comment by djhoese** [comment]
Similar to @yufeizhu600's PR, this seems to share some logic with the `abi_l1b` reader, it would be nice if the python code could be shared. It would be best if you could compare your work with #767 and see what can be combined. Right now this will be very difficult for @mraspaud and I to compare the two and find a way to merge them. Other things I noticed while skimming:

1. The `standard_name` was set to `CMI`. It should be a standard CF name like in other readers (`toa_bidirectional_reflectance`, `toa_brightness_temperature`, etc).
2. Isn't `abi_l2_cmip` technically `abi_l1b_cmip`? So then `abi_l2_product` is actually `abi_l2`?

**Comment by jhbravo** [comment]
I will make the changes you suggest
`abi_l2_cmip` -> `abi_l1b_cmip`
`abi_l2_product` -> `abi_l2`
I will see more detail the code of @ yufeizhu600 I hope we can get in touch

**Comment by yufeizhu600** [comment]
@djhoese The CMIP is actually one of NOAA ABI l2 products. 
 CMI:long_name = "ABI L2+ Cloud and Moisture Imagery reflectance factor" ;
 CMI:standard_name = "toa_lambertian_equivalent_albedo_multiplied_by_cosine_solar_zenith_angle" ;
@jhbravo I have not finished my update of the PR as Martin suggested. Will let you know once I am done. We can chat at the slack/satpy too.

**Comment by jhbravo** [comment]
> @djhoese The CMIP is actually one of NOAA ABI l2 products.
> CMI:long_name = "ABI L2+ Cloud and Moisture Imagery reflectance factor" ;
> CMI:standard_name = "toa_lambertian_equivalent_albedo_multiplied_by_cosine_solar_zenith_angle" ;
> @jhbravo I have not finished my update of the PR as Martin suggested. Will let you know once I am done. We can chat at the slack/satpy too.

**Comment by djhoese** [comment]
As far as I can tell this PR has been absorbed by #767. That reader can read CMIP files (at least it is designed to). This PR also got the new ABI composites mixed in with it which I'd like to keep separate.

Closing now. If there is a reason to reopen then we can do that or the likely better choice is an update of the code in master with a new PR.

**Pull request closed without merging**
