### PR TITLE
Add hrv_clouds, hrv_fog and natural_with_night_fog composites to seviri.yaml

### PR DESCRIPTION
**Pull request by peters77**
This PR adds two hrv composites to seviri.yaml. Recipes are provide by @pnuu . I added the 

```
natural_with_night_fog:
    compositor: !!python/name:satpy.composites.DayNightCompositor
    standard_name: natural_with_night_fog
    prerequisites:
      - natural_color
      - night_fog
```
to seviri.yaml as the composite version of visir.yaml doesn't work with seviri. 

 - [ ] Closes #xxxx 
 - [ ] Tests added and test suite added to parent suite 
 - [ ] Tests passed 
 - [ ] Passes ``flake8 satpy`` 
 - [ ] Fully documented 
 - [ ] Add your name to `AUTHORS.md` if not there already

### CODE REVIEW

**Comment by mraspaud** [comment]
@peters77 thanks a lot for this ! If you feel like it, it would be nice if you could paste an example image of each here for future reference :)

**Comment by pnuu** [comment]
Oh, and remember to add yourself to `AUTHORS.md` :+1:

**Comment by peters77** [comment]
Some examples: 

hrv_clouds: 
hrv_clouds

hrv_fog:
Ohne Titel 2

natural_with_night_fog:
natural_with_night_fog

**Comment by mraspaud** [comment]
@peters77 Looks good. How about using `natural_color_sun` to have a slightly brighter image on the last one ?

**Comment by mraspaud** [comment]
oh, and @peters77 you need to add your name to the AUTHORS.md file :)

**Comment by peters77** [comment]
Added myself to AUTHORS.md, changed as proposed to natural_color_sun. Brighter image on the day side looks much better.

MSG-4-euro-raw

**Pull request merged**
