### PR TITLE
Add FIR product to seviri_l2_grib reader

### PR DESCRIPTION
**Pull request by strandgren**
Add support of reading additional products to the seviri_l2_grid reader.

 - [x] Fully documented 
 - [x] Add your name to `AUTHORS.md` if not there already

### CODE REVIEW

**Review by pnuu — APPROVED** [review]
Looks good to me. Thanks for the PR!

**Review by sjoro — CHANGES_REQUESTED** [review]
Very good, just one minor comment/suggestion. Please add a link to the EUM Product Navigator (https://navigator.eumetsat.int/) to the references in `seviri_l2_grib.py` and `seviri_l2_bufr.py`.
Users can use the product navigator to find more info on EUM products, for example "what is the active fire classification? what do the numbers mean?".

**Review by sjoro — APPROVED** [review]
looks good to me!

**Review by mraspaud — APPROVED** [review]
LGTM

**Comment by mraspaud** [comment]
Thanks for the PR, and welcome to the Pytroll community!

**Pull request merged**
