### PR TITLE
Make documentation generation faster

### LINKED ISSUE #2864: Documentation takes too long to build
We've been noticing that documentation on readthedocs has been timing out. Off the top of my head I believe the last time I checked RTD gives free projects 15 minutes for a build (30 minutes if you pay). The area preview generation (using cartopy) is taking a little over 4 minutes by itself (that's my local machine, not a cheap CI runner that RTD might be using). On top of that the resulting HTML file (see below) is ~23MB in size because it has all the SVG images embedded. I don't know how others feel but that seems like a lot. I mention the size because my initial idea for fixing the HTML representation time was to just pre-create the HTML of the areas and save it to git and detect when it needs to be updated.

https://satpy.readthedocs.io/en/stable/resample.html#area-definitions-included-in-satpy

Here's the timing on `time make html` on my local machine with the cartopy shapefiles already downlaoded and cached:

```
Before generating reader table:  2024-07-30T14:52:17.541998
After generating reader table:  2024-07-30T14:52:18.705411
After reading area YAML:  2024-07-30T14:52:18.783992
Before iterating over areas:  2024-07-30T14:52:18.784044
After iterating over areas:  2024-07-30T14:52:18.970641
After writing areas:  2024-07-30T14:56:28.425944

real	6m57.167s
user	6m55.319s
sys	0m2.993s
```

So the last two prints before the `time` output are the HTML representation writing. So ~66% of the documentation rendering is the area repr. Another big chunk of the remaining 3 minutes is likely API documentation generation.

### PR DESCRIPTION
**Pull request by djhoese**
Closes #2864 

Requires https://github.com/pytroll/pyresample/pull/615

 - [x] Closes #2864 
 - [ ] Tests added 
 - [ ] Fully documented 
 - [ ] Add your name to `AUTHORS.md` if not there already

### CODE REVIEW

**Comment by mraspaud** [comment]
Ok, pyresample 1.30.0 is now out, do you think this is ready?

**Comment by djhoese** [comment]
Not really. Once I get RTD builds working then we have to decide if we like the eay it looks. Then I need to update the documentation to explain how to run the script before running the normal sphinx build commands.

**Comment by djhoese** [comment]
@mraspaud @BENR0 What do you think (scroll down and expand the "Map" sections):

https://satpy--2875.org.readthedocs.build/en/2875/resample.html#area-definitions-included-in-satpy

**Comment by djhoese** [comment]
@mraspaud I kind of wonder if I should make it so the area list is only generated from the `main` branch. It seems super wasteful to build it on every commit of every PR. It adds 2+ minutes to every documentation run.

**Comment by mraspaud** [comment]
That seems reasonable. We just need to make sure we generate it locally whenever we change that code...

**Comment by BENR0** [comment]
Yepp like what you did with the template. Although in the link you posted there are now area defs listed for me.

**Comment by djhoese** [comment]
Yes, sorry @BENR0. I realized that right after I made the commit. I'll merge this to make sure my technique works and then any requested changes can go in a future PR. I'll comment when the build finishes so you can review the area overviews.

**Comment by djhoese** [comment]
@BENR0 Here you go: https://satpy.readthedocs.io/en/latest/resample.html#area-definitions-included-in-satpy

Looks like based on my time log messages that it takes ~4 minutes to generate these.

**Comment by mraspaud** [comment]
Thanks for fixing this!

**Comment by BENR0** [comment]
Yepp nice, thanks for the fix.

**Pull request merged**
