### PR TITLE
Handle valid range and valid_range correctly for two types of HY2 SCAT l2b hdf5 data

### LINKED ISSUE #2208: hy2_scat_l2b_h5 reader does not work any more due to space in `valid range` attribute
**Describe the bug**

**To Reproduce**

```python
# Your code here
#!/usr/bin/env python

import sys
from satpy import Scene
from satpy.utils import debug_on
debug_on()

files = [sys.argv[1]]
data = Scene(filenames=files, reader = 'hy2_scat_l2b_h5')
data.load(['wind_speed_selection'])

```

**Expected behavior**
The wind_speed_selection should be read without any error messages.

**Actual results**
```
(pytroll) trygveas@pc5564:~/pytroll/satpy$ python ~/Git/ppi-remotesensing-satellite-processing/templates/test-hy2.py ~/Git/ppi-remotesensing-satellite-processing/W_XX-EUMETSAT-Darmstadt,SURFACE+SATELLITE,HY2B+SM_C_EUMP_20220611------_18202_o_250_l2b.h5
[DEBUG: 2022-09-28 17:34:17 : satpy.readers.yaml_reader] Reading ('/home/trygveas/pytroll/satpy/satpy/etc/readers/hy2_scat_l2b_h5.yaml',)
[DEBUG: 2022-09-28 17:34:17 : satpy.readers.yaml_reader] Assigning to hy2_scat_l2b_h5: ['/home/trygveas/Git/ppi-remotesensing-satellite-processing/W_XX-EUMETSAT-Darmstadt,SURFACE+SATELLITE,HY2B+SM_C_EUMP_20220611------_18202_o_250_l2b.h5']
[DEBUG: 2022-09-28 17:34:17 : satpy.composites.config_loader] Looking for composites config file scatterometer.yaml
[DEBUG: 2022-09-28 17:34:17 : satpy.composites.config_loader] Looking for composites config file visir.yaml
[WARNING: 2022-09-28 17:34:17 : satpy.readers.yaml_reader] Failed to load DataID(name='wvc_lat', resolution=25000, modifiers=()) from <HY2SCATL2BH5FileHandler: '/home/trygveas/Git/ppi-remotesensing-satellite-processing/W_XX-EUMETSAT-Darmstadt,SURFACE+SATELLITE,HY2B+SM_C_EUMP_20220611------_18202_o_250_l2b.h5'>
Traceback (most recent call last):
  File "/home/trygveas/pytroll/satpy/satpy/readers/yaml_reader.py", line 695, in _load_dataset
    projectable = fh.get_dataset(dsid, ds_info)
  File "/home/trygveas/pytroll/satpy/satpy/readers/hy2_scat_l2b_h5.py", line 110, in get_dataset
    data = self._mask_data(key['name'], data)
  File "/home/trygveas/pytroll/satpy/satpy/readers/hy2_scat_l2b_h5.py", line 129, in _mask_data
    valid_range = self[key_name].attrs['valid_range']
KeyError: 'valid_range'
[ERROR: 2022-09-28 17:34:17 : satpy.readers.yaml_reader] Could not load dataset 'DataID(name='wvc_lat', resolution=25000, modifiers=())': "Could not load DataID(name='wvc_lat', resolution=25000, modifiers=()) from any provided files"
Traceback (most recent call last):
  File "/home/trygveas/pytroll/satpy/satpy/readers/yaml_reader.py", line 847, in _load_dataset_with_area
    ds = self._load_dataset_data(file_handlers, dsid, **kwargs)
  File "/home/trygveas/pytroll/satpy/satpy/readers/yaml_reader.py", line 719, in _load_dataset_data
    proj = self._load_dataset(dsid, ds_info, file_handlers, **kwargs)
  File "/home/trygveas/pytroll/satpy/satpy/readers/yaml_reader.py", line 704, in _load_dataset
    raise KeyError(
KeyError: "Could not load DataID(name='wvc_lat', resolution=25000, modifiers=()) from any provided files"
[WARNING: 2022-09-28 17:34:17 : satpy.readers.yaml_reader] Failed to load DataID(name='wvc_lon', resolution=25000, modifiers=()) from <HY2SCATL2BH5FileHandler: '/home/trygveas/Git/ppi-remotesensing-satellite-processing/W_XX-EUMETSAT-Darmstadt,SURFACE+SATELLITE,HY2B+SM_C_EUMP_20220611------_18202_o_250_l2b.h5'>
Traceback (most recent call last):
  File "/home/trygveas/pytroll/satpy/satpy/readers/yaml_reader.py", line 695, in _load_dataset
    projectable = fh.get_dataset(dsid, ds_info)
  File "/home/trygveas/pytroll/satpy/satpy/readers/hy2_scat_l2b_h5.py", line 110, in get_dataset
    data = self._mask_data(key['name'], data)
  File "/home/trygveas/pytroll/satpy/satpy/readers/hy2_scat_l2b_h5.py", line 129, in _mask_data
    valid_range = self[key_name].attrs['valid_range']
KeyError: 'valid_range'
[ERROR: 2022-09-28 17:34:17 : satpy.readers.yaml_reader] Could not load dataset 'DataID(name='wvc_lon', resolution=25000, modifiers=())': "Could not load DataID(name='wvc_lon', resolution=25000, modifiers=()) from any provided files"
Traceback (most recent call last):
  File "/home/trygveas/pytroll/satpy/satpy/readers/yaml_reader.py", line 847, in _load_dataset_with_area
    ds = self._load_dataset_data(file_handlers, dsid, **kwargs)
  File "/home/trygveas/pytroll/satpy/satpy/readers/yaml_reader.py", line 719, in _load_dataset_data
    proj = self._load_dataset(dsid, ds_info, file_handlers, **kwargs)
  File "/home/trygveas/pytroll/satpy/satpy/readers/yaml_reader.py", line 704, in _load_dataset
    raise KeyError(
...
```

**Environment Info:**
 - OS: Linux
 - Satpy Version: 0.37.2 from main
 - PyResample Version:
 - Readers and writers dependencies (when relevant): [run `from satpy.utils import check_satpy; check_satpy()`]

**Additional context**
So runing a bit debugging, I see `valid range` is replaced by `valid_range` in `data.attrs`. But in `_mask_data` the `valid_range` is used from self. Which is as far as I can see stil having the `valid range` (without underscrore)

I'm a bit pussled about this, since I'm quite sure this worked in the past. But checking in now I get these error messages.

I need to look at the blame to see if something has been changed in the reader

### PR DESCRIPTION
**Pull request by TAlonglong**
There was a mixture of where attributes were taken from, both data and self[key]
Adding keep_attrs when using xarray.where let us keep the attributes so we can use attributes from that instead of self[key]

 - [X] Closes #2208 
 - [x] Tests added 
 - [x] Fully documented 
 - [x] Add your name to `AUTHORS.md` if not there already

### CODE REVIEW

**Comment by TAlonglong** [comment]
Hm, I don't understand why the tests are failing. When I run the tests locally, they pass.

**Comment by pnuu** [comment]
Often that would mean missing dependencies on CI, but can't see how that would be the case in this one if the tests have been passing before the PR :thinking:

**Comment by TAlonglong** [comment]
Ah, ok. Setting up python 3.8 I get the test to fail. Now I have something to debug.

**Comment by TAlonglong** [comment]
No, it is not the python version but xarray version. upgrading to `xarray                    2022.6.0           pyhd8ed1ab_1    conda-forge`
gives the error. Looks like the `keeps_attrs` is not respected in xarray.where https://docs.xarray.dev/en/stable/generated/xarray.where.html

Hm, do I use it wrong or is there a bug in xarray?

**Comment by djhoese** [comment]
In the docs it says it will take the `attrs` of the first array argument `x`. In both cases of your usage that DataArray doesn't have any `.attrs` I think:

```
data = xr.where(data > 180, data - 360., data, keep_attrs=True)
```

I think `data - 360.0` resets the attrs, but I could be wrong.

In your other case:

```
data = xr.where(data < valid_range[0], np.nan, data, keep_attrs=True)
```

`np.nan` won't have any attrs either.

**Comment by TAlonglong** [comment]
Ah, thanks.

**Comment by TAlonglong** [comment]
Now the test for this change pass as far as I can see. But there is another test failing.

Hm what changed now?

**Comment by djhoese** [comment]
This is a known failure that I need to fix. Someone already added an `atol` in one of the other active PRs. It seems numpy or other precision has changed in recent versions and now one of the tests is being too strict.

**Comment by TAlonglong** [comment]
Yeah, that was my guess also. Should I add this in this PR? Or does it need to be in a separate PR?

Then I can at least make an issue?

**Comment by djhoese** [comment]
If this PR is straight forward and ready to be merged besides the failing test then I'm OK with you adding it here. I think 1e-4 is good enough, but I'd have to search for the other contributor who already fixed it. In another PR I saw yet another test failing, but I don't see that here so we'll have to see what happens.

**Comment by TAlonglong** [comment]
OK, I ran the reader tests locally, and a lot is failing, mainly the same issue:
```
============================================================================== short test summary info ==============================================================================
FAILED satpy/tests/reader_tests/test_seviri_l1b_calibration.py::TestSEVIRICalibrationAlgorithm::test_vis_calibrate - AssertionError: Left and right DataArray objects are not close
FAILED satpy/tests/reader_tests/test_seviri_l1b_hrit.py::TestHRITMSGCalibration::test_calibrate[VIS006-reflectance-NOMINAL-False] - AssertionError: Left and right DataArray objec...
FAILED satpy/tests/reader_tests/test_seviri_l1b_hrit.py::TestHRITMSGCalibration::test_calibrate[VIS006-reflectance-NOMINAL-True] - AssertionError: Left and right DataArray object...
FAILED satpy/tests/reader_tests/test_seviri_l1b_hrit.py::TestHRITMSGCalibration::test_calibrate[HRV-reflectance-NOMINAL-False] - AssertionError: Left and right DataArray objects ...
FAILED satpy/tests/reader_tests/test_seviri_l1b_hrit.py::TestHRITMSGCalibration::test_calibrate[HRV-reflectance-NOMINAL-True] - AssertionError: Left and right DataArray objects a...
FAILED satpy/tests/reader_tests/test_seviri_l1b_native.py::TestNativeMSGCalibration::test_calibrate[VIS006-reflectance-NOMINAL-False] - AssertionError: Left and right DataArray o...
FAILED satpy/tests/reader_tests/test_seviri_l1b_native.py::TestNativeMSGCalibration::test_calibrate[VIS006-reflectance-NOMINAL-True] - AssertionError: Left and right DataArray ob...
FAILED satpy/tests/reader_tests/test_seviri_l1b_native.py::TestNativeMSGCalibration::test_calibrate[HRV-reflectance-NOMINAL-False] - AssertionError: Left and right DataArray obje...
FAILED satpy/tests/reader_tests/test_seviri_l1b_native.py::TestNativeMSGCalibration::test_calibrate[HRV-reflectance-NOMINAL-True] - AssertionError: Left and right DataArray objec...
FAILED satpy/tests/reader_tests/test_seviri_l1b_nc.py::TestNCSEVIRIFileHandler::test_calibrate[VIS006-reflectance-False] - AssertionError: Left and right DataArray objects are no...
FAILED satpy/tests/reader_tests/test_seviri_l1b_nc.py::TestNCSEVIRIFileHandler::test_calibrate[VIS006-reflectance-True] - AssertionError: Left and right DataArray objects are not...
FAILED satpy/tests/reader_tests/test_seviri_l1b_nc.py::TestNCSEVIRIFileHandler::test_get_dataset[VIS006-reflectance] - AssertionError: Left and right DataArray objects are not close
FAILED satpy/tests/reader_tests/test_utils.py::TestSunEarthDistanceCorrection::test_apply_sunearth_corr - AssertionError: 
FAILED satpy/tests/reader_tests/test_utils.py::TestSunEarthDistanceCorrection::test_remove_sunearth_corr - AssertionError: 
FAILED satpy/tests/reader_tests/test_vii_l1b_nc.py::TestViiL1bNCFileHandler::test_calibration_functions - ValueError: ('The number of tie points in the along-route dimension must...
FAILED satpy/tests/reader_tests/test_vii_l1b_nc.py::TestViiL1bNCFileHandler::test_functions - ValueError: ('The number of tie points in the along-route dimension must be a multip...
============================================================== 16 failed, 874 passed, 269 warnings in 96.76s (0:01:36) ==============================================================
```

I think this is better cleaned up separately

**Review by mraspaud — COMMENTED** [review]
Thanks for fixing this. Could you add a test for this?

**Comment by TAlonglong** [comment]
Thats what I wanted. But the tests was passing all the time. And I never figured out why the tests passed and the code did not work with real data. I think it is the way mocking is used.

So then the design of the tests was wrong in the first place.

**Comment by mraspaud** [comment]
> So then the design of the tests was wrong in the first place.

That is very likely indeed. Do you feel like working on it or do you need help?

**Comment by TAlonglong** [comment]
> What do you mean by `self`? You mean the loaded file that you access with `self[some_var_name]`?

yes

**Comment by djhoese** [comment]
I'm still not sure what the original issue is but if you think this helps then try it out and let's see how it goes. FYI `val = self.file_content.__getitem__(key)` is the same as `val = self.file_content[key]`.

**Comment by TAlonglong** [comment]
pre-commit.ci autofix

**Comment by mraspaud** [comment]
@TAlonglong could you try to clean up the history here? there are a lot of old commits hanging around, and that makes is particularly difficult to review

**Comment by TAlonglong** [comment]
yeah, I think I did some merge from the main or rebase that messed this up. I never get these things right.

I don't understand how I could clean this up. I will need to have a look around to see if I can figure something out.

**Comment by djhoese** [comment]
I would suggest maybe creating a new branch off of current `main`, then doing `git cherry-pick <commit SHA>` for each one of your actual commits in this PR. If you do them in order then it might not be too bad.

**Comment by TAlonglong** [comment]
Okay, so I partly did what David suggested. But there was mess of try and fail code, so cherry picking became difficult. So I ended up to create a diff patch and apply that to a new branch #2268

Please feel free to close this PR if that work out.

**Comment by mraspaud** [comment]
I merged #2268, so closing this

**Pull request closed without merging**
