### PR TITLE
Update VIIRS/MODIS ReflecanceCorrector modifier to download DEM data at runtime

### PR DESCRIPTION
**Pull request by djhoese**
This modifier is the last bit of Satpy that I know of that uses an external file for additional functionality. With this PR it now downloads the files specified by the YAML so the results are as accurate as possible.

 - [x] Tests added 
 - [x] Fully documented 
 - [x] Move modifier to satpy.modifiers subpackage
 - [x] Refactor tests to be cleaner and less duplicated code

### CODE REVIEW

**Review by mraspaud — APPROVED** [review]
LGTM

**Comment by mraspaud** [comment]
Anything you can do for the codebeat comment (for crefl that is)?

**Comment by djhoese** [comment]
I'll take a look. FYI we're doing some testing with Polar2Grid that uses this algorithm and I think I need to un-daskify it. Perhaps wrap it in a map_blocks function. I think it is one reason we are seeing major performance issues in my new version of P2G (updates in a later PR of course).

**Comment by djhoese** [comment]
Codebeat issues related to crefl have been fixed. The code is so much better.

Since you approved I will expect either a change of review from you or I will merge it when it passes the tests.

**Comment by mraspaud** [comment]
Yep, go ahead.

**Pull request merged**
