### PR TITLE
Fix SEVIRI native reader flipping

### PR DESCRIPTION
**Pull request by ameraner**
This PR undoes the flipping of the data in the SEVIRI native reader, following the rationale that readers should not modify the original data. 

This is achieved by removing the `flipud `and `fliplr `from `get_dataset`, and by commutating the order of the `area_extent `elements. 
For the HRV channel reading, the order of the parameters for the`StackedAreaDefinition` call needed to be switched.

Test have been updated to reflect the new area extents.

In addition, a new pattern for native files without order number is added. 

 - [x] Tests added 
 - [x] Tests passed 
 - [x] Passes ``flake8 satpy`` 
 - [x] Fully documented

### CODE REVIEW

**Comment by ameraner** [comment]
For the current SEVIRI readers, this is a collection of area extents, including the new set for the updated native reader. `seviri_0deg `is added for reference.

```
seviri_0deg
 (-5570248.686685662, -5567248.28340708,  5567248.28340708,  5570248.686685662)

old native
 (-5570248.477339745, -5567248.074173927, 5567248.074173927, 5570248.477339745)
old native pre 12/2017
 (-5568748.275756836, -5568748.275756836, 5568748.275756836, 5568748.275756836)

nc
 (-5570248.477339745, -5567248.074173927, 5567248.074173927, 5570248.477339745)
hrit
 ( 5567248.28340708,   5570248.686685662,-5570248.686685662,-5567248.28340708)
hrit pre 12/2017
 ( 5568748.28340708,   5568748.686685662,-5568748.686685662,-5568748.28340708)

new native
 (5567248.074173927,   5570248.477339745,-5570248.477339745,-5567248.074173927)
new native pre 2017
 (5568748.275756836,   5568748.275756836,-5568748.275756836,-5568748.275756836)
```

This demonstrates that (up to the decimals), the new native area extent computation is equivalent to the hrit implementation.

The pictures created from the following code confirm that the flipping is successful:
```
channel_name = 'VIS006'
test_image = '../MSG4-SEVI-MSG15-0100-NA-20200506112744.103000000Z-NA.nat'
scn = Scene(reader="seviri_l1b_native", filenames=[test_image])
scn.load(['VIS006'])
scn_res = scn.resample('seviri_0deg')

area = scn_res['VIS006'].attrs['area']
crs = area.to_cartopy_crs()
fig, ax = plt.subplots(subplot_kw={'projection': crs}, figsize=(10,10))
ax.set_extent([0.498-0.75, 2.083+0.75, 38.355, 41.188], crs=ccrs.PlateCarree())
ax.coastlines(resolution='10m')
ax.imshow(scn_res['VIS006'].values, transform=crs, extent=crs.bounds, origin='upper', vmin=0, vmax=30)
```
temp_new_imp

The exact same image is obtained using the old reader implementation. 

**However**, something interesting happens for the HRV channel. Using the same code, following image is produced by the old implementation:
hrvold

While the new implementation produces:
hrvnew

Notice the shift in the N-S axis. So I made a test in `get_dataset `to check if the data behaves as expected:
```
            shape = (self.mda['hrv_number_of_lines'], self.mda['hrv_number_of_columns'])

            raw2 = self.dask_array['hrv']['line_data'][:, 2, :]
            raw1 = self.dask_array['hrv']['line_data'][:, 1, :]
            raw0 = self.dask_array['hrv']['line_data'][:, 0, :]

### OLD IMPLEMENTATION
            shape_layer = (self.mda['number_of_lines'], self.mda['hrv_number_of_columns'])
            data2 = dec10216(raw2.flatten())
            data2 = da.flipud(da.fliplr((data2.reshape(shape_layer))))
            data1 = dec10216(raw1.flatten())
            data1 = da.flipud(da.fliplr((data1.reshape(shape_layer))))
            data0 = dec10216(raw0.flatten())
            data0 = da.flipud(da.fliplr((data0.reshape(shape_layer))))

            data = np.zeros(shape)
            idx = range(0, shape[0], 3)
            data[idx, :] = data2
            idx = range(1, shape[0], 3)
            data[idx, :] = data1
            idx = range(2, shape[0], 3)
            data[idx, :] = data0

### NEW IMPLEMENTATION
            data2 = dec10216(raw2.flatten())
            data2 = data2.reshape(shape_layer)
            data1 = dec10216(raw1.flatten())
            data1 = data1.reshape(shape_layer)
            data0 = dec10216(raw0.flatten())
            data0 = data0.reshape(shape_layer)

            datan = np.zeros(shape)
            idx = range(0, shape[0], 3)
            datan[idx, :] = data2
            idx = range(1, shape[0], 3)
            datan[idx, :] = data1
            idx = range(2, shape[0], 3)
            datan[idx, :] = data0

### COMPARISON
            same = data==np.flipud(np.fliplr(datan))
            plt.figure()
            plt.imshow(same)
            plt.colorbar()
```
This is the output:
image

Zooming into the lower left part:
image

So, the flipping of the data _before_ the lines interleaving seems to produce shifting artifacts. I believe the new implementation fixes this, which is confirmed by the better matching of the image with the coastlines.

**Comment by pnuu** [comment]
The coverage for the `diff` (changes made in this PR) means that only some of the lines were originally covered by the tests, and now as they are changed these changes are not covered by the tests. Well that wasn't very clear :joy:

**Comment by sfinkens** [comment]
Nice work! VISIR extents look good (up to the decimals). And the new extents are consistent with the old ones (including decimals). Can you please show the plot without resampling to `seviri_0deg`?

And thanks for taking the time to compile that list of area extents! So it seems that we have two different image extents among the readers:

```
                                  width             height
        seviri_0deg  11137496.970092742 11137496.970092742
                 nc  11137496.551513672 11137496.551513672
               hrit  11137496.970092742 11137496.970092742
      hrit_pre_2018  11137496.970092742 11137496.970092742
         old_native  11137496.551513672 11137496.551513672
old_native_pre_2018  11137496.551513672 11137496.551513672
new_native 	     11137496.551513672 11137496.551513672
new_native_pre_2018  11137496.551513672 11137496.551513672
```
Also, the difference pre 2018 and post 2018 is exactly 1500 meters in the HRIT reader (hard coded somewhere), whereas it is 1500.2 meters (half a pixel) in the native reader.  We should figure out what's correct. But that's something for another PR ;)

**Comment by ameraner** [comment]
@sfinkens good observation indeed. The MSG Level 1.5 Image Data Format Description  ([link](https://www.eumetsat.int/website/wcm/idc/idcplg?IdcService=GET_FILE&dDocName=PDF_TEN_05105_MSG_IMG_DATA&RevisionSelectionMethod=LatestReleased&Rendition=Web) says:

> The problem is a constant shift of the image by 0.5 low resolution pixels North plus 0.5 low
> resolution pixels West. The HRV channel appears shifted by 1.5 HRV pixels North plus 1.5
> HRV pixels West.

So I think the native implementation, shifting the image by pixel amounts and not hardcoded exact meters, is the most correct.

**Comment by mraspaud** [comment]
> Also, the georeferencing offset correction is exactly 1500 meters in the HRIT reader (hard coded somewhere), whereas it is 1500.2 meters (half a pixel) in the native reader. We should figure out what's correct. But that's something for another PR ;)

I agree that this needs to be fixed, but in another PR.

I'm merging this one as it look good. Thanks for taking the time to look at this in detail!

**Pull request merged**
