### PR TITLE
Make mask dataset a kwarg to resample

### PR DESCRIPTION
**Pull request by ninahakansson**
Make mask dataset a kwarg to resample. And make sure the remapper is cached.

 - [ ] Closes #xxxx 
 - [ ] Tests added 
 - [ ] Fully documented 
 - [ ] Add your name to `AUTHORS.md` if not there already

### CODE REVIEW

**Comment by djhoese** [comment]
I read your issue in #2434, but I still don't understand how you expect to use this keyword argument? Assuming the mask is the same as the geo mask (`mask_area`), is this a workaround for some dask-related issue that isn't sharing computations? Or are you saying you want to assume that the invalid mask between all bands is the same? Is that a safe assumption?

**Comment by ninahakansson** [comment]
In operation I have 10 polar nwcsaf products on the same swath. They are produced with trollflow2. I want images of all products for three formats and three areas. So almost 100 images. And I want them finished in a few minutes (less than 4 would be nice :). 

The same remapper and mask (from the cloudmask) is safe to use for all my 10 products. Using the same mask can also solve some problems "with cloud-free is also nodata" that is present in some of the products. I guess the mask is the same as the invalid mask? So only three remappers (one per area) need to be calculated. This is not possible in satpy currently. With this PR I can do that, but maybe I also broke something and it need to be done in a different way? So this is a feature I would like to add.

I expect to use the mask_array_name like this:
```
  scn2 = scn1.resample("euron1", compute=False, mask_array_name="cloudmask")
 ```
Also the lat/lon for the area should only be calculated one time per area (discussed in the issue). That the calculation is done several times I think is a bug.

**Comment by djhoese** [comment]
Do you have some files for this reader that I could test with?

**Comment by ninahakansson** [comment]
With a non-buggy conda environment and this PR https://github.com/pytroll/satpy/pull/2440 with the new pps-omposites I get my 100 images in less than 4 minutes. As the new compositor uses the same mask when remapping the remapper is cached and reused automatically.

**Pull request closed without merging**
