### PR TITLE
add image comparison behave tests

### PR DESCRIPTION
**Pull request by KatrinPoepp**
Pytroll image comparison dev behave tests as PR. This method of code transfer was proposed by Martin Raspaud.
Documentation for the behave tests will be provided with the rest of the project code.

### CODE REVIEW

**Comment by gerritholl** [comment]
The branch for this PR includes 322 MiB in data (8 PNG files), added in commit 1367072ad008b7281f8ef94d8a72238d8d981b23.  We should probably upload those files somewhere (zenodo?) and then include code to download them on-the-fly, as to not pollute the git repository with large binary files.  This may need rewriting the commit history?

**Comment by pnuu** [comment]
Yes, I think getting completely rid of the images from the repo requires rewriting the git history on force-pushing.

**Comment by gerritholl** [comment]
If we remove the images in a dedicated commit, then squash the commits before merge, would that be enough to remove the images from the git history?

**Comment by gerritholl** [comment]
Related to https://github.com/pytroll/image-comparison-tests-dev/pull/2

**Review by gerritholl — COMMENTED** [review]
start behave test

**Comment by rymdulf** [comment]
Starting to clone and test the repository pytroll/satpy

**Review by gerritholl — COMMENTED** [review]
start behave test

**Review by gerritholl — COMMENTED** [review]
start behave test

**Comment by rymdulf** [comment]
A job is already running for this repository. Please wait for the current job to finish.

**Review by gerritholl — COMMENTED** [review]
start behave test

**Comment by rymdulf** [comment]
Starting to clone and test the repository pytroll/satpy

**Comment by rymdulf** [comment]
The testing process was executed successfully. See the test results for this pull request [here](https://image-test.int-pytroll-development.s.ewcloud.host)!

**Comment by gerritholl** [comment]
The code under `satpy/tests/behave/` is partially duplicated by https://github.com/pytroll/image-comparison-tests-dev/pull/2, for example:

https://github.com/pytroll/image-comparison-tests-dev/blob/106710d3534be8f326d67d3de358a9e210db80f1/behave/create_reference.py

and

https://github.com/KatrinPoepp/satpy/blob/ec4f99623642328f5eeab5691a035871501cd90f/satpy/tests/behave/create_reference.py

**Review by gerritholl — COMMENTED** [review]
start behave test

**Comment by rymdulf** [comment]
Starting to clone and test the repository pytroll/satpy

**Review by gerritholl — COMMENTED** [review]
start behave test

**Comment by rymdulf** [comment]
A job is already running for this repository. Please wait for the current job to finish.

**Comment by rymdulf** [comment]
An error occurred during the process.

**Comment by rymdulf** [comment]
An error occurred during the process.

**Comment by rymdulf** [comment]
Error while cloning the repository: Error while cloning the repository: Command '['docker', 'run', '--name', 'clone-repo-image', '-v', '/home/imagetester/pull_request_pull-branch:/app', '-v', '/home/imagetester/pytroll-image-comparison-tests/data:/app/ext_data', 'python:3.10-slim', 'bash', '-c', 'touch /app/output.log && apt-get update >> /app/output.log 2>&1 && apt-get install -y git libgl1-mesa-glx libglib2.0-0 python3-venv >> /app/output.log 2>&1 && python3 -m venv /app/venv >> /app/output.log 2>&1 && /app/venv/bin/pip install behave Pillow pytest numpy opencv-python dask netcdf4 h5netcdf >> /app/output.log 2>&1 && git clone https://[REDACTED]@github.com/KatrinPoepp/satpy.git --branch pull-branch /app/repository >> /app/output.log 2>&1 && source /app/venv/bin/activate && pip install -e /app/repository >> /app/output.log 2>&1 && source /app/venv/bin/activate && cd /app/repository/satpy/tests/behave && behave >> /app/output.log 2>&1 || true && chown -R 1005:1005 /app >> /app/output.log 2>&1']' returned non-zero exit status 137.

**Review by gerritholl — COMMENTED** [review]
start behave test

**Comment by rymdulf** [comment]
Starting to clone and test the repository pytroll/satpy

**Comment by rymdulf** [comment]
The testing process was executed successfully. See the test results for this pull request [here](https://image-test.int-pytroll-development.s.ewcloud.host)!

**Comment by gerritholl** [comment]
Replaced by https://github.com/pytroll/satpy/pull/2999

**Pull request closed without merging**
