### PR TITLE
[PCW] Metadata from the prologue file incldued in the netCDF files.

### PR DESCRIPTION
**Pull request by loreclem**
The `hrit_msg.py` reader now reads by default all the metadata available in the prologue and epilogue files. This information is stored into the netCDF metadata, when the datasets are saved.

Furthermore, in case the projection used is not compatible with the CF convention, or it is not yet implemented according to this convention, the data is still saved into a netCDF file and a warning is issued.
The proj4 string is stored in the metadata of the netCDF file, using the `grid_proj4` parameter instead of the CF standard `grid_mapping` description.

TODO: make the reading/saving of all metadata from the PROLOGUE/EPILOGUE optional.

### CODE REVIEW

**Comment by mraspaud** [comment]
@loreclem any progress with this ?

**Comment by loreclem** [comment]
@mraspaud not really. I have generated a dataset that I passed to our internal customer and I'm waiting for a feedback on that. Otherwise, I didn't do anything new on this.

**Comment by sfinkens** [comment]
... and the raw metadata from the reader could then look like this

```
IR_108:raw_metadata_file_type = 0LL ;
IR_108:raw_metadata_total_header_length = 6198LL ;
IR_108:raw_metadata_data_field_length = 17223680LL ;
IR_108:raw_metadata_number_of_bits_per_pixel = 10LL ;
IR_108:raw_metadata_number_of_columns = 3712LL ;
IR_108:raw_metadata_number_of_lines = 464LL ;
IR_108:raw_metadata_compression_flag_for_data = 0LL ;
...
```

**Comment by loreclem** [comment]
Hi @sfinkens, this PR is pretty much still work in progress. Unfortunately, I didn't do any progress on this recently due to lack of time. Having said that, I'd be very happy if you bring this forward and I have nothing against what you propose.

We actually generated some test data with the current version, but the nested dictionaries are still not correctly encoded and therefore very difficult to decode (the json serialization should be made recursive).

Otherwise, I'm happy with your proposed solution of having separate attributes for each non-dictionary item, it would actually make things easier to read.

Marco Sassi (MeteoSwiss) will work on this topic during the next PyTroll workshop, so you might also want to get in touch with him on Slack.

**Comment by sfinkens** [comment]
@loreclem Thanks for the feedback! We also need the writer to work, so I already started looking into it :) I think it shouldn't be too hard to make the dictionary unfolding optional. And thanks for pointing me to recursive json encoding, I had overseen that.

**Comment by sfinkens** [comment]
@loreclem If you have time, please check out #736 and let me know what you think!

**Comment by loreclem** [comment]
@sfinkens I think your PR #736 is very valid work and it makes this PR obsolete, it can be closed and deleted.

**Comment by sfinkens** [comment]
@loreclem Thanks for you initial work!

**Pull request closed without merging**
