### PR TITLE
Fix nightly/unstable CI URL

### PR DESCRIPTION
**Pull request by djhoese**
See https://github.com/corteva/rioxarray/pull/257

### CODE REVIEW

**Review by mraspaud — APPROVED** [review]
LGTM. Is this good to merge?

**Comment by djhoese** [comment]
No. See https://github.com/MacPython/scipy-wheels/issues/114

**Comment by djhoese** [comment]
This PR is still failing to pull in the new wheels, but this is only because the old wheels are still listed on the target URL. The scipy dev has asked those with admin privileges to remove these old packages and *then* this should be working.

**Comment by djhoese** [comment]
Upstream looks good. Merging.

**Pull request merged**
