### PR TITLE
Remove py27 tests and switch to py38

### PR DESCRIPTION
**Pull request by djhoese**
Given some recent user issues with python 3.8 I thought I'd try switching to Python 3.8 for our travis tests. At the same time it didn't seem necessary to keep Python 2.7.

 - [ ] Closes #xxxx 
 - [ ] Tests added and test suite added to parent suite 
 - [ ] Tests passed 
 - [ ] Passes ``flake8 satpy`` 
 - [ ] Fully documented

### CODE REVIEW

**Comment by mraspaud** [comment]
Looks good. Should we also remove the py2 support in the setup.py at the same time ?

**Comment by djhoese** [comment]
Yeah probably. This was mostly to help Christian on slack to prove that our tests passed on python 3.8.

**Comment by mraspaud** [comment]
Should start working with this again ? I'd like to remove python 2 tests asap :)

**Comment by djhoese** [comment]
I'd like to get a 0.19.1 out before we cut the py27 tests out.

**Comment by mraspaud** [comment]
ok

**Comment by djhoese** [comment]
Before rerunning tests today: Travis - Passed, Appveyor - Failed
After rerunning tests: Travis - Failed, Appveyor - Passed

:thinking: 

Force numpy to 1.17 on travis to match master branch...

**Pull request merged**
