### PR TITLE
New compositors: MultiFiller and LongitudeMaskingCompositor

### PR DESCRIPTION
**Pull request by ch-k**
I've added to more compositors. They are necessary to create a "world composite" (global mosaic) as described in PR https://github.com/pytroll/satpy/pull/1560 . 
The `MultiFiller` is an extension of `Filler` but works with multiple projectables (including data from optional_datasets). Maybe Filler might be replaced by this one, but I am unsure if it has any side effects.

The `LongitudeMaskingCompositor` makes it possible to mask areas outside spezified min and max longitude values.

 - [x] Tests added 
 - [x] Fully documented

### CODE REVIEW

**Comment by djhoese** [comment]
Correct me if I'm wrong but couldn't the MultiFiller be replaced by using the Filler compositor on each of the inputs to an RGB?

```
RGB ->
  R = Filler -> input1
  G = Filler -> input2
  B = Filler -> input3
  ```

Just curious, what do you use the LongitudeFiller for. I know you said for global composites but in what way? Would it make sense to also allow for latitude?

**Comment by ch-k** [comment]
> Correct me if I'm wrong but couldn't the MultiFiller be replaced by using the Filler compositor on each of the inputs to an RGB?
> 
> ```
> RGB ->
>   R = Filler -> input1
>   G = Filler -> input2
>   B = Filler -> input3
> ```
> 
> Just curious, what do you use the LongitudeFiller for. I know you said for global composites but in what way? Would it make sense to also allow for latitude?

The FillingCompositor fills each of the channels individually. Like a background for all bands. The MultiFiller is more like a chain of the existing Filler  compositor. There's only one output. It can also use more than 3 projectables. In my case, I have images of 5 satellites. I'll attach a sample composite yaml in Monday.

**Comment by djhoese** [comment]
Oh I see now. In the past we've used the MultiScene's `blend` method to stack separate Scene's together. You don't have to do it this way, but I'm curious how you're accomplishing this (combining multiple satellites into one Scene and compositor).

**Comment by ch-k** [comment]
> Oh I see now. In the past we've used the MultiScene's `blend` method to stack separate Scene's together. You don't have to do it this way, but I'm curious how you're accomplishing this (combining multiple satellites into one Scene and compositor).

Sample use case for `LongitudeMaskingCompositor` and `MultiFiller`
```
sensor_name: world-images

composites:

  world_comp_zds_masked:
    compositor: !!python/name:satpy.composites.LongitudeMaskingCompositor
    prerequisites:
    - image_zds
    standard_name: world_comp_zds_masked     
    lon_min: -37.5
    lon_max: 20.75

  world_comp_goes16_masked:
    compositor: !!python/name:satpy.composites.LongitudeMaskingCompositor
    prerequisites:
    - image_goes16
    standard_name: world_comp_goes16_masked     
    lon_min: -105.
    lon_max: -37.5

  world_comp_goes17_masked:
    compositor: !!python/name:satpy.composites.LongitudeMaskingCompositor
    prerequisites:
    - image_goes17
    standard_name: world_comp_goes17_masked     
    lon_min: -177.15
    lon_max: -105.

  world_comp_iodc_masked:
    compositor: !!python/name:satpy.composites.LongitudeMaskingCompositor
    prerequisites:
    - image_iodc
    standard_name: world_comp_iodc_masked     
    lon_min: 20.75
    lon_max: 91.1

  world_comp_himawari8_masked:
    compositor: !!python/name:satpy.composites.LongitudeMaskingCompositor
    prerequisites:
    - image_himawari8
    standard_name: world_comp_himawari8_masked     
    lon_min: 91.1
    lon_max: -177.15


  dwd_world_comp:
    compositor: !!python/name:satpy.composites.MultiFiller
    prerequisites:
    - name: world_comp_zds_masked
    optional_prerequisites:
    - name: world_comp_goes16_masked
    - name: world_comp_goes17_masked 
    - name: world_comp_iodc_masked
    - name: world_comp_himawari8_masked
    standard_name: dwd_world_comp 
  ```

The base channels are defined in following reader config:
```
reader:
    name: world_generic_image
    description: generic image reader
    reader: !!python/name:satpy.readers.yaml_reader.FileYAMLReader
    sensors: [world-images]
    default_channels: [image_goes16, image_goes17]

datasets:
  image_goes16:
    name: image_goes16
    file_type: graphic_goes16
  image_goes17:
    name: image_goes17
    file_type: graphic_goes17
  image_zds:
    name: image_zds
    file_type: graphic_zds
  image_iodc:
    name: image_iodc
    file_type: graphic_iodc
  image_himawari8:
    name: image_himawari8
    file_type: graphic_himawari8

file_types:
    graphic_goes16:
        file_reader: !!python/name:satpy.readers.generic_image.GenericImageFileHandler
        file_patterns:
         - 'goes16_{filename}{start_time:%Y%m%d%H%M}.tif'
         - 'goes16_{filename}.tif'
    graphic_goes17:
        file_reader: !!python/name:satpy.readers.generic_image.GenericImageFileHandler
        file_patterns:
         - 'goes17_{filename}{start_time:%Y%m%d%H%M}.tif'
         - 'goes17_{filename}.tif'
    graphic_zds:
        file_reader: !!python/name:satpy.readers.generic_image.GenericImageFileHandler
        file_patterns:
         - 'ZDS_{filename}{start_time:%Y%m%d%H%M}.tif'
         - 'ZDS_{filename}.tif'
    graphic_iodc:
        file_reader: !!python/name:satpy.readers.generic_image.GenericImageFileHandler
        file_patterns:
         - 'IODC_{filename}{start_time:%Y%m%d%H%M}.tif'
         - 'IODC_{filename}.tif'
    graphic_himawari8:
        file_reader: !!python/name:satpy.readers.generic_image.GenericImageFileHandler
        file_patterns:
         - 'himawari8_{filename}{start_time:%Y%m%d%H%M}.tif'
         - 'himawari8_{filename}.tif'

```

And this would be an example output:

created with:
```
my_files = ['/vagrant/worldcomp/geotiff-in/goes16/wcm10km/goes16_IR_1035_ir_wcm10km_202102182330.tif', 
            '/vagrant/worldcomp/geotiff-in/goes17/wcm10km/goes17_IR_1035_ir_wcm10km_202102182330.tif',
            '/vagrant/worldcomp/geotiff-in/zds/wcm10km/ZDS_IR_108_ir_wcm10km_202102182330.tif',
            '/vagrant/worldcomp/geotiff-in/iodc/wcm10km/IODC_IR_108_ir_wcm10km_202102182330.tif',
            '/vagrant/worldcomp/geotiff-in/himawari8/wcm10km/himawari8_IR1_ir_wcm10km_202102182330.tif',
            
            ]
scn = Scene(reader="world_generic_image", filenames=my_files)
scn.load(['dwd_world_comp'])
scn.show('dwd_world_comp')
```

**Review by djhoese — APPROVED** [review]
Looks good to me. I understand the need for the longitude masking now. It was just odd to see it in a compositor.

**Pull request merged**
