### PR TITLE
Fix exception to catch when new namedtuple syntax is used

### PR DESCRIPTION
**Pull request by mraspaud**
This a quick fix for python 3.6 compatibility.

 - [ ] Passes ``flake8 satpy``

### CODE REVIEW

**Review by djhoese — COMMENTED** [review]
Was this just a wrong assumption on your part on which exception is raised? Also, cool codecov comment/notification.

**Comment by mraspaud** [comment]
Apparently. I just ran the code on 3.6 and could see that the error wasn't as I had expected.

So should we add 3.6 in travis again? To make codecov happy?

**Comment by djhoese** [comment]
I guess if you want to add a 3.6 linux environment it wouldn't hurt, but I'm not sure if conda-forge even still supports it.

**Comment by mraspaud** [comment]
I'm not in favour, but we do say that 3.6 is supported right?

**Comment by mraspaud** [comment]
On pypi.org, for satpy: `Requires: Python >=3.6`. We are now running operationally with conda and newer pythons. @pnuu what do you say.

**Comment by djhoese** [comment]
@mraspaud How about we keep this next release python 3.6 then consider dropping it for the next one (0.24?)?

**Comment by mraspaud** [comment]
Im good with that.

**Comment by mraspaud** [comment]
Merging this in a moment, as soon as the tests pass.

**Pull request merged**
