### PR TITLE
Fixed an error when reading/viewing EUMETSAT ROI Image Products

### PR DESCRIPTION
**Pull request by ColinDuff**
I have updated the native_msg.py reader to fix a problem we had when reading in EUMETSAT ROI Image products.  It appears the number of columns was being padded so that the number of columns where always a multiple of 4. Also the Number of Columns value form the ROI header was always set to 3712. I now use the east / west pixel values.

A check was added so that the memmap array doesn't include the channel id dimension if only 1 channel is present in the file.  

Checked pep8 compliance using geany editor - all ok except for a few long lines 

 Colin

### CODE REVIEW

**Comment by mraspaud** [comment]
Thanks for the PR. Does this work for HRV too ?

**Comment by ColinDuff** [comment]
Actually just spotted it doesnt work for some HRV cases where the padding has been added but works for the other cases. I can investigate further and raise another pull request if you like. Or accept this one and i raise a new PR once the HRV issue is fixed

**Comment by mraspaud** [comment]
I'm in no rush to merged this PR, so just push you new commits to this branch (ColinDuff:develop) and it will update this PR automagically.

**Comment by ColinDuff** [comment]
hi, actually it does work for HRV. The problem i thought i saw was down to we dont create the HRV image for the full disk , only certain parts of the Image so my ROI image for the HRV channel , which i thought had missing data, was in fact correct.

**Comment by ColinDuff** [comment]
Also what about the coverage failure, does a test case need to updated?

**Comment by mraspaud** [comment]
For coverage, there isn't anything to do right now. I'm merging this one, thanks !

**Pull request merged**
