### PR TITLE
Adding VIIRS_GRAN reader: NOAA CLASS - VIIRS EDR  

### PR DESCRIPTION
**Pull request by bbakernoaa**
- [ ] Closes #xxxx 
 - [ ] Tests added 
 - [ ] Tests passed 
 - [ ] Passes ``git diff origin/master **/*py | flake8 --diff`` 
 - [ ] Fully documented

### CODE REVIEW

**Comment by djhoese** [comment]
@bbakernoaa Thanks for adding this and getting this reader started. A few things I'm noticing that may make this more flexible for the future and a few things that need to be fixed:

1. The name in the YAML file will have to match the filename of that YAML file (see failing travis tests).
2. Did you change anything in the file handler code from the original L1B code? Maybe you could use the L1B handler as a base class? I suppose these are supposed to be EDRs and not level 2 files so that may not make sense. This is making me think I need to make a generic CF compliant reader.
3. Could you add some unit tests for this?
4. There are ways to dynamically generate the available DatasetIDs from the contents of the file so they don't all have to be specified in the YAML file. This may make it more flexible in the future if a new variable is added or changed in the file format.

**Comment by djhoese** [comment]
Also what does "GRAN" mean? You may want to update the description of the reader in the YAML file.

**Comment by bbakernoaa** [comment]
> @bbakernoaa Thanks for adding this and getting this reader started. A few things I'm noticing that may make this more flexible for the future and a few things that need to be fixed:
> 
> 1. The name in the YAML file will have to match the filename of that YAML file (see failing travis tests).

Fixed 

> 2. Did you change anything in the file handler code from the original L1B code? Maybe you could use the L1B handler as a base class? I suppose these are supposed to be EDRs and not level 2 files so that may not make sense. This is making me think I need to make a generic CF compliant reader.

No nothing is changed from the original L1B code.  All I did was rename the classes.  

I do think that a generic CF Complaint reader is a great idea.  

> 3. Could you add some unit tests for this?

Yea let me see what I can gather.  

> 4. There are ways to dynamically generate the available DatasetIDs from the contents of the file so they don't all have to be specified in the YAML file. This may make it more flexible in the future if a new variable is added or changed in the file format.

YES this is very daunting and takes way too much time for something that could be generated automatically. I just didn't want huge variable names and such

**Comment by djhoese** [comment]
@bbakernoaa Do you think you'll have time to add tests for this any time soon?

**Comment by bbakernoaa** [comment]
I am not going to be able to address this for a few weeks.  I got
sidetracked with some conferences and stuff coming up.  I will be able to
look at it hopefully soon but I don't know exactly when.

**Comment by djhoese** [comment]
@bbakernoaa The SSEC/CIMSS group has a summer intern working on DNB and Cloud Mask processing and will likely update what you've started here to work with the new versions available on CLASS. If you have any updates to these files or other concerns, let us know.

@tommyjasmin already worked on a TROPOMI reader which did the complex dynamic DatasetID stuff I mentioned above and he'll be working with our intern Daniel on this, so this shouldn't be too bad.

**Comment by bbakernoaa** [comment]
@djhoese This is great news.  I'll be looking forward to this.  Unfortunately, I don't have any updates to this.

**Comment by djhoese** [comment]
@bbakernoaa I thought you were going to leave this alone so that Daniel (our intern) could work on it? He has been working on it in a separate branch on his own fork.

**Comment by djhoese** [comment]
FYI @dhueholt ^

**Comment by djhoese** [comment]
Closing to avoid confusion. Newest version of this PR is #951.

**Pull request closed without merging**
