### PR TITLE
Update FCI L1c reader to work with remote file systems

### PR DESCRIPTION
**Pull request by pnuu**
This PR adapts the FCI L1c reader so that it is able to read data from remote locations using `fsspec`.

```python
fnames = ["simplecache::s3://satellite-data-fci-test-data-2022/*DEV_20170920112*.nc"]
scn = Scene(reader='fci_l1c_nc', filenames=fnames)
scn.load(['ir_123'])
scn.save_datasets()
```

See the [documentation](https://satpy.readthedocs.io/en/stable/remote_reading.html) for more information on accessing remote data.

 - [x] Tests added 
 - [x] Fully documented

### CODE REVIEW

**Comment by gerritholl** [comment]
Unless there is a public place with FCI data served over S3, I can't test the remote reading functionality.  However, for local processing, there is a severe regression in performance.  Generating three channels and one composite from compressed full disc on my workstation, without resampling: without this PR, 38.7 seconds.  With this PR, 1 minutes 55 seconds.  That's roughly 3× longer.  This PR should make sure that there is no regression in the performance for local processing, which will remain the most common use case.

At the same time, RAM usage is down from 4.3 GB to 2.9 GB, but in this case I believe wall clock time will worry users more.

Satpy main:

```

        Command being timed: "python /home/gholl/checkouts/protocode/fci-true-color.py"
        User time (seconds): 88.84
        System time (seconds): 3.90
        Percent of CPU this job got: 239%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 0:38.67
        Average shared text size (kbytes): 0
        Average unshared data size (kbytes): 0
        Average stack size (kbytes): 0
        Average total size (kbytes): 0
        Maximum resident set size (kbytes): 4329920
        Average resident set size (kbytes): 0
        Major (requiring I/O) page faults: 0
        Minor (reclaiming a frame) page faults: 616257
        Voluntary context switches: 16582
        Involuntary context switches: 25305
        Swaps: 0
        File system inputs: 245656
        File system outputs: 109240
        Socket messages sent: 0
        Socket messages received: 0
        Signals delivered: 0
        Page size (bytes): 4096
        Exit status: 0
```

With this PR:

```
        Command being timed: "python /home/gholl/checkouts/protocode/fci-true-color.py"
        User time (seconds): 169.68
        System time (seconds): 2.80
        Percent of CPU this job got: 147%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 1:57.20
        Average shared text size (kbytes): 0
        Average unshared data size (kbytes): 0
        Average stack size (kbytes): 0
        Average total size (kbytes): 0
        Maximum resident set size (kbytes): 2893340
        Average resident set size (kbytes): 0
        Major (requiring I/O) page faults: 0
        Minor (reclaiming a frame) page faults: 366179
        Voluntary context switches: 21684
        Involuntary context switches: 19337
        Swaps: 0
        File system inputs: 246760
        File system outputs: 109240
        Socket messages sent: 0
        Socket messages received: 0
        Signals delivered: 0
        Page size (bytes): 4096
        Exit status: 0
```

**Comment by pnuu** [comment]
Thanks for testing! I noticed the same increase in processing time for local files, but didn't yet have time to look into it. My guess is some `da.array()` calls or such are causing unnecessary computes.

**Comment by djhoese** [comment]
FYI just to put this somewhere, I found this: https://github.com/cedadev/S3-netcdf-python

**Comment by djhoese** [comment]
And...https://docs.unidata.ucar.edu/nug/current/nczarr_head.html

**Comment by mraspaud** [comment]
@pnuu This is waiting for the FCI performance PR, right?

**Comment by pnuu** [comment]
@mraspaud yes, indeed. I'm planning on working on this and the performance tweaking during PCW.

**Comment by pnuu** [comment]
I've made some progress based on https://github.com/pytroll/satpy/pull/2237/commits/bb7c313aff078fe0ae3e0618f78b913a310bbfe5 . With that, I can create 20 resampled day/night composites in 140 seconds, which is roughly 40 seconds more than by using the `netcdf4` version. The changes took 60+ seconds off from the scene creation, and the overall processing time is now pretty usable.

I'll convert this PR to draft, and eventually replace with a new PR that'll be in sync with https://github.com/pytroll/satpy/pull/2237

**Comment by pnuu** [comment]
Closing due to #2305 which is based on recently merged PRs handling FCI data.

**Pull request closed without merging**
