### PR TITLE
Use the cira stretch also for the true_color_ahi_default

### LINKED ISSUE #127: High resolution 'true_color' composite issue for Himawari-8 AHI
#### Code Sample, a minimal, complete, and verifiable piece of code

```python
from satpy.scene import Scene
from datetime import datetime, timedelta


ppp_config_directory = "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/satpy-0.7.5-py2.7.egg/satpy/etc/"
path = "/Users/andyprata/Documents/python/himawari-8/hsd"
path_output = "/Users/andyprata/Documents/python/himawari-8/png/"

time_slot = datetime(2017, 11, 26, 23)
time_slot_str = time_slot.strftime("%Y%m%d%H%M")
fn_out = 'global_hima_'+time_slot_str
print "Processing: "+time_slot_str
global_scene = Scene(platform_name="Himawari-8", sensor="ahi", reader="ahi_hsd",
                     start_time=time_slot,
                     end_time=time_slot + timedelta(minutes=10),
                     base_dir=path,
                     ppp_config_dir=ppp_config_directory)

rgb_composite = 'true_color'
print "Loading composite: "+rgb_composite
global_scene.load([rgb_composite])
print "Saving file..."
global_scene.save_dataset(rgb_composite, path_output+fn_out+'_'+rgb_composite+'.png')
print "Done. File saved here: " + path_output+fn_out+'_'+rgb_composite+'.png'
```
#### Problem description
The issue has been described here: https://groups.google.com/forum/#!topic/pytroll/pN9JLV2j-88
The above code results in the following error: 
KeyError: "No dataset matching 'true_color' found"
The following workaround can be used to avoid the above error, but the output is not the expected result:
```python
local_scene = global_scene.resample(global_scene['B03'].info['area'])
local_scene.save_dataset(rgb_composite, path_output+fn_out+'_'+rgb_composite+'.png')
```
#### Expected Output
image
Note: this image was generated using the 'true_color_reducedsize' composite.
#### Actual Result, Traceback if applicable
image

#### Versions of Python, package at hand and relevant dependencies
Python version: 2.7.14
NumPy version: 1.13.1

### PR DESCRIPTION
**Pull request by adybbroe**
Signed-off-by: Adam.Dybbroe <adam.dybbroe@smhi.se>

Please make the PR against the `develop` branch.

 - [x] Closes #127 
 - [x] Tests passed (for all non-documentation changes)
 - [x] Passes ``git diff origin/develop **/*py | flake8 --diff``

### CODE REVIEW

**Comment by adybbroe** [comment]
So, with this it is possible to derive a proper high resolution AHI true color with the workaround mentioned in issue #127

**Comment by davidh-ssec** [comment]
Do we want to take this opportunity to rename all `true_color_X` standard names to just `true_color`?

**Comment by adybbroe** [comment]
@davidh-ssec Sounds like a good idea, or we do it a new PR I am preparing which conserns the way we do the true color. We have decided to use the red channel instead of the blue channel when damping the correction. This is the damping we use to reduce correction over clouds and snow areas (usually correlated with high terrain). Using the red channel is conceptually more correct and we have seen it already improves the imagery nicely!

**Comment by adybbroe** [comment]
Oh, I thought the problem with true_color_X names were more widespread, but it seems to be only AHI, right?

**Pull request merged**
