### PR TITLE
Add support for MCMIP GOES ABI L2 files

### LINKED ISSUE #1162: abi_l2_nc reader unable to read MCMIP files
Dear Developers,
I'm using satpy 0.21 from this git-repo.
But I cannot read with satpy abi_l2_nc reader GOES16 data.
So can one read GOES16 ABI-L2 data with satpy, have I just not installed the reader?
Cheers, Markus
below the data is read fine with xarray but I have problems wih satpy...
Can one somehow set the data read by xarray into satpy into 

```
 self.data = xarray.open_dataset(fileName)
 print("DATA KEYS:", self.data.keys())
 scn = Scene(reader='abi_l2_nc', filenames=[fileName])
```
xarray reads the data fine but satpy gives an error.

> DOWNLOAD: noaa-goes16/ABI-L2-MCMIPF/2019/244/18/OR_ABI-L2-MCMIPF-M6_G16_s20192441800192_e20192441809505_c20192441810011.nc
File already there (not downloading): /home/hu-mka/Downloads/OR_ABI-L2-MCMIPF-M6_G16_s20192441800192_e20192441809505_c20192441810011.nc
DATA KEYS: KeysView(<xarray.Dataset>
Dimensions:                                 (band: 1, number_of_image_bounds: 2, number_of_time_bounds: 2, x: 5424, y: 5424)
Coordinates:
    t                                       datetime64[ns] ...
    y                                       (y) float32 0.151844 ... -0.151844
    x                                       (x) float32 -0.151844 ... 0.151844
    y_image                                 float32 ...
    x_image                                 float32 ...
    band_wavelength_C01                     (band) float32 ...
    band_wavelength_C02                     (band) float32 ...
    band_wavelength_C03                     (band) float32 ...
    band_wavelength_C04                     (band) float32 ...
    band_wavelength_C05                     (band) float32 ...
    band_wavelength_C06                     (band) float32 ...
    band_wavelength_C07                     (band) float32 ...

> No filenames found for reader: abi_l2_nc
Don't know how to open the following files: {'/home/hu-mka/Downloads/OR_ABI-L2-MCMIPF-M6_G16_s20192441800192_e20192441809505_c20192441810011.nc'}

### PR DESCRIPTION
**Pull request by duncanwp**
Adds support for multi-channel Cloud Moisture Imagery (MCMIP) ABI files (as available on e.g. AWS)

 - [x] Closes #1162
 - [x] Tests added 
 - [x] Tests passed 
 - [x] Passes ``flake8 satpy`` 
 - [x] Fully documented 
 - [ ] Add your name to `AUTHORS.md` if not there already

### CODE REVIEW

**Comment by djhoese** [comment]
You mentioned you are getting an error:

```
  File "./process_goes_l2_se_pacific_hackathon.py", line 118, in load_and_save_vars
    scn.load(variables)
  File "/home/ubuntu/anaconda3/envs/satpy/lib/python3.7/site-packages/satpy/scene.py", line 973, in load
    self.read(**kwargs)
  File "/home/ubuntu/anaconda3/envs/satpy/lib/python3.7/site-packages/satpy/scene.py", line 880, in read
    return self._read_datasets(nodes, **kwargs)
  File "/home/ubuntu/anaconda3/envs/satpy/lib/python3.7/site-packages/satpy/scene.py", line 721, in _read_datasets
    new_datasets = reader_instance.load(ds_ids, **kwargs)
  File "/home/ubuntu/anaconda3/envs/satpy/lib/python3.7/site-packages/satpy/readers/yaml_reader.py", line 872, in load
    ds = self._load_dataset_with_area(dsid, coords, **kwargs)
  File "/home/ubuntu/anaconda3/envs/satpy/lib/python3.7/site-packages/satpy/readers/yaml_reader.py", line 775, in _load_dataset_with_area
    file_handlers = self._get_file_handlers(dsid)
  File "/home/ubuntu/anaconda3/envs/satpy/lib/python3.7/site-packages/satpy/readers/yaml_reader.py", line 721, in _get_file_handlers
    filetype = self._preferred_filetype(ds_info['file_type'])
  File "/home/ubuntu/anaconda3/envs/satpy/lib/python3.7/site-packages/satpy/readers/yaml_reader.py", line 684, in _preferred_filetype
    if filetype in self.file_handlers:
TypeError: unhashable type: 'dict'
```

Maybe this scheme of file_type as a dictionary isn't actually supported. I know we have things like:

```
  '2':
    name: '2'
    resolution:
      250: {file_type: hdf_eos_data_250m}
      500: {file_type: hdf_eos_data_500m}
      1000: {file_type: hdf_eos_data_1000m}
```

So each resolution has it's own file_type but maybe not the other way around. I'll have to look into this more. This may not be as easy as I had hoped.

**Comment by duncanwp** [comment]
Yeah, I suspect you're right. Let me know if you think of anthing. Thanks

**Comment by djhoese** [comment]
So there are ways to make this work without supporting the file_type dictionary stuff but I think they still require modifying python code. For example, you could look at modifying:

https://github.com/pytroll/satpy/blob/fab1e8a355f83df9bd26cacd3719dadcc08084f1/satpy/readers/abi_l2_nc.py#L38-L40

So that it checks what the current file_type is. So maybe:

```
var = info['file_key']
if self.filetype_info['file_type'] == 'abi_l2_mcmip':
     var += "_" + key.name
```

Then in YAML change your file_types to `file_type: [abi_l2_cmip_c16, abi_l2_mcmip]`. This should work but it isn't as pretty or flexible as I'd like. @mraspaud ideas?

**Comment by djhoese** [comment]
@duncanwp Any time to look at changing the code above as I suggested?

**Comment by duncanwp** [comment]
Hey @djhoese, I'm struggling at the moment and it's not something I need anymore... If it's useful for someone else I can take another look at it otherwise it might be best to close it.

**Review by mraspaud — APPROVED** [review]
LGTM

**Pull request merged**
