### PR TITLE
add flash_area composite for LI L2

### PR DESCRIPTION
**Pull request by TAlonglong**
Add simple composite to be able to demostrate LI L2 capabilities of satpy

### CODE REVIEW

**Review by djhoese — APPROVED** [review]
This seems fine to me, but I know nothing about LI so someone on the EU side should really review this.

**Comment by mraspaud** [comment]
@sjoro @seeno opinions on this PR?

**Comment by gerritholl** [comment]
What does it look like?  Could you perhaps add an image to this PR?

**Comment by gerritholl** [comment]
For lightning it might be nice if 0 is transparent rather than yellow.  I don't know if there is a different way to do that apart from making an RGBA version of the indicated colormap.  It seems all the named colormaps built into trollimage are RGB and none are RGBA.

**Review by pnuu — APPROVED** [review]
LGTM. I've already used this as a basis on highlighting lightning on top of a SEVIRI composite.

**Comment by TAlonglong** [comment]
flash_area

**Comment by pnuu** [comment]
The failing unstable tests are something in `holoviews`. I saw that mentioned somewhere, and in any case should be handled in a PR touching code. Merging.

**Comment by TAlonglong** [comment]
flash_area

**Comment by pnuu** [comment]
> For lightning it might be nice if 0 is transparent rather than yellow.

For zero flash area there is no data, so those areas are transparent.

**Pull request merged**
