### PR TITLE
Cleaning up and adding MERSI-2 RGB composites

### PR DESCRIPTION
**Pull request by adybbroe**
Signed-off-by: Adam Dybbroe <Adam.Dybbroe@smhi.se>

Adding composites for MERSI-2 and cleaning up those that can't be made (airmass for instance)

 - [ ] Closes #xxxx 
 - [ ] Tests added and test suite added to parent suite 
 - [x] Tests passed 
 - [x] Passes ``flake8 satpy`` 
 - [ ] Fully documented 
 - [x] Add your name to `AUTHORS.md` if not there already

### CODE REVIEW

**Comment by djhoese** [comment]
I restarted the tests now that the new pyresample and trollimage were released and they passed. @adybbroe Any comment on my comment? Otherwise, we can talk about this in Boston next week.

**Comment by adybbroe** [comment]
Sorry @djhoese Didn't pay attention, and missed your input
There is something strange with the MERSI-2 data I think especially concerning the 1.6 and 3.7 bands, that influence the look of some the RGBs, cloudtop is one of them. I really don't like to need a special enhancement for MERSI-2, but thought we could keep until we have figured out what's going on with the channels?

**Comment by adybbroe** [comment]
@djhoese Concerning resolution, for MERSI-2 several of the bands are 250 m, and comes also in aggregated form (1km). I wanted to focus on the legacy 1km band resolution first. Then we can add higher resolution composites later

**Comment by djhoese** [comment]
> Concerning resolution, for MERSI-2 several of the bands are 250 m, and comes also in aggregated form (1km). I wanted to focus on the legacy 1km band resolution first. Then we can add higher resolution composites later

I would argue that this goes against what we do in the rest of Satpy. It is possible to request a low-resolution version by doing `scn.load(['some_composite'], resolution=1000)` if that is what someone would like to do. Otherwise, native resampling or regular resampling is available for getting the bands to the same resolution. A user could also only provide the 1000m files if that is the only thing they wanted. Forcing and limiting the composite recipe should be something the user controls when the recipe/code can handle multiple resolutions.

**Comment by adybbroe** [comment]
Ok, @djhoese I agree! Let me just try see if I can make the composites work the way they should without resolution!

**Comment by adybbroe** [comment]
...takes forever to get the MERSI data to my laptop, didn't bring any. So might need to wait till the evening before I can test @djhoese ...

**Comment by adybbroe** [comment]
Ok, think I cleaned up the composite recipes. I verified most of the RGBs in both 250m and 1000m, works! Thanks @djhoese

**Comment by mraspaud** [comment]
@djhoese are we glad with this one ?

**Pull request merged**
