### PR TITLE
Fix filter in modis_l2.yaml

### LINKED ISSUE #2298: There is a bug in 'find_files_and_readers(reader='modis_l2)''
**Describe the bug**
It didn't work as a filter.

**To Reproduce**

```python
MOD_dir = 'F:/yydata/MODIS/'
Y=2022
M=10
D=7
h=1
m=45
MO_cloud_name = find_files_and_readers(start_time=datetime.datetime(Y, M, D, h, m),
                                       base_dir=MOD_dir,
                                       reader='modis_l2')
print(MO_cloud_name)

```

**Expected behavior**
The correct result is {'modis_l2': ['F:/yydata/MODIS\\MOD35_L2.A2022113.0325.061.2022113133154.hdf', 'F:/yydata/MODIS\\MOD03.A2022280.0145.061.2022280064847.hdf']}

**Actual results**
{'modis_l2': ['F:/yydata/MODIS\\MOD35_L2.A2022113.0325.061.2022113133154.hdf', 'F:/yydata/MODIS\\MOD35_L2.A2022056.0155.061.2022056133703.hdf', 'F:/yydata/MODIS\\MOD35_L2.A2022113.0145.061.2022113133304.hdf', 'F:/yydata/MODIS\\MOD35_L2.A2022280.0145.061.2022280130947.hdf', 'F:/yydata/MODIS\\MOD35_L2.A2022129.0145.061.2022129133116.hdf', 'F:/yydata/MODIS\\MOD35_L2.A2022129.0325.061.2022129133249.hdf', 'F:/yydata/MODIS\\MOD35_L2.A2022056.0330.061.2022056133549.hdf', 'F:/yydata/MODIS\\MOD03.A2022280.0145.061.2022280064847.hdf']}

### PR DESCRIPTION
**Pull request by springfieldpsk**
I see Issue #2298 and help fix it

This PR replace `acquisition_time` with `start_time`,to make filter have correct result

https://github.com/pytroll/satpy/blob/6dfb9b9353fa64e91a1f7553783abd859042da56/satpy/etc/readers/modis_l2.yaml#L14

+ fix #2298

### CODE REVIEW

**Comment by djhoese** [comment]
@springfieldpsk Thanks for starting this. Could you do another commit to your branch and update the other filename patterns in that file that use `acquisition_time`?

**Comment by springfieldpsk** [comment]
@djhoese no problem

**Comment by djhoese** [comment]
I made one more change to the Python code to see `acquisition_time` needs to be checked at all in the python code. If this breaks I'll fix it.

**Comment by djhoese** [comment]
What do you think @mraspaud about tests for this? We don't really have tests for `find_files_and_readers` in the reader-specific tests, but we also don't (I think) have reader-specific checks of `find_files_and_readers`. Hhhmmm :thinking: maybe we could have a test for the filtering of the reader since that is what `find_files_and_readers` uses (so create an instance of the reader with multiple times of files and provide filter_parameters to limit by start time).

Or no new tests.

**Review by mraspaud — APPROVED** [review]
LGTM

**Comment by mraspaud** [comment]
I don't think this needs a test for find files and readers. Merging

**Pull request merged**
