### PR TITLE
Fix DeprecationWarning: invalid escape sequence in versioneer.py

### PR DESCRIPTION
**Pull request by BoboTiG**
- [x] Passes ``git diff origin/master -- "*py" | flake8 --diff``

### CODE REVIEW

**Comment by djhoese** [comment]
Thanks for this @BoboTiG. I'm curious, how did you run in to this issue? Is this something the versioneer project has suggested people do? Are you part of the versioneer project?

**Comment by BoboTiG** [comment]
I found the issue by using this command:
```shell
PYTHONWARNINGS=all python -m compileall * >/dev/null
```
Those `DeprecationWarning`s are already converted to `SyntaxWarning`s in Python 3.8 and will become `SyntaxError`s in Python 4.0.

I opened a PR: ryanpdwyer/versioneer2#1, but I am not part of the project :)

**Comment by djhoese** [comment]
I believe the proper project for this (that we used to install these files in satpy) is this one: https://github.com/warner/python-versioneer

Thanks for your help. I want to wait to see what the versioneer maintainers do with the fix (could you please make a PR on that repository?) before merging this one to make sure we match what they are doing.

**Comment by BoboTiG** [comment]
Sure, I will open a PR in that repository too. Let's wait for their decision :)

**Comment by djhoese** [comment]
@BoboTiG I may be missing something. What part of that PR refers to the changes you've made here?

**Comment by djhoese** [comment]
@BoboTiG Have you seen any updates on this? It looks like that PR hasn't been responded to.

**Comment by BoboTiG** [comment]
Nope, the project seems dead :/

**Comment by djhoese** [comment]
It does look that way doesn't it. @mraspaud any idea if the other "big" projects using versioneer do anything special for newer code? I didn't see any fork that was obviously the replacement. I could ask around but don't remember what projects were using it (xarray?).

**Comment by mraspaud** [comment]
dask and xarray do iirc

**Comment by djhoese** [comment]
We no longer use versioneer so this PR is no longer needed. Thanks for bringing it to our attention and sorry for taking so long to continue the discussion.

**Pull request closed without merging**
