### PR TITLE
Reduce Dask computations in `DayNightCompositor`

### LINKED ISSUE #2614: DayNightCompositor triggers early dask computation
**Describe the bug**

Loading composites that use the `DayNightCompositor` trigger an early dask computation.

**To Reproduce**

```python
import dask.config
from satpy.tests.utils import CustomScheduler
from satpy import Scene
from glob import glob
seviri_files = glob("/media/nas/x21308/scratch/SEVIRI/202103300900/H-000*")
sc = Scene(filenames={"seviri_l1b_hrit": seviri_files})
with dask.config.set(scheduler=CustomScheduler(max_computes=1)):
    sc.load(["natural_color_with_night_ir"])
    ls = sc.resample("eurol")
    ls.compute()
```

**Expected behavior**

I expect that exactly one computation occurs, in `ls.compute()`.  Therefore, I expect no output.

**Actual results**

In reality, this fails with:

```python-traceback
Traceback (most recent call last):
  File "/data/gholl/checkouts/protocode/mwe/day-night-compute.py", line 10, in <module>
    ls.compute()
  File "/data/gholl/checkouts/satpy/satpy/scene.py", line 1294, in compute
    datasets = compute(*(new_scn._datasets.values()), **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/gholl/mambaforge/envs/py311/lib/python3.11/site-packages/dask/base.py", line 628, in compute
    results = schedule(dsk, keys, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/gholl/checkouts/satpy/satpy/tests/utils.py", line 288, in __call__
    raise RuntimeError("Too many dask computations were scheduled: "
RuntimeError: Too many dask computations were scheduled: 3
```

NB: it says there were three computations, even though one would expect it should fail as soon as it tries to calculate number two — see "Additional context" for comments on why this happens.

**Environment Info:**
 - OS: Linux
 - Satpy Version: main

**Additional context**

The early computes that happen before `ls.compute()` are not easily seen, because the `ValueError` raised in `satpy.tests.utils.CustomScheduler` is swallowed by dask in `compute_meta`.  See #2615 for more details, but briefly:

https://github.com/dask/dask/blob/2023.9.3/dask/array/utils.py#L95-L96

When we run with `max_computes=0` and set a breakpoint in `satpy/tests/utils.py:288`, we can investigate the traceback and why `compute_meta` gets called:

```python-traceback
  File "/data/gholl/checkouts/protocode/mwe/day-night-compute.py", line 9, in <module>
    ls = sc.resample("eurol")
  File "/data/gholl/checkouts/satpy/satpy/scene.py", line 983, in resample
    new_scn.generate_possible_composites(unload)
  File "/data/gholl/checkouts/satpy/satpy/scene.py", line 1508, in generate_possible_composites
    keepables = self._generate_composites_from_loaded_datasets()
  File "/data/gholl/checkouts/satpy/satpy/scene.py", line 1527, in _generate_composites_from_loaded_datasets
    return self._generate_composites_nodes_from_loaded_datasets(needed_comp_nodes)
  File "/data/gholl/checkouts/satpy/satpy/scene.py", line 1533, in _generate_composites_nodes_from_loaded_datasets
    self._generate_composite(node, keepables)
  File "/data/gholl/checkouts/satpy/satpy/scene.py", line 1591, in _generate_composite
    composite = compositor(prereq_datasets,
  File "/data/gholl/checkouts/satpy/satpy/composites/__init__.py", line 714, in __call__
    weights = self._mask_weights_with_data(weights, day_data, night_data)
  File "/data/gholl/checkouts/satpy/satpy/composites/__init__.py", line 789, in _mask_weights_with_data
    return da.where(mask, weights, np.nan)
  File "/data/gholl/mambaforge/envs/py311/lib/python3.11/site-packages/dask/array/routines.py", line 2107, in where
    return elemwise(np.where, condition, x, y)
  File "/data/gholl/mambaforge/envs/py311/lib/python3.11/site-packages/dask/array/core.py", line 4831, in elemwise
    result = blockwise(
  File "/data/gholl/mambaforge/envs/py311/lib/python3.11/site-packages/dask/array/blockwise.py", line 286, in blockwise
    meta = compute_meta(func, dtype, *args[::2], **kwargs)
  File "/data/gholl/mambaforge/envs/py311/lib/python3.11/site-packages/dask/array/utils.py", line 140, in compute_meta
    meta = func(*args_meta, **kwargs_meta)
  File "<__array_function__ internals>", line 200, in where
  File "/data/gholl/mambaforge/envs/py311/lib/python3.11/site-packages/xarray/core/common.py", line 165, in __array__
    return np.asarray(self.values, dtype=dtype)
  File "/data/gholl/mambaforge/envs/py311/lib/python3.11/site-packages/xarray/core/dataarray.py", line 759, in values
    return self.variable.values
  File "/data/gholl/mambaforge/envs/py311/lib/python3.11/site-packages/xarray/core/variable.py", line 616, in values
    return _as_array_or_item(self._data)
  File "/data/gholl/mambaforge/envs/py311/lib/python3.11/site-packages/xarray/core/variable.py", line 309, in _as_array_or_item
    data = np.asarray(data)
  File "/data/gholl/mambaforge/envs/py311/lib/python3.11/site-packages/dask/array/core.py", line 1700, in __array__
    x = self.compute()
  File "/data/gholl/mambaforge/envs/py311/lib/python3.11/site-packages/dask/base.py", line 342, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/data/gholl/mambaforge/envs/py311/lib/python3.11/site-packages/dask/base.py", line 628, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/data/gholl/checkouts/satpy/satpy/tests/utils.py", line 288, in __call__
    raise RuntimeError("Too many dask computations were scheduled: "
```

The `da.where` call in `satpy.composites` passes xarray types to dask:

```python
In [3]: print(mask)
<xarray.DataArray (y: 2048, x: 2560)>
dask.array<or_, shape=(2048, 2560), dtype=bool, chunksize=(2048, 2560), chunktype=numpy.ndarray>
Coordinates:
  * y            (y) float64 -1.502e+06 -1.504e+06 ... -7.64e+06 -7.642e+06
  * x            (x) float64 -3.778e+06 -3.776e+06 ... 3.896e+06 3.898e+06
    crs          object PROJCRS["unknown",BASEGEOGCRS["unknown",DATUM["Unknow...
    bands        <U1 'R'
    spatial_ref  int64 0

In [4]: print(weights)
<xarray.DataArray '_cos_zen_ndarray-2b25ca5da362f711551dec6e02deccd8' (y: 2048,
                                                                       x: 2560)>
dask.array<clip, shape=(2048, 2560), dtype=float64, chunksize=(2048, 2560), chunktype=numpy.ndarray>
Dimensions without coordinates: y, x
```

I'm still not sure why this triggers a computation of metadata, but perhaps it could be avoided by passing dask array or using xarray.where.

### PR DESCRIPTION
**Pull request by pnuu**
This PR gets rid of unnecessary Dask computations in `DayNightCompositor`. This is enforced with a custom scheduler for the compositor tests.

 - [x] Closes #2614 
 - [x] Tests added 
 - [ ] Fully documented 
 - [ ] Add your name to `AUTHORS.md` if not there already

### CODE REVIEW

**Comment by pnuu** [comment]
The tests fail (at least) locally, even though I get identical results with real composites with the three composite types we have:
```yaml
  natural_color_day_only:
    compositor: !!python/name:satpy.composites.DayNightCompositor
    standard_name: natural_color_day_only
    day_night: day_only
    include_alpha: true
    lim_low: 87.0
    lim_high: 93.0
    prerequisites:
      - name: natural_color

  night_microphysical_night_only:
    compositor: !!python/name:satpy.composites.DayNightCompositor
    standard_name: night_microphysical_night_only
    day_night: night_only
    include_alpha: True
    lim_low: 87.0
    lim_high: 87.0
    prerequisites:
      - name: night_microphysical

  vis06_with_ir108:
    compositor: !!python/name:satpy.composites.DayNightCompositor
    standard_name: vis06_with_ir108
    lim_low: 85.0
    lim_high: 88.0
    prerequisites:
      - vis06
      - ir108
```

My test script (adapted from the original by @gerritholl):

```python
#!/usr/bin/env python

import dask.config
from satpy.tests.utils import CustomScheduler
from satpy import Scene
from glob import glob
seviri_files = glob("/home/lahtinep/data/satellite/geo/0deg/*202303080900*")
sc = Scene(filenames={"seviri_l1b_hrit": seviri_files})
with dask.config.set(scheduler=CustomScheduler(max_computes=1)):
    sc.load(["natural_color_day_only", "night_microphysical_night_only", "vis06_with_ir108"])
    ls = sc.resample("eurol")
    ls.save_datasets(base_dir="/tmp")
```

**Comment by pnuu** [comment]
There was a simple logic error when I converted the calls, still trying to figure out the `IncompatibleAreas` exception.

**Comment by pnuu** [comment]
I don't see any places in the compositor where `DataArray.data` are replaced.

The failure is in the only test where SZA data are not provided and both day and night data are used. This works with real data (I'm testing with SEVIRI HRIT), so I'm I guess the fake data in the test class is somehow wrong.

**Comment by pnuu** [comment]
Ok, my real data test was using a composite where both day and night parts were single channels. With RGB sub-composites I get
```
RuntimeError: None of the requested datasets have been generated or could not be loaded. Requested composite inputs may need to have matching dimensions (eg. through resampling).
```
The DataArray`s passed in the `data` list have identical areas and shapes when passed to `super(DayNightCompositor, self).__call__(data, **kwargs)`.

Switching the mock data in the test to 1D makes the failing test pass.

**Comment by pnuu** [comment]
Found something that works, not entirely sure why: use `.data` when applying the weights to day and night composites, not the `DataArray`. I don't know why this makes any difference when comparing the areas, the attributes are handled separately in any case. So might be there's a try/except somewhere that masks the original exception.

**Review by mraspaud — APPROVED** [review]
LGTM!

**Comment by djhoese** [comment]
This might be a case where type annotations would make it more clear what type of objects are being passed where and if we can expect them to work. I'll try to review this in detail this morning and merge if it all looks good. Thanks for tackling this @pnuu!

**Comment by djhoese** [comment]
Ok I did some debugging into this. What happens is we call this method:

```
    def _mask_weights_with_data(self, weights, day_data, night_data):
        data_a = _get_single_channel(day_data)
        data_b = _get_single_channel(night_data)
        if "only" in self.day_night:
            mask = _get_weight_mask_for_single_side_product(data_a, data_b)
        else:
            mask = _get_weight_mask_for_daynight_product(weights, data_a, data_b)
```

The `data_a` and `data_b` both have `.coords["bands"] = ["R"]`. This results in `mask` also having bands = ["R"]. This then results in `weights` later on acquiring the `bands = ["R"]` coordinate too. Then when we finally apply the mask the first (R) band has `.coords["bands"] = ["R"]` but the G and B bands don't have this coordinate (because it wasn't equal). Finally, when the base compositor class concatenates the individual R, G, and B bands together it errors out because it is told to concat on the "bands" dimension but not all of the inputs have that coordinate. I'll see if I can come up with a clean and obvious solution to this.

**Comment by djhoese** [comment]
@pnuu I ended up making more changes than I anticipated after adding and fixing some type annotations. Please review and merge if you're OK with everything.

**Comment by pnuu** [comment]
Thank you for explaining what really was happening! Also thanks for the type annotations, some day I need to start looking at them my self...

**Pull request merged**
