### PR TITLE
Set travis and appveyor numpy version back to 'stable'

### PR DESCRIPTION
**Pull request by djhoese**
The ci-helpers default for "stable" numpy version is 1.18 which is not available from conda-forge. This was causing problems in #988 but maybe now that I fixed the mitiff issue this will work (even if ci-helpers falls back to PyPI numpy).

 - [ ] Tests passed

### CODE REVIEW

**Comment by mraspaud** [comment]
@djhoese this is good to merge, right ?

**Comment by djhoese** [comment]
OSX is failing. I've restarted those environments.

**Comment by djhoese** [comment]
It seems like the failure is related to the pygrib, glymur, and pygac dependencies not being installed.

**Comment by djhoese** [comment]
Merged with master which already had travis on stable numpy and was passing. Now github missed the travis link so here is the latest build for this PR: https://travis-ci.org/github/pytroll/satpy/builds/666786469

**Comment by mraspaud** [comment]
Ok, good, this can be merged when it passes

**Pull request merged**
