### PR TITLE
Fix cira fire temperature and green snow

### LINKED ISSUE #1650: wrong gamma for red beam of cira_fire_temperature RGB
**Describe the bug**
According to documentation, which is referenced in the respective yaml files, the gamma value for the red beam (C07/NIR3.9) of cira_fire_temperature RGB shall be 0.4 and not 1.4.

```python
  cira_fire_temperature:
    standard_name: cira_fire_temperature
    reference: http://rammb.cira.colostate.edu/training/visit/quick_guides/Fire_Temperature_RGB.pdf
    operations:
      - name: stretch
        method: !!python/name:satpy.enhancements.stretch
        kwargs:
          stretch: crude
          min_stretch: [273, 0.0, 0.0]
          max_stretch: [333, 100.0, 75.0]
      - name: gamma
        method: !!python/name:satpy.enhancements.gamma
        kwargs:
          gamma: [**0.4**, 1, 1]
```

**Screenshots**
compare
correct RGB is to the left

**Environment Info:**
 - OS:[Linux
 - Satpy Version: 0.27.0

### PR DESCRIPTION
**Pull request by mraspaud**
Two composites had bugs. This PR fixes it.

 - [x] Closes #1650 
 - [ ] Tests added 
 - [ ] Fully documented

### CODE REVIEW

**Comment by mraspaud** [comment]
@djhoese @pnuu do you think we need tests for this?

**Comment by djhoese** [comment]
I don't think we have tests for things like this. This might be a good place for integration tests, especially considering @gerritholl's idea for a gallery of composites in #1527.

**Comment by mraspaud** [comment]
Good idea with the integration tests, but in another pr, right?

**Comment by djhoese** [comment]
Yes.

**Review by pnuu — APPROVED** [review]
LGTM

**Pull request merged**
