### PR TITLE
Add FCI L2 netCDF reader.

### PR DESCRIPTION
**Pull request by sjoro**
Add FCI L2 netCDF reader. Replaces PR #1073 and is based on a most recent `master`-branch.

 - [x] Tests added
 - [x] Tests passed
 - [x] Passes ``flake8 satpy`` 
 - [x] Fully documented

### CODE REVIEW

**Comment by mraspaud** [comment]
Two things I forgot: 
- What's the README.md ?
- Don't forget to add the reader to reader lists in index.rst

**Comment by sjoro** [comment]
README.md and index.srt sorted.

**Comment by sjoro** [comment]
Issue [#1222](https://github.com/pytroll/satpy/issues/1222) raised to remind about the TODO's in the code.

**Comment by mraspaud** [comment]
@sjoro the appveyor tests are failing because of some stupid windows permission issues. The workaround I've use before is this:
https://github.com/pytroll/satpy/blob/master/satpy/tests/reader_tests/test_viirs_compact.py#L2459-L2464

**Comment by mraspaud** [comment]
Anything you can do to make codebeat happier ?

**Comment by sjoro** [comment]
any ideas for appveyor fail?

**Comment by djhoese** [comment]
@sjoro It says it is unable to build non-mergeable pull request. Maybe try making this "Ready for review" and see if it starts up appveyor? I don't see anything about this PR in the appveyor history.

**Pull request merged**
