### PR TITLE
Calculate Solar zenith angles in DayNightCompositor if the dataset is not given

### PR DESCRIPTION
**Pull request by pnuu**
With this PR the Sun zenith angles are calculated from the day-time dataset info if the dataset is not available directly from the reader.

The default (in visir.py) is that all the drivers would supply the zenith angles. For the instruments for which the readers do not produce the zenith angles, they are calculated when creating the composite. As an example, the built-in ``natural_with_night_fog`` product has been modified according to this.

 - [x] Tests passed 
 - [x] Passes ``git diff origin/develop **/*py | flake8 --diff``

### CODE REVIEW

**Comment by mraspaud** [comment]
@pnuu could you add a test for checking that the angles would be computed ?

**Comment by pnuu** [comment]
Yes, I'll take a look at adding the test.

**Comment by pnuu** [comment]
Ok, added some tests. Not very thorough, but a start :-) The test data I created is being stretched, so the end-result isn't really intuitive.
Also fixed a case where data mask is `True` or `False`.

**Comment by pnuu** [comment]
This PR is using the obsolete `Dataset` class and is not xarray compatible. Also, the functionality is already present in the current `master` branch, so I'm closing the PR and deleting the feature branch. The only things not in `master` are the examples added to the instrument composite YAML configs, and the unittests for the non-xarray day-night compositor.

**Pull request closed without merging**
