### PR TITLE
Add platform_name and sensor in avhrr_aapp_l1b reader

### LINKED ISSUE #385: No platform_name and sensor in dataset metadata for avhrr_aapp_l1b reader
**Describe the bug**
The `avhrr_aapp_l1b` doesn't have `platform_name` and `sensor` in the dataset metadata.

**To Reproduce**

```python
from satpy import Scene
fname = "hrpt_noaa18_20180731_0934_67992.l1b"
glbl = Scene(reader='avhrr_aapp_l1b', filenames=[fname,])
glbl.load(['4'])
print(glbl['4'].attrs.get('platform_name', None))
print(glbl['4'].attrs.get('sensor', None))
```

**Expected behavior**
The above code should print
```python
NOAA-18
avhrr-3
```

**Actual results**
The above code prints
```python
None
None
```

**Environment Info:**
 - SatPy Version: current SatPy `master` branch

### PR DESCRIPTION
**Pull request by pnuu**
This PR adds `platform_name` (read from the data header) and `sensor` to the dataset metadata. AVHRR/2 is removed from `avhrr_aapp_l1b.yaml`, as AAPP documentation doesn't mention it at all.

 - [x] Closes #385
 - [ ] Tests added
 - [x] Tests passed
 - [ ] Passes ``git diff origin/master **/*py | flake8 --diff``

### CODE REVIEW

**Comment by adybbroe** [comment]
@pnuu Do you want to solve the units issue as well here?
```
> /home/a000680/usr/src/satpy/satpy/composites/__init__.py(504)_get_reflectance()
-> if (dataset.attrs['units'] == 'K' and
(Pdb) dataset.attrs
OrderedDict([('name', 'solar_zenith_angle'), ('sensor', 'avhrr-3'), ('resolution', 1050), ('platform_name', 'NOAA-19'), ('modifiers', ()), ('start_time', datetime.datetime(2017, 9, 18, 4, 7, 37, 498000)), ('end_time', datetime.datetime(2017, 9, 18, 4, 22, 59, 332000)), ('area', <pyresample.geometry.SwathDefinition object at 0x7f2c633ec8d0>), ('calibration', None), ('polarization', None), ('level', None), ('ancillary_variables', [])])
```

**Comment by djhoese** [comment]
@pnuu Should this be included in 0.9.1? Doesn't look like it needs 0.10?

**Comment by pnuu** [comment]
I'd include this ASAP to have pyspectral based composites to work for AVHRR.

**Comment by djhoese** [comment]
It isn't shorter: `if 'X' in dataset.attrs and dataset.attrs['X'] == 'K'`

**Pull request merged**
