### PR TITLE
Fix AAPP l1b reader for negative slope on channel 2

### PR DESCRIPTION
**Pull request by mraspaud**
This is a fix for https://github.com/ssec/polar2grid/issues/332

 - [ ] Closes ssec/polar2grid#332 
 - [x] Tests added 
 - [x] Fully documented

### CODE REVIEW

**Comment by mraspaud** [comment]
@djhoese did you test it with p2g?

**Comment by djhoese** [comment]
No. The current version of P2G has not been ported to use Satpy yet for this reader. It is planned, but not something that I can promise will be done any time soon. The last release of P2G had a reader based off of the old mpop reader I think. This PR fixes the generation of the image using just Satpy, right?

**Comment by mraspaud** [comment]
OK, so it doesn't close that p2g issue then...

**Comment by mraspaud** [comment]
Yes, just satpy

**Comment by djhoese** [comment]
Not directly, no. I've asked Kathy to test changing the `if` statement as you have here and we'll see if that fixes it in the old P2G. Then I think we can safely assume that this change (included in this PR) fixes the stuff in P2G (current and future).

**Comment by djhoese** [comment]
Kathy confirmed with me on slack that changing the `if` check fixed her Polar2Grid output.

**Comment by mraspaud** [comment]
Perfect, merging then

**Pull request merged**
