### PR TITLE
Rename readers to meet new reader naming scheme

### LINKED ISSUE #527: [SEP] Reader naming conventions
This SatPy Enhancement Proposal [SEP] is to finalize reader naming conventions for all readers provided by SatPy. This issue is set for v0.11 which I think will be the "break all the readers and rename them" release.

I propose the following reader naming convention and rules:

## Rules

1. Readers should be named following the scheme:

```
[<file format>_]<sensor/algorithm>[_<processing/calibration level>[_<detailed suffix>]]
```

2. Reader names should be all lowercase regardless of acronyms contained with fields separated by underscores where possible. Hyphens as inter-field separators will be considered on a case by case basis.
3. Abbreviations should follow community standards:

* NetCDF -> `nc`,
* HDF 4 ->`hdf`
* HDF 5 -> `h5`
* Level 1B -> `l1b`
* Level 2 -> `l2`
* Sensor Data Record -> `sdr`
* Environmental Data Record -> `edr`

4. All naming scheme fields are optional except `sensor/algorithm`, but at least one of the optional fields should be provided.
5. Future product expectations and community usage (colloquialisms) should also be considered in what naming fields are excluded.

    For example, the ABI L1B products stored in NetCDF4 files are the official NOAA product and as such shouldn't be provided in any other "official" format in the future by that name. This means that the reader can be called "abi_l1b" even though "nc_abi_l1b" would be a more detailed name. Other formats that provide similar data for ABI are known by and referred to by other names such as the "CMIP" format. In this case the reader could be called "cmip_abi_l1b" or "cmip_abi_l2".

6. If a reader's format becomes obsolete, due to changes by the operational processing or satellite mission's organizers, and the new reader's name conflicts with the existing reader, the old reader's name should be prefixed with `legacy_`. The main point being that reader's of new formats are not `new_` readers, but rather just "the reader" for that format.

## Personal Opinion and Complications

If this naming scheme was only for computer/internal use then I'd say things like `nc_abi_l1b` would be preferred. Since these names need to be easily identifiable I think `abi_l1b` is more logical as a user friendly. I'm sure allowing the flexibility discussed in point 5 above will cause issues in the future, but I'm hoping it won't.

Additionally, we are going to have a lot of headaches where files are describes by the "scheme" they adopt and not by the *format* that they are. For example "SCMI" files are NetCDF4 files that follow CF standards (sort of). The name "SCMI" stands for Sectorized Cloud Moisture Imagery which isn't even what it is used for anymore. So does the reader that reads ABI SCMI data call itself the `scmi_abi` reader or the nc_abi reader or some combination of "nc", "scmi", "l1b", "abi", blah blah blah.

## Examples

1. `abi_l1b`
2. `hrit_ahi`
3. `hsd_ahi`
4. `viirs_sdr`
5. `viirs_edr_flood`
    The VIIRS EDR Flood Product
6. `geocat`
    A reader for the output from the GeoCAT software. Could be one or more sensors and one or more processing levels.
7. `nc_goes`
    Pre-GOES-16 satellite format

### PR DESCRIPTION
**Pull request by djhoese**
For details on the discussion that lead to the changes in this PR see #527. The bottom line is that the names of readers in SatPy are fairly inconsistent. This PR is an attempt to finalize the naming convention and rename existing readers to match this scheme.

## Readers Changed

* `avhrr_aapp_l1b` -> `avhrr_l1b_aapp`
* `avhrr_eps_l1b` -> `avhrr_l1b_eps`
* `avhrr_hrpt_l1b` -> `avhrr_l1b_hrpt`
* `fci_fdhsi` -> `fci_l1c_fdhsi`
* `gac_lac_l1` -> `avhrr_l1b_gaclac`
* `ghrsst_osisaf` -> `ghrsst_l3c_sst`
* `hdf4_caliopv3` -> `caliop_l2_cloud`
* `hdfeos_l1b` -> `modis_l1b`
* `hrit_electrol` -> `electrol_hrit`
* `hrit_goes` -> `goes-imager_hrit`
* `hrit_jma` -> `ahi_hrit`
* `hrit_msg` -> `seviri_l1b_hrit`
* `native_msg` -> `seviri_l1b_native`
* `nc_goes` -> `goes-imager_nc`
* `nc_nwcsaf_msg` -> `nwcsaf-geo`
* `nc_nwcsaf_pps` -> `nwcsaf-pps_nc`
* `nc_olci_l1b` -> `olci_l1b`
* `nc_olci_l2` -> `olci_l2`
* `nc_seviri_l1b` -> `seviri_l1b_nc`
* `nc_slstr` -> `slstr_l1b`
* `safe_msi` -> `msi_safe`
* `safe_sar_c` -> `sar-c_safe`
* `scmi_abi_l1b` -> `abi_l1b_scmi`

## Remaining/Undecided

* ~~`avhrr_aapp_l1b`, `avhrr_eps_l1b`, `avhrr_hrpt_l1b`: Aren't the middle part of these names technically the processing software? Or could they maybe be considered the "file format"?~~
* ~~`gac_lac_l1`: This looks like a AVHRR reader but I don't know what "gac_lac" is.~~
* ~~`ghrsst_osisaf`: It is originally just for AVHRR, but now supports AVHRR and VIIRS. Also OSISAF is technically the organization and not the processing software, right? Would `osisaf-ghrsst_l2_sst` be too annoying?~~
* ~~`grib`, technically this should probably be `generic_grib` but `grib` is already a generic format. If this stays `grib` then should `generic_image` become `image`?~~ I'm considering this a non-issue right now
* ~~`nc_nwcsaf_msg`: Right now this only support seviri but @adybbroe said that the processing software actually supports other geostationary satellites and is now called NWCSAF Geo (or something). So possible names are: `nwcsafgeo` or `nwcsaf_geo` or `nwcsaf-geo` or `nwcsaf-geo_nc`.~~
* ~~`nc_nwcsaf_pps`: Same as above. PPS is Polar Platform System~~
* ~~`nc_seviri_l1b`: Is this the "official" product for level 1b? If so then this could be called `seviri_l1b`. If not, then `seviri_l1b_nc`.~~

 - [x] Closes #527 
 - [x] Tests added 
 - [x] Tests passed 
 - [x] Passes ``git diff origin/master -- "*py" | flake8 --diff`` 
 - [x] Fully documented

### CODE REVIEW

**Comment by djhoese** [comment]
As mentioned on slack, @sjoro said that `nc_seviri_l1b` should be renamed to `seviri_l1b_nc` since the NetCDF product is not the "official" product (HRIT is, followed by native).

**Comment by sjoro** [comment]
please consider changing `seviri_native` and `seviri_hrit` to `seviri_l1b_native` and `seviri_l1b_hrit`. though, i have no strong opinion on this. just thought it might help users who are not familiar with the data.

**Comment by djhoese** [comment]
@adybbroe I renamed `nc_nwcsaf_msg/pps` to `nwcgeo/nwcpps` based on the pages here:

* http://www.nwcsaf.org/3
* http://www.nwcsaf.org/web/guest/16

Which use those names for the products. I didn't here any opinions on better names for this but would also be ok with something like `nwcsaf-geo`. Maybe?

Only reader remaining now is `ghrsst_osisaf`. I can't find any files online that match the file patterns for this reader so I don't know what the differences are between this reader's file and others and what a good name would be.

@sjoro @ColinDuff @mraspaud @pnuu Please review the names I've changed so far. I'm ok merging this as is and leaving `ghrsst_osisaf` if needed.

**Comment by mraspaud** [comment]
We probably have to update a bunch of pytroll-examples notebooks in conjunction with this, right ?

**Comment by mraspaud** [comment]
> `ghrsst_osisaf`: It is originally just for AVHRR, but now supports AVHRR and VIIRS. Also OSISAF is technically the organization and not the processing software, right? Would `osisaf-ghrsst_l2_sst` be too annoying?

How about `osisaf_l2_ghrsst` (`ghrsst` is a product I think)

**Comment by mraspaud** [comment]
Also, why `seviri_l1b_hrit` vs `ahi_hrit` ?
As for the NWCSAF products, I would rather have `nwcsaf-geo` and `nwcsaf-pps_nc` (there is a h5 version for older versions of the PPS software)

**Comment by ColinDuff** [comment]
seviri name changes look good to me

**Comment by djhoese** [comment]
@mraspaud:

1. Updating examples: Yes, but since this PR still allows for the old names to be used we should be fine from the immediate "I tried this example and it didn't work".
2. For ghrsst_osisaf, [this page](https://data.nodc.noaa.gov/cgi-bin/iso?id=gov.noaa.nodc:GHRSST-AVHRR_SST_NOAA19_NAR-OSISAF-L3C) suggests level 3C. I took "osisaf" to be the producing/processing organization but my google searches made it seem like their format may be custom compared to others who produce the same product. Additionally the way it is used in the pages I've found is that "ghrsst" is the group that produces (or at least approved of) the algorithm. Maybe `ghrsst_l2` or `ghrsst_l3c` then?
3. Electro-L: Yes you are right for that specific instrument. When I was looking for it on OSCAR I found that every other platform uses "Electro-L N<N>" for the name. See:

 * https://www.wmo-sat.info/oscar/instruments/view/324
 * https://www.wmo-sat.info/oscar/satellites/view/73
 * https://www.wmo-sat.info/oscar/satellites/view/474
 * https://www.wmo-sat.info/oscar/satellites/view/613

4. For `seviri_l1b_hrit`, the `l1b` was added to be consistent with the other SEVIRI L1B reader's after talking with @sjoro. The `ahi_hrit`, as far as I know, is the only HRIT product released as `hrit` for AHI. I'd prefer not to add the `l1b` (is that even correct?) for AHI, but I'd be ok with removing `l1b` for the seviri hrit reader. I think I most prefer the way it is currently, but can be convinced otherwise.
5. I'm ok with the nwcsaf-geo. For `nwcsaf-pps`, do you ever see us supporting the older format? Maybe it would be "cleaner" to have `nwcsaf-pps_h5` reader if it is needed in the future?

**Comment by djhoese** [comment]
@mraspaud Note I/we also need to update the directory names for the behavior tests since they currently use `hrit_msg` and other similar readers.

**Comment by mraspaud** [comment]
1. Very good
2. Could we just omit the level while we wait for @adybbroe to give his opinion on that ?
3. Ok
4. Ok, we can leave it as it is.
5. TBH, I'm generally not confortable with leaving the formats out, for the reason that what might be the regular format for some users might be different for others. In this particular case, the pps v2014 software can produce both nc and h5 files, both of which are officially supported. We chose to support nc, because h5 is going to be dropped in the next version, but h5 has been the historical format. So to avoid confusion I'd like to append `_nc`. The geo counterpart doesn't have this problem since the software name changed from `nwcsaf_msg` to `nwcsaf_geo`, but as per my preliminary comment on this point, I would prefer to have `_nc` appended. Yeah, you can call me pedantic :)

**Comment by djhoese** [comment]
2. So just `ghrsst`?
5. I'm ok with adding the format. I think this is easily a 50/50 decision for me on this specific reader. I think most users coming to satpy who want to read the data are probably using the new format. If they are using the old format I would assume they already have non-satpy solutions for what they want to do. Let me know (here or slack) if you are ok with me not changing it. Otherwise, I'll make the changes tomorrow morning probably.

**Comment by djhoese** [comment]
But isn't `ghrsst` the algorithm and the product? `osisaf` is the "processing center" if I'm understanding things, which our current naming scheme doesn't handle (nor do I want it to). For the naming scheme to use an "extra detail" field like "product" it has to include the level like `viirs_edr_flood`. I think if we are being strict about this naming, which we don't need to be, I'm fine with this being an exception to the rule, then I think it would be `osisaf-ghrsst`.

**Comment by mraspaud** [comment]
ok, `ghrsst` it is.

**Pull request merged**
