### PR TITLE
Add an initial section on writing tests

### PR DESCRIPTION
**Pull request by pnuu**
This PR adds an initial documentation page on writing unit tests. At this stage, only pytest fixtures are mentioned, triggered by the discussion on https://github.com/pytroll/satpy/pull/2316/ and further in Slack and the monthly contributor meeting.

If there is support for the `NOTE` section, or comments on how to adapt it, I'll add it to at least some of the tests using built-in fixtures in this PR.

```
# NOTE:
# The following fixtures are not defined in this file, but are used and injected by Pytest:
# - tmp_path
# - fixture_defined_in_conftest.py
```

### CODE REVIEW

**Review by mraspaud — APPROVED** [review]
LGTM, I'm very happy with that!

**Review by djhoese — APPROVED** [review]
This looks good to me. I think this is a good balance. I kind of wish there was more content in the writing tests documentation, but this is a good starting point.

**Comment by pnuu** [comment]
Thanks! I'll start going through the tests and add the note at least to some of them. Depends how many I find...

**Comment by pnuu** [comment]
I agree that the Writing tests section is way too short, but that'll require input from someone with more insights than I have.

I've now added the note on all the test modules I found using any of the builtin or `conftest.py` fixtures. Might have missed some, but at least most of them should be there.

**Comment by pnuu** [comment]
Rebase from main to bring in the fix for the RtD build.

**Comment by djhoese** [comment]
Hm you somehow got appveyor back. Nice job lol

**Comment by pnuu** [comment]
Wait, what? :joy:

**Comment by pnuu** [comment]
Now that I resolved the conflict in VIIRS L2 tests Appveyor went away again...

**Review by djhoese — APPROVED** [review]

**Pull request merged**
