### PR TITLE
Add github workflow

### PR DESCRIPTION
**Pull request by mraspaud**
As an alternative to travis

 - [ ] Closes #xxxx 
 - [ ] Tests added 
 - [ ] Passes ``flake8 satpy`` 
 - [ ] Fully documented 
 - [ ] Add your name to `AUTHORS.md` if not there already

### CODE REVIEW

**Review by djhoese — APPROVED** [review]

**Comment by djhoese** [comment]
I guess we just need it to show up as a check now in PRs.

**Comment by mraspaud** [comment]
That should happen automatically once we merge this PR.

Should I remove the travis builds then?

**Comment by gerritholl** [comment]
For motivation and context see https://app.slack.com/client/T06GJF21Y/C06GJFRN0/details and https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing

**Comment by mraspaud** [comment]
I'm leaving travis-ci.yaml for now, just comment out the deploying and coverage reporting.

**Pull request merged**
