### PR TITLE
L2reader

### PR DESCRIPTION
**Pull request by jhbravo**
- [ ] Closes #xxxx 
 - [ ] Tests added 
 - [ ] Tests passed 
 - [ ] Passes ``git diff origin/master -- "*py" | flake8 --diff`` 
 - [ ] Fully documented

### CODE REVIEW

**Comment by jhbravo** [comment]
hi @djhoese 
ok, i can split this one pull request in three
one for cmip, other for derived products and one last for EPIC.
i will have in count the convention for naming readers
thank you

**Comment by djhoese** [comment]
Does this PR include the changes from #429? I think, based on how I'm feeling today, that once I finish up some projects at my own work I will sweep through your pull requests and re-organize/re-name anything that I see being needed. If you want to help with this then it may be best for you to join slack for quicker conversations. Otherwise, I can just do it myself. These new readers probably won't be an issue as long as they are xarray/dask friendly, but the ABI composites may need cleanup with some recent changes that @pnuu has made.

**Comment by jhbravo** [comment]
> Does this PR include the changes from #429? I think, based on how I'm feeling today, that once I finish up some projects at my own work I will sweep through your pull requests and re-organize/re-name anything that I see being needed. If you want to help with this then it may be best for you to join slack for quicker conversations. Otherwise, I can just do it myself. These new readers probably won't be an issue as long as they are xarray/dask friendly, but the ABI composites may need cleanup with some recent changes that @pnuu has made.

**Comment by jhbravo** [comment]
Yes, I will try to join slack in a short time.
I think that when I hide the branch, I made it with the changes I had in # 429, correct that so you can be independent.
and about the ABI compositions, I remain aware of what needs to be modified

**Pull request closed without merging**
