### PR TITLE
Drop support for Python 3.8 and add 3.11 tests

### PR DESCRIPTION
**Pull request by gerritholl**
Drop support for Python 3.8 and add tests for Python 3.11.  Remove a note that Python 2 support was dropped as this information is no longer relevant except for historians.

### CODE REVIEW

**Review by pnuu — APPROVED** [review]
LGTM

**Comment by gerritholl** [comment]
I don't know if the failing unstable tests are related to Python 3.11.

**Comment by gerritholl** [comment]
But does Python 3.10 or Python 3.11 make a difference for any of the unstable test failures?

**Comment by djhoese** [comment]
No. I'm failing locally with Python 3.9 and unstable dependencies installed.

**Comment by djhoese** [comment]
And the NUCAPS fixes: https://github.com/pytroll/satpy/pull/2417

**Comment by djhoese** [comment]
So from what I can see something about the 3.11 experimental update is now causing 3 holoviews/geoviews failures instead of just 1 from my nucaps PR. I don't think that's necessarily an issue since the error messages are all referring to the same thing, but I'm just kind of surprised at the change. Feel free to merge this @gerritholl unless you want approval from someone else.

**Pull request merged**
