### PR TITLE
[WIP] Update convert_to_ninjotiff.py utility script for xarray

### PR DESCRIPTION
**Pull request by loreclem**
get_area_def is now imported from pyresample instead of mpop.

### CODE REVIEW

**Comment by pnuu** [comment]
It seems there were some preliminary work done here to make `generic_image` reader to work with xarray and dask. I didn't notice that when I started my own branch for it, and then just wanted to complete the work to learn more how things work.

@loreclem could you check the PR I made (#374) if it would work for you in the NinjoTIFF converter?

**Comment by loreclem** [comment]
@pnuu I did some work on the `generic_image` reader in June, but I got stuck when trying to write to NinJo-Tiff (the writer was not compatible with xarray yet). I'm happy to look at your code, using `rasterio` seems much better than my implementation.
I'm traveling right now, I'll try to give you a feedback asap.

**Comment by loreclem** [comment]
@pnuu your implementation of the `generic_image` reader is superior to mine. I would suggest that we keep your version and discard this PR. If need be, I'll adapt the `convert_to_ninjotiff.py` after your reader has been merged.
The `ninjotiff` writer was not compatible with xarray and dask when I tested it in June. I haven't worked on it myself since then, so I don't know what is the status... maybe @mraspaud ?

**Comment by mraspaud** [comment]
nothing new from my side, so work is left to be done

**Comment by loreclem** [comment]
@mraspaud maybe something for me at the November workshop. Unfortunately I don't think I'll be able to work on it before...

**Comment by djhoese** [comment]
FYI @loreclem the generic_image updates that @pnuu worked on have been merged to master. If you or anyone else wants to pick up this PR to update the helper script it would be much appreciated. However, iirc this requires updates to the NinJo writer which @goodsonr and @mraspaud were working on last time I checked.

**Comment by djhoese** [comment]
It looks like us changing the master branch to main allowed github to detect that your fork doesn't exist anymore. Let me know if that is not true and we can try to find a way to get this PR back. As of right now, I'm unable to reopen this.

**Pull request closed without merging**
