### PR TITLE
Update the HRPT reader to latest satpy api

### LINKED ISSUE #175: Cannot read AVHRR in HRPT format (geoloc dtype error)
satpy 0.8.1 pyorbital 1.1.1

Trying to load AVHRR in HRPT format

```
satpy/readers/hrpt.py calls
        s_times = sgeom.times(
            self.times[:, np.newaxis]).ravel()
pyorbital/geoloc.py calls
        tds = [timedelta(seconds=i) for i in self._times]
        return np.array(tds) + start_of_scan

The last line gives the error:
TypeError: ufunc add cannot use operands with types dtype('O') and dtype('<M8[ms]')

  File "/packages/pytroll/bin/satpy_to_png.py", line 229, in process_list_of_filenames
    global_scene.load([band_name])
  File "/packages/pytroll/local/lib/python2.7/site-packages/satpy/scene.py", line 564, in load
    self.read(**kwargs)
  File "/packages/pytroll/local/lib/python2.7/site-packages/satpy/scene.py", line 505, in read
    return self.read_datasets(nodes, **kwargs)
  File "/packages/pytroll/local/lib/python2.7/site-packages/satpy/scene.py", line 378, in read_datasets
    new_datasets = reader_instance.load(ds_ids, **kwargs)
  File "/packages/pytroll/local/lib/python2.7/site-packages/satpy/readers/yaml_reader.py", line 875, in load
    ds = self._load_dataset_with_area(dsid, coords)
  File "/packages/pytroll/local/lib/python2.7/site-packages/satpy/readers/yaml_reader.py", line 853, in _load_dataset_with_area
    ds = self._load_dataset_data(file_handlers, dsid, **slice_kwargs)
  File "/packages/pytroll/local/lib/python2.7/site-packages/satpy/readers/yaml_reader.py", line 713, in _load_dataset_data
    proj = self._load_entire_dataset(dsid, ds_info, file_handlers)
  File "/packages/pytroll/local/lib/python2.7/site-packages/satpy/readers/yaml_reader.py", line 631, in _load_entire_dataset
    projectable = fh.get_dataset(dsid, ds_info)
  File "/packages/pytroll/local/lib/python2.7/site-packages/satpy/readers/hrpt.py", line 149, in get_dataset
    lons, lats = self.get_lonlats()
  File "/packages/pytroll/local/lib/python2.7/site-packages/satpy/readers/hrpt.py", line 236, in get_lonlats
    self.times[:, np.newaxis]).ravel()
  File "/packages/pytroll/local/lib/python2.7/site-packages/pyorbital/geoloc.py", line 128, in times
    return np.array(tds) + start_of_scan
TypeError: ufunc add cannot use operands with types dtype('O') and dtype('<M8[ms]')

### PR DESCRIPTION
**Pull request by mraspaud**
This PR adapts the HRPT reader to dask, xarray and latest pygac 

 - [x] Closes #175  
 - [x] Tests added 
 - [x] Passes ``flake8 satpy`` 
 - [x] Fully documented

### CODE REVIEW

**Review by howff — CHANGES_REQUESTED** [review]
Thanks very much for the quick PR!
But I think in hrpt.py get_dataset is treating key as a dict but it's a tuple so instead of key['name'] you need to use key.name (and same for key.calibration).

**Comment by mraspaud** [comment]
@howff the key is in principle an instance of a DataID. The recommended way to access its fields now is with `['name']`.

**Comment by howff** [comment]
The tuple problem was probably me patching hrpt.py into a version of satpy older than master. But when I use this branch I can confirm that the data loads ok and the built-in composites also work, so thank you very much :)

**Comment by mraspaud** [comment]
You are very welcome, it was high time to update this reader! So thank you for poking us.

**Comment by mraspaud** [comment]
@howff I think I'm happy with this PR now. Any further comments?

**Comment by TAlonglong** [comment]
Do you need https://github.com/pytroll/python-geotiepoints for that?

**Comment by gerritholl** [comment]
Same problem after installing the latest `pyorbital` and `pygac`:

```
[DEBUG: 2021-02-05 16:36:41 : satpy.readers.yaml_reader] Reading ('/home/gholl/checkouts/satpy/satpy/etc/readers/avhrr_l1b_hrpt.yaml',)
[DEBUG: 2021-02-05 16:36:41 : satpy.readers.yaml_reader] Assigning to avhrr_l1b_hrpt: ['/media/nas/x21308/scratch/20210205141010_NOAA_19.hmf']
[DEBUG: 2021-02-05 16:36:41 : satpy.composites.config_loader] Looking for composites config file avhrr-3.yaml
[DEBUG: 2021-02-05 16:36:41 : satpy.composites.config_loader] Looking for composites config file visir.yaml
[DEBUG: 2021-02-05 16:36:41 : satpy.composites.config_loader] Looking for composites config file avhrr-2.yaml
[DEBUG: 2021-02-05 16:36:41 : satpy.composites.config_loader] No composite config found called avhrr-2.yaml
[DEBUG: 2021-02-05 16:36:41 : satpy.readers.yaml_reader] No coordinates found for DataID(name='longitude', resolution=1050, modifiers=())
[WARNING: 2021-02-05 16:36:41 : satpy.readers.yaml_reader] Failed to load DataID(name='longitude', resolution=1050, modifiers=()) from <HRPTFile: '/media/nas/x21308/scratch/20210205141010_NOAA_19.hmf'>
Traceback (most recent call last):
  File "/home/gholl/checkouts/satpy/satpy/readers/yaml_reader.py", line 687, in _load_dataset
    projectable = fh.get_dataset(dsid, ds_info)
  File "/home/gholl/checkouts/satpy/satpy/readers/hrpt.py", line 161, in get_dataset
    attrs['platform_name'] = self.platform_name
  File "/data/gholl/miniconda3/envs/py38b/lib/python3.8/functools.py", line 967, in __get__
    val = self.func(instance)
  File "/home/gholl/checkouts/satpy/satpy/readers/hrpt.py", line 156, in platform_name
    return spacecrafts[(self._data["id"]["id"][0] >> 3) & 15]
KeyError: 2
[ERROR: 2021-02-05 16:36:41 : satpy.readers.yaml_reader] Could not load dataset 'DataID(name='longitude', resolution=1050, modifiers=())': "Could not load DataID(name='longitude', resolution=1050, modifiers=()) from any provided files"
Traceback (most recent call last):
  File "/home/gholl/checkouts/satpy/satpy/readers/yaml_reader.py", line 829, in _load_dataset_with_area
    ds = self._load_dataset_data(file_handlers, dsid, **kwargs)
  File "/home/gholl/checkouts/satpy/satpy/readers/yaml_reader.py", line 711, in _load_dataset_data
    proj = self._load_dataset(dsid, ds_info, file_handlers, **kwargs)
  File "/home/gholl/checkouts/satpy/satpy/readers/yaml_reader.py", line 696, in _load_dataset
    raise KeyError(
KeyError: "Could not load DataID(name='longitude', resolution=1050, modifiers=()) from any provided files"
[DEBUG: 2021-02-05 16:36:41 : satpy.readers.yaml_reader] No coordinates found for DataID(name='latitude', resolution=1050, modifiers=())
[WARNING: 2021-02-05 16:36:41 : satpy.readers.yaml_reader] Failed to load DataID(name='latitude', resolution=1050, modifiers=()) from <HRPTFile: '/media/nas/x21308/scratch/20210205141010_NOAA_19.hmf'>
Traceback (most recent call last):
  File "/home/gholl/checkouts/satpy/satpy/readers/yaml_reader.py", line 687, in _load_dataset
    projectable = fh.get_dataset(dsid, ds_info)
  File "/home/gholl/checkouts/satpy/satpy/readers/hrpt.py", line 161, in get_dataset
    attrs['platform_name'] = self.platform_name
  File "/data/gholl/miniconda3/envs/py38b/lib/python3.8/functools.py", line 967, in __get__
    val = self.func(instance)
  File "/home/gholl/checkouts/satpy/satpy/readers/hrpt.py", line 156, in platform_name
    return spacecrafts[(self._data["id"]["id"][0] >> 3) & 15]
KeyError: 2
[ERROR: 2021-02-05 16:36:41 : satpy.readers.yaml_reader] Could not load dataset 'DataID(name='latitude', resolution=1050, modifiers=())': "Could not load DataID(name='latitude', resolution=1050, modifiers=()) from any provided files"
Traceback (most recent call last):
  File "/home/gholl/checkouts/satpy/satpy/readers/yaml_reader.py", line 829, in _load_dataset_with_area
    ds = self._load_dataset_data(file_handlers, dsid, **kwargs)
  File "/home/gholl/checkouts/satpy/satpy/readers/yaml_reader.py", line 711, in _load_dataset_data
    proj = self._load_dataset(dsid, ds_info, file_handlers, **kwargs)
  File "/home/gholl/checkouts/satpy/satpy/readers/yaml_reader.py", line 696, in _load_dataset
    raise KeyError(
KeyError: "Could not load DataID(name='latitude', resolution=1050, modifiers=()) from any provided files"
[WARNING: 2021-02-05 16:36:41 : satpy.readers.yaml_reader] Failed to load coordinates for 'DataID(name='4', wavelength=WavelengthRange(min=10.3, central=10.8, max=11.3, unit='µm'), resolution=1050, calibration=<calibration.brightness_temperature>, modifiers=())'
[WARNING: 2021-02-05 16:36:41 : satpy.readers.yaml_reader] Failed to load DataID(name='4', wavelength=WavelengthRange(min=10.3, central=10.8, max=11.3, unit='µm'), resolution=1050, calibration=<calibration.brightness_temperature>, modifiers=()) from <HRPTFile: '/media/nas/x21308/scratch/20210205141010_NOAA_19.hmf'>
Traceback (most recent call last):
  File "/home/gholl/checkouts/satpy/satpy/readers/yaml_reader.py", line 687, in _load_dataset
    projectable = fh.get_dataset(dsid, ds_info)
  File "/home/gholl/checkouts/satpy/satpy/readers/hrpt.py", line 161, in get_dataset
    attrs['platform_name'] = self.platform_name
  File "/data/gholl/miniconda3/envs/py38b/lib/python3.8/functools.py", line 967, in __get__
    val = self.func(instance)
  File "/home/gholl/checkouts/satpy/satpy/readers/hrpt.py", line 156, in platform_name
    return spacecrafts[(self._data["id"]["id"][0] >> 3) & 15]
KeyError: 2
[ERROR: 2021-02-05 16:36:41 : satpy.readers.yaml_reader] Could not load dataset 'DataID(name='4', wavelength=WavelengthRange(min=10.3, central=10.8, max=11.3, unit='µm'), resolution=1050, calibration=<calibration.brightness_temperature>, modifiers=())': "Could not load DataID(name='4', wavelength=WavelengthRange(min=10.3, central=10.8, max=11.3, unit='µm'), resolution=1050, calibration=<calibration.brightness_temperature>, modifiers=()) from any provided files"
Traceback (most recent call last):
  File "/home/gholl/checkouts/satpy/satpy/readers/yaml_reader.py", line 829, in _load_dataset_with_area
    ds = self._load_dataset_data(file_handlers, dsid, **kwargs)
  File "/home/gholl/checkouts/satpy/satpy/readers/yaml_reader.py", line 711, in _load_dataset_data
    proj = self._load_dataset(dsid, ds_info, file_handlers, **kwargs)
  File "/home/gholl/checkouts/satpy/satpy/readers/yaml_reader.py", line 696, in _load_dataset
    raise KeyError(
KeyError: "Could not load DataID(name='4', wavelength=WavelengthRange(min=10.3, central=10.8, max=11.3, unit='µm'), resolution=1050, calibration=<calibration.brightness_temperature>, modifiers=()) from any provided files"
[WARNING: 2021-02-05 16:36:41 : satpy.scene] The following datasets were not created and may require resampling to be generated: DataID(name='4', wavelength=WavelengthRange(min=10.3, central=10.8, max=11.3, unit='µm'), resolution=1050, calibration=<calibration.brightness_temperature>, modifiers=())
Traceback (most recent call last):
  File "test-hrpt.py", line 7, in <module>
    ls.save_datasets(filename=str(plotdir() / "{start_time:%Y%m%d%H%M}-{platform_name:s}-{name:s}.tif"))
  File "/home/gholl/checkouts/satpy/satpy/scene.py", line 1001, in save_datasets
    raise RuntimeError("None of the requested datasets have been "
RuntimeError: None of the requested datasets have been generated or could not be loaded. Requested composite inputs may need to have matching dimensions (eg. through resampling).
```

from `conda list`:

```
pygac                     1.4.0                    pypi_0    pypi
pyorbital                 1.6.0+11.gf1e50fc          pypi_0    pypi
satpy                     0.25.2.dev50+g905197a3           dev_0    <develop>
```

**Comment by mraspaud** [comment]
@TAlonglong yes, and pyorbital and pygac

**Comment by mraspaud** [comment]
@gerritholl do you have python-geotiepoints installed?

**Comment by gerritholl** [comment]
It was probably a corrupted file.  With other files I do get an image, but many lines are misplaced:

`20210202124445_NOAA_18.hmf`:

202102021244-NOAA 18-4

`20210205041432_NOAA_19.hmf`:

202102050414-NOAA 19-4

`20210205091618_NOAA_19.hmf`:

202102050916-NOAA 19-4

I don't remember having seen this before.  Maybe AAPP has some error checking to remove those lines?

**Comment by mraspaud** [comment]
@gerritholl fun! I guess some consistancy check is in order...

**Comment by gerritholl** [comment]
Both `20210205091618_NOAA_19.hmf` files, projected on `eurol`, channel 4 without any other corrections.

With the `avhrr_l1b_aapp` reader pre-processed by AAPP:

with-aapp

With the `avhrr_l1b_hrpt` reader, no processing by AAPP:

without-aapp

**Comment by howff** [comment]
Some misplaced scanlines is to be expected if the timestamps have been corrupted due to noisy data.
The KeyError is possibly also the same cause, if the spacecraft id in the data has been corrupted by a bit flip.
Adding a filter for this is probably something I could contribute but it's not a bug in satpy.

**Comment by mraspaud** [comment]
@howff, yes, corrupted timestamps are probably the issue. I was thinking of trying to fit the timestamps to a line to correct the outliers, but how would you do it?

**Comment by gerritholl** [comment]
I agree that it's not a bug in Satpy, rather a missing feature — but as long as the data quality reading directly is worse than when pre-processing it with AAPP, users are going to keep AAPP in their pipelines despite the additional overhead.

**Comment by gerritholl** [comment]
Doesn't pygac have a lot of experience in filtering the dozens of things that can go wrong with data?  Could that help here?  There's already a pygac dependency anyway...

**Comment by mraspaud** [comment]
@gerritholl indeed: https://github.com/pytroll/pygac/blob/c86b67ed6f3b76b27cdcfd0f352b6b22bba7fe1a/pygac/reader.py#L757

**Comment by mraspaud** [comment]
ah no that won't work as HRPT doesn't have line numbers

**Comment by howff** [comment]
I would be happy to have this PR merged, to get the new API working, and leave the handling of dirty data to a different PR.

**Comment by mraspaud** [comment]
ok, great, I will merge this one then. @howff do you want to take a shot at that new PR for filter or fixing erroneous timestamps?

**Pull request merged**
