### PR TITLE
Remove the time_bnds

### LINKED ISSUE #1242: Dimension name of time in time_bounds is duplicated with the time dimension name of variable
**Describe the bug**
This issue happens when using `save_datasets` with scene blended by time.

**To Reproduce**

```python
from glob import glob
from satpy import Scene, MultiScene
from satpy.multiscene import timeseries

filenames = glob('../data/himawari/**/HS_H08_20190725_05*_B13_*.DAT.bz2', recursive=True)
mscn = MultiScene.from_files(filenames, reader="ahi_hsd")
mscn.load(['B13'])
blended_scene = mscn.blend(blend_function=timeseries)
blended_scene.save_datasets(filename='H8_B13_20190725.nc')
```

**Expected behavior**
New name for time dimension of bounds.

**Actual results**
```
[INFO: 2020-06-25 19:21:48 : satpy.writers.cf_writer] Saving datasets to NetCDF4/CF.
Traceback (most recent call last):
  File "/home/xin/Documents/Github/tobac-tutorials/themes/tobac_v1/Example_OLR_Tracking_satellite/read_h8.py", line 14, in <module>
    blended_scene.save_datasets(filename='H8_B13_20190725.nc')
  File "/home/xin/Documents/Github/satpy_xin/satpy/scene.py", line 1361, in save_datasets
    return writer.save_datasets(datasets, compute=compute, **save_kwargs)
  File "/home/xin/Documents/Github/satpy_xin/satpy/writers/cf_writer.py", line 637, in save_datasets
    end_times)
  File "/home/xin/Software/miniconda3/envs/s5p/lib/python3.7/site-packages/xarray/core/dataset.py", line 1275, in __setitem__
    self.update({key: value})
  File "/home/xin/Software/miniconda3/envs/s5p/lib/python3.7/site-packages/xarray/core/dataset.py", line 3576, in update
    merge_result = dataset_update_method(self, other)
  File "/home/xin/Software/miniconda3/envs/s5p/lib/python3.7/site-packages/xarray/core/merge.py", line 864, in dataset_update_method
    return merge_core([dataset, other], priority_arg=1, indexes=dataset.indexes)
  File "/home/xin/Software/miniconda3/envs/s5p/lib/python3.7/site-packages/xarray/core/merge.py", line 550, in merge_core
    coerced, join=join, copy=False, indexes=indexes, fill_value=fill_value
  File "/home/xin/Software/miniconda3/envs/s5p/lib/python3.7/site-packages/xarray/core/alignment.py", line 409, in deep_align
    fill_value=fill_value,
  File "/home/xin/Software/miniconda3/envs/s5p/lib/python3.7/site-packages/xarray/core/alignment.py", line 317, in align
    % (dim, unlabeled_sizes, labeled_size)
ValueError: arguments without labels along dimension 'time' cannot be aligned because they have different dimension size(s) {1} than the size of the aligned dimension labels: 6
```

**Environment Info:**
 - OS: Linux
 - Satpy Version: 0.22.0

**Additional context**
Temporary solution:
Rename the `time` dimension to `bnds_time` in [`make_time_bounds`](https://github.com/pytroll/satpy/blob/4b92a3cfb828d3140e162a19924e13662f43fe5a/satpy/writers/cf_writer.py#L214):

```
def make_time_bounds(start_times, end_times):
    """Create time bounds for the current *dataarray*."""
    start_time = min(start_time for start_time in start_times
                     if start_time is not None)
    end_time = min(end_time for end_time in end_times
                   if end_time is not None)
    data = xr.DataArray([[np.datetime64(start_time), np.datetime64(end_time)]],
                        dims=['bnds_time', 'bnds_1d'])
    return data
```

This is the result of `ncdump -h H8_B13_20190725.nc` after the modification above:
```
netcdf H8_B13_20190725 {
dimensions:
	x = 5500 ;
	y = 5500 ;
	time = 6 ;
	bnds_time = 1 ;
	bnds_1d = 2 ;
variables:
	int64 FLDK ;
		FLDK:crs_wkt = "PROJCRS[\"unknown\",BASEGEOGCRS[\"unknown\",DATUM[\"unknown\",ELLIPSOID[\"unknown\",6378137,298.257024882273,LENGTHUNIT[\"metre\",1,ID[\"EPSG\",9001]]]],PRIMEM[\"Greenwich\",0,ANGLEUNIT[\"degree\",0.0174532925199433],ID[\"EPSG\",8901]]],CONVERSION[\"unknown\",METHOD[\"Geostationary Satellite (Sweep Y)\"],PARAMETER[\"Longitude of natural origin\",140.7,ANGLEUNIT[\"degree\",0.0174532925199433],ID[\"EPSG\",8802]],PARAMETER[\"Satellite Height\",35785863,LENGTHUNIT[\"metre\",1,ID[\"EPSG\",9001]]],PARAMETER[\"False easting\",0,LENGTHUNIT[\"metre\",1],ID[\"EPSG\",8806]],PARAMETER[\"False northing\",0,LENGTHUNIT[\"metre\",1],ID[\"EPSG\",8807]]],CS[Cartesian,2],AXIS[\"(E)\",east,ORDER[1],LENGTHUNIT[\"metre\",1,ID[\"EPSG\",9001]]],AXIS[\"(N)\",north,ORDER[2],LENGTHUNIT[\"metre\",1,ID[\"EPSG\",9001]]]]" ;
		FLDK:false_easting = 0. ;
		FLDK:false_northing = 0. ;
		FLDK:geographic_crs_name = "unknown" ;
		FLDK:grid_mapping_name = "geostationary" ;
		FLDK:horizontal_datum_name = "unknown" ;
		FLDK:inverse_flattening = 298.257024882273 ;
		FLDK:latitude_of_projection_origin = 0. ;
		FLDK:long_name = "FLDK" ;
		FLDK:longitude_of_prime_meridian = 0. ;
		FLDK:longitude_of_projection_origin = 140.7 ;
		FLDK:perspective_point_height = 35785863. ;
		FLDK:prime_meridian_name = "Greenwich" ;
		FLDK:projected_crs_name = "unknown" ;
		FLDK:reference_ellipsoid_name = "unknown" ;
		FLDK:semi_major_axis = 6378137. ;
		FLDK:semi_minor_axis = 6356752.3 ;
		FLDK:sweep_angle_axis = "y" ;
	double x(x) ;
		x:units = "m" ;
		x:standard_name = "projection_x_coordinate" ;
	double y(y) ;
		y:units = "m" ;
		y:standard_name = "projection_y_coordinate" ;
	double time(time) ;
		time:standard_name = "time" ;
		time:bounds = "time_bnds" ;
		time:units = "days since 2019-07-25T05:00:21.467927" ;
		time:calendar = "proleptic_gregorian" ;
	double longitude(y, x) ;
		longitude:_FillValue = NaN ;
		longitude:name = "longitude" ;
		longitude:standard_name = "longitude" ;
		longitude:units = "degrees_east" ;
	double latitude(y, x) ;
		latitude:_FillValue = NaN ;
		latitude:name = "latitude" ;
		latitude:standard_name = "latitude" ;
		latitude:units = "degrees_north" ;
	float B13(time, y, x) ;
		B13:_FillValue = NaNf ;
		B13:calibration = "brightness_temperature" ;
		B13:end_time = "2019-07-25 05:34:40.838569" ;
		B13:grid_mapping = "FLDK" ;
		B13:id = "[\"B13\", [10.2, 10.4, 10.6], 2000, null, \"brightness_temperature\", null, []]" ;
		B13:modifiers = "" ;
		B13:platform_name = "Himawari-8" ;
		B13:resolution = 2000LL ;
		B13:scheduled_time = "2019-07-25 05:25:00" ;
		B13:sensor = "ahi" ;
		B13:standard_name = "toa_brightness_temperature" ;
		B13:start_time = "2019-07-25 05:25:21.441533" ;
		B13:units = "K" ;
		B13:wavelength = 10.2, 10.4, 10.6 ;
		B13:coordinates = "longitude latitude" ;
	double time_bnds(bnds_time, bnds_1d) ;

// global attributes:
		:history = "Created by pytroll/satpy on 2020-06-25 11:27:11.038053" ;
		:Conventions = "CF-1.7" ;
```

If it looks fine, I can create a PR for this.

### PR DESCRIPTION
**Pull request by zxdawn**
~~Currently, the `start_time` is the minimum `start_times` while `end_time` is the maximum `end_times`.~~

~~It's better to support the datatime array which is useful for time_series blending in `MultiScene`.~~

Delete the useless `time_bnds` for new version of xarray.

https://github.com/pytroll/satpy/blob/d7fbbdf00d40755b3ed82832fd3362ed19f8581a/satpy/writers/cf_writer.py#L467

 - [ ] Closes #1242, #1174 
 - [ ] Tests added 
 - [ ] Tests passed 
 - [ ] Passes ``flake8 satpy``

### CODE REVIEW

**Comment by sfinkens** [comment]
Thanks for looking into this! I tried it out with the following example, but it doesn't work yet:

```python
In [1]: from glob import glob                                                                                                                                                                                                                
In [2]: from satpy import MultiScene                                                                                                                                                                                                         
In [3]: from satpy.multiscene import timeseries                                                                                                                                                                                                                                                                                                                                                                                                                             
In [4]: filenames = glob('/data/georing/ahi_hsd/*', recursive=True)                                                                                                                                                                          
In [5]: mscn = MultiScene.from_files(filenames, reader="ahi_hsd")                                                                                                                                                                            
In [6]: mscn.load(['B13'])
In [7]: blended_scene = mscn.blend(blend_function=timeseries)
In [8]: blended_scene.save_datasets(writer='cf', filename='test.nc')       
Traceback:
...                                                                                                                                                       
ValueError: different number of dimensions on data and dims: 3 vs 2
```
I think this is because the start/end times passed to `make_time_bounds` are not the coordinates added by `timeseries`.
You should also keep in mind that

- There are use cases where the multiscene was blended with a different method (stack instead of timeseries for example). Then there will be no `start_time` or `end_time` coordinates.
- By default the CF writer prepends the dataset name to non-dimensional coordinates: `start_time` -> `B13_start_time`. See the `make_alt_coords_unique` method.

If this turns out to be too much work, a quick fix could be to not add time bounds if the time dimension is larger than 1.

**Comment by zxdawn** [comment]
The `time_bnds` is useless in the new version of xarray:
https://github.com/pytroll/satpy/blob/d7fbbdf00d40755b3ed82832fd3362ed19f8581a/satpy/writers/cf_writer.py#L467

I delete it instead of figuring how to make it work for many situations ...

**Comment by mraspaud** [comment]
@zxdawn I'm not sure I understand this PR fully: Passing the time bounds to the encoding is according to the comment not necessary after xarray 0.14. However that line is not removed. Moreover, that is removed is the creation and insertion of the time bounds variable, and I don't understand why that is?

**Comment by zxdawn** [comment]
@mraspaud Sorry, I forgot to delete the line of passing the time bounds to the encoding. Updated now.

**Comment by mraspaud** [comment]
No problem. Did the tests not need updating?

**Review by mraspaud — CHANGES_REQUESTED** [review]
Looks good, the only thing left I think is change the minimum version of xarray in `setup.py`

**Comment by mraspaud** [comment]
yeah, you need to fix the tests, making sure xarray is doing its job too.

**Comment by zxdawn** [comment]
Updated the `setup.py` and deleted/modified the tests of time bounds now.

**Comment by mraspaud** [comment]
@zxdawn thanks! I'm wondering what the comment saying "the time bounds can be removed after xarray 0.14" actually means. Does it mean that there is a building mechanism in xarray for that now, and should we test that? @sfinkens do you know?

**Comment by sfinkens** [comment]
@mraspaud @zxdawn I think there was a misunderstanding in the conversation here and on slack some time ago.

xarray does not automatically add time bounds when you save a dataset to netcdf. Although not required by the CF conventions, they provide very valuable information and in my opinion we should keep them.

That comment in `_set_default_time_encoding` was about the _encoding_ of time bounds. Before version 0.14 xarray did not recognize that time bounds and time coordinates should be encoded in the same way. Instead `time` could be encoded as `days since 1970` whereas `time_bounds` would be in `microseconds since 2020-01-01 12:15:30`.

If I remember correctly, the issue here is that `make_time_bounds` computes a single tuple `(tstart, tend)`, even if there are multiple timestamps in the dataset. In that case you would probably want bounds for every time stamp.

**Comment by zxdawn** [comment]
@mraspaud As explained by @sfinkens, the time bounds for each timestamp are required. I don't have another reason for removing this. May I close this and make another PR, this one looks a little confused?

**Comment by mraspaud** [comment]
Yes, absolutely! I'll just go ahead and close this, feel free to start another PR.

**Pull request closed without merging**
