### PR TITLE
Replace np.bool by np.bool_

### PR DESCRIPTION
**Pull request by gerritholl**
np.bool no longer exists in latest numpy, replace with np.bool_.

 - [ ] Tests added 
 - [ ] Fully documented

### CODE REVIEW

**Comment by mraspaud** [comment]
IIRC, `np.bool` was an alias for `bool`, so what is the motivation for switching to `np.bool_`?

**Comment by gerritholl** [comment]
> IIRC, `np.bool` was an alias for `bool`, so what is the motivation for switching to `np.bool_`?

Considering the context, `np.bool_` is probably what was intended.  All other types are numpy types.

**Comment by gerritholl** [comment]
They actually have the same effect:

```
In [136]: dtype([("C", bool), ("D", np.bool_)])
Out[136]: dtype([('C', '?'), ('D', '?')])
```

So, why switch?  For consistency with the rest of the record array definition.

**Comment by gerritholl** [comment]
The remaining failures are due to libtiff.

https://github.com/pearu/pylibtiff/blob/308bde1b0cedfa15d00ac7e7c3e95a8c39ba2065/libtiff/libtiff_ctypes.py#L644

**Review by mraspaud — APPROVED** [review]
LGTM

**Pull request merged**
