### PR TITLE
Fix leftovers from module splitting

### PR DESCRIPTION
**Pull request by mraspaud**
#1327 broke some yaml config files. This PR fixes this.

### CODE REVIEW

**Comment by djhoese** [comment]
Sorry! Any idea why tests didn't catch this? They are supposed to check every reader config.

**Comment by mraspaud** [comment]
I suppose these readers aren't tested correctly yet?

**Comment by djhoese** [comment]
Hm actually maybe the tests do a safe loading where they don't import things.

**Comment by mraspaud** [comment]
@djhoese ok to merge?

**Pull request merged**
