### PR TITLE
Make WavelengthRange importable from satpy.dataset

### PR DESCRIPTION
**Pull request by sfinkens**
This PR makes the `satpy.dataset.dataid.WavelengthRange` class from importable from `satpy.dataset`. The [satpy internals docs](https://github.com/pytroll/satpy/blame/main/doc/source/dev_guide/satpy_internals.rst#L95) suggest that, but currently the import doesn't work.

### CODE REVIEW

**Comment by djhoese** [comment]
My guess is this was a find/replace error when I was moving these modules around when refactoring. Interested why you decided to change the imports rather than change the documentation in the satpy internals?

**Comment by sfinkens** [comment]
In fact I first changed the documentation, but then I saw that `ModifierTuple` is already available in `satpy.dataset`, so I thought maybe that's how it's supposed to be :smile:

**Comment by sfinkens** [comment]
@mraspaud Any opinion? Otherwise I would revert the changes and update the documentation

**Comment by adybbroe** [comment]
Where are we here? 
I suppose we should not also include `FrequencyRange` etc from `readers/pmw_channels_definitions.py`!?

**Comment by mraspaud** [comment]
I'm good with that change, but in what context would that be useful for a user?

**Review by mraspaud — APPROVED** [review]
LGTM

**Pull request merged**
