### PR TITLE
Fix ABI L2 reader not scaling and masking data

### PR DESCRIPTION
**Pull request by djhoese**
This PR does the following:

* Fix L2 reader so it scales and masks data (it wasn't doing this before)
* Fix ABI L1b and L2 readers so they preserve integer data types of possible (including preserving `_FillValue` attribute for use later in satpy)
* Add `calibration` to C01-C16 CMI products
* Move resolution metadata to the python `available_datasets` method to get it from the file. CSPP Geo's products are supposed to all be 2km but the operational products from NOAA vary.
* Add day and night versions of the COD and CSP products. CSPP Geo does not merge these algorithm's output together so you get two separate files that could both exist for the same time step.
* Fix the `area_code` part of the file name patterns so they catch M1 and M2 for mesoscale data.
* As part of the two above points, separate the plain COD and CSP file patterns so they won't conflict with the CODD/CODN/CSPD/CSPN names.
* Add CSPP Geo's NAV product file for Longitude and Latitude. This is a "nice to have" product that CSPP Geo passes on from the AIT software instead of hiding it from the user. It is an unofficial product.
* Adds the FSC (fractional snow cover) file and dataset to the reader

One more question: Should I remove the `ancillary_variables` attributes from the file so we avoid the warning about not being able to load the `DQF` variable?

@yufeizhu600 Please review/test if possible.

 - [ ] Tests added and test suite added to parent suite 
 - [ ] Tests passed 
 - [ ] Passes ``flake8 satpy``

### CODE REVIEW

**Comment by djhoese** [comment]
Tests are failing because of https://github.com/pydata/xarray/issues/3317

**Comment by djhoese** [comment]
@yufeizhu600 Based on your comments on slack and the fixes I did, do you think this is ready for merge?

**Comment by djhoese** [comment]
@yufeizhu600 Now that I have your most recent changes, do you think this is ready for merge?

@mraspaud Review if you'd like otherwise I'll probably merge while traveling on Sunday.

**Comment by yufeizhu600** [comment]
Yes, I think it is good to go ahead.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Pull request merged**
