### PR TITLE
Feature handle data from HY-2B SCAT files directly from NSOAS 

### LINKED ISSUE #1783: Metadata name problem in HY-2B L2B reader
- **First,** I found that one of the names in `Global_Attributes` maybe changed from `L2B_Number_WVC_cells` to `L2B_Expected_WVC_Cells`. 
https://github.com/pytroll/satpy/blob/983961bfb06cdb80ae9dcebd7ad86fe6cca13382/satpy/readers/hy2_scat_l2b_h5.py#L59
I use the data provided by NSOAS. Due to I don't have EUMETCast data that  I can't verify whether it is different from the data distributed by EUM.  
Metadata
- **Second**  
During the plotting process, found that if this error is not modified, an error will be reported as  
```python
Failed to load DataID(name='wvc_lat', resolution=25000, modifiers=()) from <HY2SCATL2BH5FileHandler: 'C:/...too long.h5'>
Traceback (most recent call last):
File "C:\ProgramData\Miniconda3\envs\my_satpy_env\lib\site-packages\satpy\readers\yaml_reader.py", line 689, in _load_dataset
projectable = fh.get_dataset(dsid, ds_info)
File "C:\ProgramData\Miniconda3\envs\my_satpy_env\lib\site-packages\satpy\readers\hy2_scat_l2b_h5.py", line 99, in get_dataset
data = self._mask_data(key['name'], data)
File "C:\ProgramData\Miniconda3\envs\my_satpy_env\lib\site-packages\satpy\readers\hy2_scat_l2b_h5.py", line 118, in _mask_data
valid_range = self[key_name].attrs['valid range']
KeyError: 'valid range'
```  
I fixed `valid range` into `valid_range` in this line. Don’t know if I’m doing this correctly?  
https://github.com/pytroll/satpy/blob/983961bfb06cdb80ae9dcebd7ad86fe6cca13382/satpy/readers/hy2_scat_l2b_h5.py#L118 

- Third is about a question that is it support to draw wind direction vector arrows? The image I processed through composite only has the wind speed color filling map.  
  
Thanks for your attention to this matter.

### PR DESCRIPTION
**Pull request by TAlonglong**
Handle small differences in HY-2B SCAT files from NSOAS and data received via Eumetcast Eumetsat

 - [X] Closes #1783  
 - [X] Tests added

### CODE REVIEW

**Comment by TAlonglong** [comment]
Maybe this one can go into the next release @mraspaud

**Review by mraspaud — APPROVED** [review]
LGTM, thanks for adding the nsoas file format to the reader! Does the list of supported formats need to be adjusted in the main documentation page?

**Comment by TAlonglong** [comment]
Hm, you mean here: https://satpy.readthedocs.io/en/latest/index.html?highlight=%20MTG%20FCI%20Level%202#satpy-s-documentation. I will add a few letters

**Comment by mraspaud** [comment]
Yes, in the main table :) thanks!

**Pull request merged**
