### PR TITLE
Sort AUTHORS.md file by last name

### PR DESCRIPTION
**Pull request by djhoese**
Clean up AUTHORS.md list and other license headers throughout Satpy. Based on GPLv3 examples and documentation the header in individual files for a larger project should be:

```
# Copyright (c) 2018-2019 Satpy developers
#
# This file is part of satpy.
#
# satpy is free software: you can redistribute it and/or modify it under the
# terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# satpy is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE.  See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# satpy.  If not, see <http://www.gnu.org/licenses/>.
```

@pytroll/core Technically in python 3 we are no longer supposed to put the unicode declaration: https://www.python.org/dev/peps/pep-0008/#source-file-encoding Thoughts on removing this?

 - [ ] Closes #xxxx 
 - [ ] Passes ``flake8 satpy`` 
 - [ ] Fully documented

### CODE REVIEW

**Comment by mraspaud** [comment]
We use unicode encoding, hence we must have the header as long as we support python2 right ?

**Comment by djhoese** [comment]
> as long as we support python2 right ?

I suppose, yes. However, we probably only have 1 file with any actual unicode (non-ascii characters) in it.

**Comment by mraspaud** [comment]
Well, then you can remove it for the other files. Flake8 won't complain right ?

**Comment by djhoese** [comment]
It doesn't seem to when I removed it locally from `satpy/__init__.py`.

**Comment by pnuu** [comment]
Does the header example need to have the package name in lowercase? Or should it be `Satpy`?

**Comment by djhoese** [comment]
As mentioned on slack @pnuu, I believe the license is meant to be about the package so `satpy` (lowercase) is expected/intended.

**Comment by mraspaud** [comment]
@djhoese any news on this ?

**Comment by djhoese** [comment]
@mraspaud If you are ok with the license as I originally posted in this PR then I can update all the files. This may annoyingly break other PRs, but it has to happen at some point.

**Comment by mraspaud** [comment]
Go for it

**Comment by djhoese** [comment]
This is ready to merge. The FIXME that CodeFactor is complaining about is for #810.

**Comment by sfinkens** [comment]
LGTM, thanks for updating all the licenses!

**Pull request merged**
