### PR TITLE
Replace assertRaises with pytest.raises

### PR DESCRIPTION
**Pull request by mraspaud**
As the new ruff requires

 - [ ] Closes #xxxx 
 - [ ] Tests added 
 - [ ] Fully documented 
 - [ ] Add your name to `AUTHORS.md` if not there already

### CODE REVIEW

**Comment by djhoese** [comment]
Can you bump the version of `ruff` (or merge the pre-commit bot PR) to make sure that ruff is complaining about these?

**Comment by mraspaud** [comment]
> Can you bump the version of `ruff` (or merge the pre-commit bot PR) to make sure that ruff is complaining about these?

I will when I'm finished, otherwise I won't be able to commit smaller parts of the pr.

**Comment by djhoese** [comment]
Shouldn't ruff only run locally on the files you modify/commit?

**Comment by mraspaud** [comment]
Ah, yes indeed, what was I thunking.

**Pull request merged**
