### PR TITLE
Support emtpy datasets in yaml reader

### PR DESCRIPTION
**Pull request by zxdawn**
- [ ] Tests added 
 - [ ] Tests passed 
 - [ ] Passes ``flake8 satpy`` 
 - [ ] Fully documented 

Because some L2 and L3 data have different varnames in different products, we need to support empty `datasets` in yaml reader.

### CODE REVIEW

**Comment by djhoese** [comment]
Could you provide more detail and some examples of what you want to work and what isn't currently working? The handling of YAML datasets is complex and fairly flexible so I'm sure there is a way to support what you need without changing how this works. For example, if L2 and L3 are different file types then the variables can be defined with per-file_type parameters. I'm 90% sure this is allowed and will work.

**Comment by zxdawn** [comment]
Here's the example of four kinds of GPM L2 data:
image


The group name and root varnames are different. I don't know the suitable method of adding some to `datasets` in yaml.

Besides, the 2D lon and lat have different shapes under different groups in the same file:
image
I don't know how to set the coordinates which can be used in resample in the reader.

**Comment by djhoese** [comment]
Sometimes it seems like file designers don't want people to easily use their files.

So this PR is needed because in your PR (#1234) you are defining all datasets with `available_datasets` right? I don't understand why this doesn't work already. Were you getting some kind of error before? In your other PR you have `datasets: ~`. What if you do `datasets: {}`?

**Comment by zxdawn** [comment]
If I change `datasets: ~` to `datasets: {}`, it works well. Shall we close this PR?

**Comment by mraspaud** [comment]
If you're happy with `datasets: {}`, please close this :)

**Pull request closed without merging**
