### PR TITLE
Remove 1-D lat/lon variables from mimic reader's available datasets

### LINKED ISSUE #1371: MIMIC reader available_dataset_names returns 1d lat/lon fields
**Describe the bug**
A mimic dataset loaded into the Scene object will include the data field (TPWGrid at the least) and the 1-D latitude and longitude fields.  The latitude and longitude fields are 1-D versus the 2-D.

**To Reproduce**

```python
from satpy import find_files_and_readers, Scene
mimic_files=find_files_and_readers(base_dir=<mimic_data_dir>)
scn = Scene(mimic_files)
keys = scn.available_dataset_names()
scn.load(keys)    # Therefore this fails
scn.save_datasets(filename="{name}_{start_time:%Y%m%d%H%M%S}.tif")  # also fails/see Actual Results for further information
```

**Expected behavior**
I am thinking that any dataset available from the available_dataset_names should load without error, or it should not be returned in the list of available_dataset_names.  True?

**Actual results**

**Odd, when debug_on is not set, there is an error with the load command, but not with debug_on.**
Could not load dataset 'DatasetID(name='latitude', wavelength=None, resolution=None, polarization=None, calibration=None, level=None, modifiers=())': different number of dimensions on data and dims: 1 vs 2
Traceback (most recent call last):
  File "/home/joleenf/miniconda3/envs/satpy/lib/python3.8/site-packages/satpy/readers/yaml_reader.py", line 782, in _load_dataset_with_area
    ds = self._load_dataset_data(file_handlers, dsid, **kwargs)
  File "/home/joleenf/miniconda3/envs/satpy/lib/python3.8/site-packages/satpy/readers/yaml_reader.py", line 667, in _load_dataset_data
    proj = self._load_dataset(dsid, ds_info, file_handlers, **kwargs)
  File "/home/joleenf/miniconda3/envs/satpy/lib/python3.8/site-packages/satpy/readers/yaml_reader.py", line 643, in _load_dataset
    projectable = fh.get_dataset(dsid, ds_info)
  File "/home/joleenf/miniconda3/envs/satpy/lib/python3.8/site-packages/satpy/readers/mimic_TPW2_nc.py", line 109, in get_dataset
    data = xr.DataArray(data, dims=['y', 'x'])
  File "/home/joleenf/miniconda3/envs/satpy/lib/python3.8/site-packages/xarray/core/dataarray.py", line 344, in __init__
    coords, dims = _infer_coords_and_dims(data.shape, coords, dims)
  File "/home/joleenf/miniconda3/envs/satpy/lib/python3.8/site-packages/xarray/core/dataarray.py", line 121, in _infer_coords_and_dims
    raise ValueError(
ValueError: different number of dimensions on data and dims: 1 vs 2
The following datasets were not created and may require resampling to be generated: DatasetID(name='longitude', wavelength=None, resolution=None, polarization=None, calibration=None, level=None, modifiers=()), DatasetID(name='latitude', wavelength=None, resolution=None, polarization=None, calibration=None, level=None, modifiers=())

**However, with debug_on, no error is created with the load, the error occurs in the save_datasets step:**
----> 1 scn.save_datasets(filename="{name}_{start_time:%Y%m%d%H%M%S}.tif")

~/miniconda3/envs/satpy/lib/python3.8/site-packages/satpy/scene.py in save_datasets(self, writer, filename, datasets, compute, **kwargs)
   1347             datasets = [ds for ds in datasets if ds is not None]
   1348         if not datasets:
-> 1349             raise RuntimeError("None of the requested datasets have been "
   1350                                "generated or could not be loaded. Requested "
   1351                                "composite inputs may need to have matching "

RuntimeError: None of the requested datasets have been generated or could not be loaded. Requested composite inputs may need to have matching dimensions (eg. through resampling).

**Environment Info:**
 - OS: Linux (only tested on Linux)
 - Satpy Version: 0.22

### PR DESCRIPTION
**Pull request by joleenf**
Removes the 1-D lat/lon variables from the mimic reader yaml so that lat/lon values are only used as coordinates and do not appear in the available_dataset_ids list.  

 - [x] Closes #1371 
 - [ ] No new tests added

### CODE REVIEW

**Review by djhoese — APPROVED** [review]
Oh wow, it was that simple?

I changed the title since we use the PR and issue titles in our release notes and thought this would be more clear to those unfamiliar with the issue number(s).

**Comment by joleenf** [comment]
Yes.  It seems that it was that simple, which makes me nervous that I actually missed something.  However, I checked with a high and low resolution file, along with the test data.  I should probably create a second test dataset to replicate the lower resolution files now that I think of it.

**Comment by joleenf** [comment]
How do I put a hold on this request until I can make sure the testing files are working correctly?  I thought they were passing, but they just were not running due to a missing package.

**Comment by pnuu** [comment]
I'm not sure if it's visible to you, but there's a `Convert to draft` link below the reviewers.

**Comment by joleenf** [comment]
@pnuu Thanks!

**Comment by pnuu** [comment]
The Travis build failures are caused by the newest `eccodes` or `python-eccodes` package(s) in conda-forge. @mraspaud is inspectin this in Slack and https://github.com/pytroll/satpy/pull/1408

**Comment by pnuu** [comment]
I restarted the failed Linux build on Travis, the `python-eccodes` has now been built on Conda and the tests should pass.

**Comment by joleenf** [comment]
@mraspaud @djhoese  This is ready.  This pull request addresses #1392 as stated in initial pull request.  It also adds enhancements for the additional data fields contained in the lower resolution imagery.  In addition, a test is added for the structure of the lower resolution files.

**Review by mraspaud — APPROVED** [review]
LGTM, thanks for taking the time to add tests!

**Pull request merged**
