### PR TITLE
Fix Scene modifying user-provided reader_kwargs

### PR DESCRIPTION
**Pull request by djhoese**
While working with the `MultiScene` I noticed that only the first Scene creation was working and failing on the second because `reader_kwargs` passed by me were being modified by the Scene. This is the simplest fix I could think of for fixing this.

 - [ ] Closes #xxxx 
 - [x] Tests added 
 - [ ] Fully documented

### CODE REVIEW

**Review by pnuu — COMMENTED** [review]
Codecov seems to think the fix isn't covered by the modified tests.

**Comment by djhoese** [comment]
I never liked codecov anyway :wink: 

If I click on the link I get this:

image

But then if I expand `utils.py` it looks like it isn't being covered:

image

**Comment by djhoese** [comment]
I don't know exactly what codecov's problem is. Everything is tested now and when you click on the codecov Details it shows that things are covered...I think.

As discussed on slack with @pnuu, this PR now also clarifies/fixes the case where storage_options are defined at the "global" reader_kwargs level and the per-reader level (use global as defaults, overwrite with reader-specific).

**Review by pnuu — APPROVED** [review]
LGTM

**Pull request merged**
