### PR TITLE
Add Python 3.9 to CI tests

### PR DESCRIPTION
**Pull request by gerritholl**
Add GitHub CI tests for newer versions of Python.

 - [x] Closes #1876 
 - [x] Tests added

### CODE REVIEW

**Comment by gerritholl** [comment]
Not sure if this is enough; there are some other references to 3.8; I don't know if those would need updating too?

**Comment by djhoese** [comment]
I don't think conda-forge has all packages up for Python 3.10, so these tests will probably fail. What other references to Python 3.8 are there? In the other CI environments? I'd be OK with those being bumped to 3.9 or left as-is.

**Comment by gerritholl** [comment]
I mean that within the same file there are two references to `python-version: "3.8"`, but I don't know if that affects the actual tests.

**Comment by djhoese** [comment]
If you follow the indentation up, the python-versions map to Python 3.9 for the lint and style checks, 3.8 for the website building, 3.8 for the "experimental/unstable" tests. I think all of those are reasonable for now.

**Pull request merged**
