### PR TITLE
Fix xarray version for cf tests

### PR DESCRIPTION
**Pull request by mraspaud**
This PR fixes xarray version for cf tests

### CODE REVIEW

**Review by sfinkens — APPROVED** [review]
LGTM, thanks!

**Comment by djhoese** [comment]
Bokeh fixes in geoviews that haven't been released yet: https://github.com/holoviz/geoviews/pull/633

**Review by djhoese — APPROVED** [review]
This looks good to me to get things moving again.

**Comment by mraspaud** [comment]
Thanks @djhoese for adding the second fix!

**Pull request merged**
