### PR TITLE
Fix geotiff writer FAQ link

### PR DESCRIPTION
**Pull request by gerritholl**
Fix geotiff writer FAQ link to point to Satpy FAQ rather than to xarray
FAQ.

Add a gitignore for automatically generated RST sources by sphinx-apidoc.

 - [x] Fully documented

### CODE REVIEW

**Review by djhoese — CHANGES_REQUESTED** [review]
That `.gitignore` shouldn't be needed. It should be covered by the `<root>/.gitignore`.

**Comment by djhoese** [comment]
https://github.com/pytroll/satpy/blob/1aa9c5f6a501319c60009853e0c7eec15cffcbfe/.gitignore#L76

**Comment by djhoese** [comment]
Oh! It needs to be `doc/source/api/*.rst`.

**Comment by gerritholl** [comment]
> That `.gitignore` shouldn't be needed. It should be covered by the `<root>/.gitignore`.

Without it I get lots of "untracked files" notifications".  The root `.gitignore` does not include any `doc/source/api/*.rst`, but I'm happy to add one if you prefer it there rather than here.

**Comment by djhoese** [comment]
Could you remove the line above yours in the `.gitignore`. That was supposed to be the one catching the api files.

**Review by djhoese — APPROVED** [review]
Thanks!

**Pull request merged**
