### PR TITLE
Feature decorate

### PR DESCRIPTION
**Pull request by TAlonglong**
Added decorate possibilities in save_dataset

### CODE REVIEW

**Comment by mraspaud** [comment]
Would be nice if you could add something to the documentation about this!

**Comment by TAlonglong** [comment]
Hm, sounds like a good idea. But I'm not sure where this would be.

Should it go in the satpy source? under doc/source eg the quickstart.rst?

**Comment by mraspaud** [comment]
In the source at least, just add a docstring in every function, possibly with a short example on how to use the function. Then, if you can add a small section in the quickstart, that would be great !

**Comment by mraspaud** [comment]
Thanks for the PR @TAlonglong

**Pull request merged**
