### PR TITLE
Fix AHI source file segment order after decompressing.

### LINKED ISSUE #2127: Raised RuntimeError when trying to make HIMAWARI-8 true color image
**Describe the bug**
I was trying to make a HIMAWARI-8 true color image. However, SatPy module raised a ```RuntimeError``` to me at ```_slice_data``` function.

**To Reproduce**

```python
# Your code here
def get_area_def_format(proj, georange, res):
    min_lon, max_lon, min_lat, max_lat = georange
    left = min_lon
    right = max_lon
    up = min_lat
    down = max_lat
    res = res * 1000
    lat_0 = (up + down) / 2
    lon_0 = (right + left) / 2
    
    from pyproj import Proj
    p = Proj(proj=proj, lat_0=lat_0, lon_0=lon_0, ellps="WGS84")
    
    left_ex1, up_ex1 = p(left, up)
    right_ex1, up_ex2 = p(right, up)
    left_ex2, down_ex1 = p(left, down)
    right_ex2, down_ex2 = p(right, down)
    left_ex3, dummy = p(left, lat_0)
    right_ex3, dummy = p(right, lat_0)
    
    area_extent = (min(left_ex1, left_ex2, left_ex3),
                   min(up_ex1, up_ex2),
                   max(right_ex1, right_ex2, right_ex3),
                   max(down_ex1, down_ex2))
    
    xsize = int(round((area_extent[2] - area_extent[0]) / res))
    ysize = int(round((area_extent[3] - area_extent[1]) / res))
    
    return lat_0, lon_0, xsize, ysize, area_extent

channel = "true_color"

scn = Scene(glob.glob("./HS_H08*.DAT.bz2"), reader='ahi_hsd')
scn.load([channel])

georange = (32.5, 47.5, 112.5, 127.5)
latmin, latmax, lonmin, lonmax = georange

from pyresample import get_area_def
area_id = 'TEST01'
lat_0, lon_0, x_size, y_size, area_extent = get_area_def_format("eqc", (lonmin, lonmax, latmin, latmax), 1)
projection = f'+proj=eqc +lat_0={lat_0} +lon_0={lon_0} +ellps=WGS84'
description = 'TEST01'
proj_id = f'eqc_{lat_0}_{lon_0}'
areadef = get_area_def(area_id, description, proj_id, projection, x_size, y_size, area_extent)
new_scn = scn.resample(areadef)
new_scn.save_dataset(channel, base_dir="./true_color/", filename=f"{args.system}_true_color.png")
```

**Expected behavior**
Succeed in compositing true color image and save it in certain folder.

**Actual results**
```python
# For these results below I have used these codes in ```_slice_data```:
# print(slice_x, slice_y)
# print(('x', source_area.width), ('y', source_area.height), dataset.sizes.items())
slice(3082, 4582, None) slice(1109, 2253, None)
('x', 1500) ('y', 1144) ItemsView(Frozen({'y': 1144, 'x': 1500}))
slice(3082, 4582, None) slice(1109, 2253, None)
('x', 1500) ('y', 1144) ItemsView(Frozen({'y': 1144, 'x': 1500}))
slice(3082, 4582, None) slice(1109, 2253, None)
('x', 1500) ('y', 1144) ItemsView(Frozen({'y': 1144, 'x': 1500}))
slice(6165, 9163, None) slice(2218, 4506, None)
('x', 2998) ('y', 2288) ItemsView(Frozen({'y': 2288, 'x': 2998}))
slice(6165, 9163, None) slice(2218, 4506, None)
('x', 2998) ('y', 2288) ItemsView(Frozen({'y': 2288, 'x': 2998}))
slice(6165, 9163, None) slice(2218, 4506, None)
('x', 2998) ('y', 2288) ItemsView(Frozen({'y': 2288, 'x': 2998}))
slice(3082, 4582, None) slice(1109, 2253, None)
('x', 1500) ('y', 1144) ItemsView(Frozen({'y': 1144, 'x': 1500}))
slice(3082, 4582, None) slice(1109, 2253, None)
('x', 1500) ('y', 1144) ItemsView(Frozen({'y': 0, 'x': 1500}))
Traceback (most recent call last):
  File "/www/wwwroot/Satima/satpy_ahi_true_color.py", line 271, in <module>
    Satpy()
  File "/www/wwwroot/Satima/satpy_ahi_true_color.py", line 59, in __init__
    self.ask_root()
  File "/www/wwwroot/Satima/satpy_ahi_true_color.py", line 150, in ask_root
    datas = self.extract(roots, center_lon, center_lat, self.georange, args.channel, names)
  File "/www/wwwroot/Satima/satpy_ahi_true_color.py", line 190, in extract
    new_scn = scn.resample(areadef)
  File "/root/miniconda3/lib/python3.9/site-packages/satpy/scene.py", line 908, in resample
    self._resampled_scene(new_scn, destination, resampler=resampler,
  File "/root/miniconda3/lib/python3.9/site-packages/satpy/scene.py", line 819, in _resampled_scene
    dataset, source_area = self._reduce_data(dataset, source_area, destination_area,
  File "/root/miniconda3/lib/python3.9/site-packages/satpy/scene.py", line 869, in _reduce_data
    dataset = self._slice_data(source_area, (slice_x, slice_y), dataset)
  File "/root/miniconda3/lib/python3.9/site-packages/satpy/scene.py", line 783, in _slice_data
    raise RuntimeError
RuntimeError
```

**Environment Info:**
 - OS: Ubuntu 20.04.4 LTS x86_64
 - Satpy Version: 0.35.0
 - PyResample Version: 1.23.0
 - PyProj Version: 3.3.0

**Additional context**
Additionally, I found that it sometimes succeed if I ran the code again.

### PR DESCRIPTION
**Pull request by mherbertson**
Fixes the order of AHI segment source files.

 - [x] Closes #2127 
 - [x] Tests added 
 - [x] Fully documented

### CODE REVIEW

**Comment by djhoese** [comment]
Looks like the tests may need to get updated.

Otherwise, the main issue this is fixing is that decompression was writing to essentially random filenames, right? As you mentioned in the issue this meant that sorting by start_time and filename produced random ordering. But wouldn't all the files still be included?

**Comment by mherbertson** [comment]
Yes I'll look at updating the tests. All files get loaded but the padding of the `area_def` will become corrupted as the segments are out of order so the shape becomes random at the end of the processing.

**Review by djhoese — APPROVED** [review]
LGTM but I'm not sure I should be the final word here. @simonrp84 any opinions? You added this originally right?

**Comment by simonrp84** [comment]
I did add it originally, yes, but it was heavily refactored since then and my efforts to reproduce this problem have failed. Assuming it fixes the problem then the solution looks good to me.
But can you run a check that this solution works OK with non-fulldisk data? I think it should, but confirmatino that it has no effect (and that the bug doesn't appear) with Target or Japan data would be good.

**Comment by mherbertson** [comment]
Japan area:
```
import glob
from satpy.scene import Scene
from satpy.utils import debug_on
debug_on()
scn = Scene(glob.glob("../temp/data/japan/*_JP04_*.bz2"), reader='ahi_hsd')
scn.load(['green_nocorr'])
```
Debug shows each file (16 Bands) has a temp file prefixed with the segment number:
```
[INFO: 2022-06-23 05:23:15 : satpy.readers.utils] Using temp file for BZ2 decompression: /tmp/01cuqnrvbj
[INFO: 2022-06-23 05:23:16 : satpy.readers.utils] Using temp file for BZ2 decompression: /tmp/013cdgo2sc
[INFO: 2022-06-23 05:23:16 : satpy.readers.utils] Using temp file for BZ2 decompression: /tmp/013g_2ipmf
[INFO: 2022-06-23 05:23:18 : satpy.readers.utils] Using temp file for BZ2 decompression: /tmp/01ulwubmv9
[INFO: 2022-06-23 05:23:19 : satpy.readers.utils] Using temp file for BZ2 decompression: /tmp/01fegzicnw
[INFO: 2022-06-23 05:23:19 : satpy.readers.utils] Using temp file for BZ2 decompression: /tmp/018q56pruf
[INFO: 2022-06-23 05:23:19 : satpy.readers.utils] Using temp file for BZ2 decompression: /tmp/01znz7bgfg
[INFO: 2022-06-23 05:23:19 : satpy.readers.utils] Using temp file for BZ2 decompression: /tmp/01nqzz72ec
[INFO: 2022-06-23 05:23:19 : satpy.readers.utils] Using temp file for BZ2 decompression: /tmp/01pppb_5nv
[INFO: 2022-06-23 05:23:19 : satpy.readers.utils] Using temp file for BZ2 decompression: /tmp/01i_b0wq45
[INFO: 2022-06-23 05:23:19 : satpy.readers.utils] Using temp file for BZ2 decompression: /tmp/01uorqntrz
[INFO: 2022-06-23 05:23:20 : satpy.readers.utils] Using temp file for BZ2 decompression: /tmp/01uct_q7rz
[INFO: 2022-06-23 05:23:20 : satpy.readers.utils] Using temp file for BZ2 decompression: /tmp/01h633w4gi
[INFO: 2022-06-23 05:23:20 : satpy.readers.utils] Using temp file for BZ2 decompression: /tmp/019zfw3h61
[INFO: 2022-06-23 05:23:20 : satpy.readers.utils] Using temp file for BZ2 decompression: /tmp/01m0zwaw4o
[INFO: 2022-06-23 05:23:20 : satpy.readers.utils] Using temp file for BZ2 decompression: /tmp/01ro3oluhb
```
Shape output:
```
>>> print(scn['green_nocorr'].shape)
(2400, 3000)
```
Image:
green_nocoor_JP04

**Pull request merged**
