### PR TITLE
Update geotiff writer default to tiled images

### PR DESCRIPTION
**Pull request by mherbertson**
This PR updates the `geotiff.yaml` to include `tiled=True` for more efficient image processing by default.

 - [x] Tests added 
 - [x] Fully documented

### CODE REVIEW

**Review by djhoese — CHANGES_REQUESTED** [review]
Thanks for getting this pull request started. It always falls through the cracks on our TODO lists.

Could you please change the default in the python code too? This way it is more explicit what is going on.

**Comment by mherbertson** [comment]
I've removed `tiled=True` from `geotiff.yaml` as this conflicts with a hard code in the writer.

**Comment by djhoese** [comment]
> I've removed tiled=True from geotiff.yaml as this conflicts with a hard code in the writer.

It conflicts?

**Review by djhoese — APPROVED** [review]

**Review by mraspaud — APPROVED** [review]
LGTM

**Comment by mraspaud** [comment]
Great and simple PR, thanks a lot! Merging...

**Pull request merged**
