### PR TITLE
Add Low Cloud and Fog products to ABI L2 reader

### PR DESCRIPTION
**Pull request by djhoese**
As part of my work with Geo2Grid, we'd like to support the GFLS (Fog Low Stratus...still not sure what the "G" stands for) files. The filenames are pretty different from other L2 products, but otherwise the file contents are relatively standard.

I'm not sure if I want to add some default enhancements for these products.

 - [ ] Closes #xxxx 
 - [x] Tests added 
 - [x] Fully documented

### CODE REVIEW

**Review by mraspaud — APPROVED** [review]
LGTM, but what do you want to do with the row/col renaming issue? Deal with it in a later PR?

**Comment by djhoese** [comment]
I have to check the other version of these files from NDE. The files from CSPP Geo/AIT are what I've been using and this dimension naming issue is what I would consider a "bug". I really don't want to have to write flexibility in the tests to change the dimensions just for this case. I've been talking with CSPP Geo/AIT and I think they agree this should be changed in their files.

**Comment by mraspaud** [comment]
Ok, we'll wait for the feedback from Graeme then before we go on with this one.

**Comment by djhoese** [comment]
CSPP Geo has not "standardized" their files by naming the dimensions y and x like the L1b files. They also include the grid mapping variable and related information. This PR is able to read those files.

I think I'd like to merge this PR as-is and deal with any user requests later on.

**Comment by djhoese** [comment]
Merging this because I need these things merged for some work I'm doing this week. It was approved before and not much has changed since as far as the reader goes.

**Pull request merged**
