### PR TITLE
Fixes for PR#2146 so readers now also work for VII L2 water vapour pr…

### PR DESCRIPTION
**Pull request by pepephillips**
…oducts

This PR fixes vii_base_nc.py so VII L2 WV products can be read and concatenated (fix include variables num_points_act, num_points_alt for the renaming to Y,X in _standardise_dims). Additionally a missing comma in the tpw product in vii_l2_nc.yaml is corrected and a redundant comma removed.

### CODE REVIEW

**Review by pnuu — APPROVED** [review]
LGTM

**Review by mraspaud — COMMENTED** [review]
Any chance of getting small test for the dimension rename? :)

**Comment by mraspaud** [comment]
@pepephillips Any chance of getting small test for the dimension rename? :)

**Comment by pepephillips** [comment]
Hi Martin,
Sorry for the unthinkably long delay but I have a small test. Shall I put in a PR for it or is it too late?

I’ve also been working on readers for CO2M missions CLIM (a simpler version of METimage) and MAP (3MI-like). MAP is so similar to 3MI its almost a cut and paste job to get something up and running. Have you already started on 3MI?
Cheers,
Pepe

**Review by mraspaud — APPROVED** [review]
LGTM

**Comment by mraspaud** [comment]
Thanks for finalizing this PR @pepephillips ! Merged

**Pull request merged**
