### PR TITLE
Factorize area computation in goes_imager_hrit

### LINKED ISSUE #1022: Factorize area def computation in goes_imager_hrit
## Feature Request

**Is your feature request related to a problem? Please describe.**
`HRITMSGFileHandler` now has two methods `_get_area_extent` and `get_area_extent` to compute the area extent. The latter is inherited from `HRITFileHandler` and yields incorrect results for SEVIRI.

**Describe the solution you'd like**
The only reader using `HRITFileHandler.get_area_extent` is `HRITGOESFileHandler`. So we could remove that method and use the new helper methods from `satpy.readers._geos_area` in `HRITGOESFileHandler` instead.

**Describe any changes to existing user workflow**
None

**Additional context**
None

### PR DESCRIPTION
**Pull request by sfinkens**
Use the helper methods from `satpy.readers._geos_area`, which have been around for a while now. Added the test first to make sure the extents remain unchanged.

 - [X] Closes #1022 
 - [X] Tests added

### CODE REVIEW

**Comment by sfinkens** [comment]
I think that this was the last reader to make use of `satpy.readers.hrit_base.HRITFileHander.get_area_def`. At least I can remove that method and all `*hrit*` reader tests still pass. Should we remove it then?

**Comment by sfinkens** [comment]
I also noticed that many GEO reader tests are very similar when it comes to verifying the area def. For example

```
        a, b = proj4_radius_parameters(area.proj_dict)
        assert a == EQUATOR_RADIUS
        assert b == POLE_RADIUS
        assert area.proj_dict['h'] == ALTITUDE
        assert area.proj_dict['lon_0'] == 100.1640625
        assert area.proj_dict['proj'] == 'geos'
        assert area.proj_dict['units'] == 'm'
        assert area.width == 2816
        assert area.height == 464
        assert area.area_id == 'goes-15_goes_imager_fd_3km'
        area_extent_exp = (-5639254.900260435, 1925159.4881528523,
                           5643261.475678028, 3784210.48191544)
        np.testing.assert_allclose(area.area_extent, area_extent_exp)
```

Should we add a helper method for that to `satpy.tests.utils`?

**Comment by djhoese** [comment]
> Should we add a helper method for that to satpy.tests.utils?

If you can make it reusable and generic enough then I'd say go for it.

**Review by mraspaud — APPROVED** [review]
LGTM!

**Pull request merged**
