### PR TITLE
Add GOCI-II L2 Netcdf Reader

### PR DESCRIPTION
**Pull request by Isotr0py**
This PR adds the code for the basic reader functionality for the official GOCI-II Level 2 products from [NOSC](https://www.nosc.go.kr/eng/program/actionTodayRcvImg.do).

### Features
GOCI-II Level-2 products reader:
- [x] Atmospheric correction output
- [x] Aerosol output
- [x] Inherent Optical Properties output
- [x] Ocean color output
- [x] Ocean output
- [x] ~~Land output~~ (Seems that Land products are still under tests)

Remote files support:
- [ ] Maybe support for ~~[NOSC's web directory](https://www.nosc.go.kr/wd/zTreeView.do)~~ [NOSC's OPeNDAP service](https://nosc.go.kr/opendap/)?
(Failed 😥)

### Other TODO:
 - [x] Tests added 
 - [ ] Fully documented

### CODE REVIEW

**Comment by Isotr0py** [comment]
I was blocked at the OPeNDAP support, because neither using `netCDF4` nor `h5netcdf` return a dataset only contain attributes, without any groups and variables.

For example:
```python
import netCDF4

url = 'http://nosc.go.kr/opendap/GOCI-II/2024/02/14/L2/GK2_GC2_L2_20240214_021530/GK2B_GOCI2_L2_20240214_021530_LA_S010_Zsd.nc'

data = netCDF4.Dataset(url,"r")
print("groups: ", data.groups)
```
It outputs:
```
groups: {}
```

However, local file downloaded from that url works well:
```python
import netCDF4

url = 'GK2B_GOCI2_L2_20240214_021530_LA_S010_Zsd.nc'

data = netCDF4.Dataset(url,"r")
print("groups: ", data.groups)
```
Output:
```
groups:  {'navigation_data': <class 'netCDF4._netCDF4.Group'>
group /navigation_data:
    dimensions(sizes): 
    variables(dimensions): float32 latitude(number_of_lines, pixels_per_line), float32 longitude(number_of_lines, pixels_per_line)
    groups: , 'geophysical_data': <class 'netCDF4._netCDF4.Group'>
group /geophysical_data:
    dimensions(sizes): 
    variables(dimensions): float32 Zsd(number_of_lines, pixels_per_line), uint8 flag(number_of_lines, pixels_per_line)
    groups: }
```

**Comment by Isotr0py** [comment]
It seems that the failure is about other readers:
```
satpy/tests/reader_tests/test_goci2_l2_nc.py ............                [ 51%]

...

=========================== short test summary info ============================
ERROR satpy/tests/reader_tests/test_atms_l1b_nc.py
ERROR satpy/tests/reader_tests/test_fci_l1c_nc.py
ERROR satpy/tests/reader_tests/test_fci_l2_nc.py
ERROR satpy/tests/reader_tests/test_ici_l1b_nc.py
ERROR satpy/tests/reader_tests/test_li_l2_nc.py
ERROR satpy/tests/reader_tests/test_mws_l1b_nc.py
ERROR satpy/tests/reader_tests/test_osisaf_l3.py
ERROR satpy/tests/reader_tests/test_vii_base_nc.py
ERROR satpy/tests/reader_tests/test_vii_l1b_nc.py
ERROR satpy/tests/reader_tests/test_vii_l2_nc.py
ERROR satpy/tests/reader_tests/test_vii_wv_nc.py
ERROR satpy/tests/reader_tests/test_viirs_edr_active_fires.py
ERROR satpy/tests/reader_tests/test_viirs_vgac_l1c_nc.py
!!!!!!!!!!!!!!!!!!! Interrupted: 13 errors during collection !!!!!!!!!!!!!!!!!!!
================= 2 skipped, 15 warnings, 13 errors in 10.41s ==================
```

**Comment by djhoese** [comment]
I'm not sure where you got that list of failing tests, but looking at CI it seems these are the VIIRS EDR failures that @mraspaud fixed and merged into main. If you merge with pytroll main it should get the CI tests further.

**Comment by Isotr0py** [comment]
It's strange that `satpy\tests\modifier_tests\test_angles.py` failed in windows tests, while ubuntu and macos passed.

**Comment by djhoese** [comment]
I've restarted the failing tests just in case it was a race condition/hiccup.

**Comment by djhoese** [comment]
Looks good now, I think.

**Review by mraspaud — APPROVED** [review]
LGTM!

**Pull request merged**
