### PR TITLE
Cleanup optional dependencies in setup.py

### LINKED ISSUE #562: Undocumented dependency packages
There are three packages that are used by satpy but are not listed in the (optional) requirements list in setup.py:

 * pydecorate
 * glymur
 * pyninjotiff

In particular pydecorate seems to be used during unit testing.

**To Reproduce**
```
$ python3 setup.py test
```

**Expected behavior**
All tests are executed without errors

**Actual results**
4 test failures
```
======================================================================
ERROR: test_add_decorate_basic_l (satpy.tests.test_writers.TestOverlays)
Test basic add_decorate usage with L data.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/antonio/debian/git/satpy/satpy/tests/test_writers.py", line 599, in setUp
    self.dw = self.dec_writer.start()
  File "/usr/lib/python3.7/unittest/mock.py", line 1390, in start
    result = self.__enter__()
  File "/usr/lib/python3.7/unittest/mock.py", line 1243, in __enter__
    self.target = self.getter()
  File "/usr/lib/python3.7/unittest/mock.py", line 1413, in <lambda>
    getter = lambda: _importer(target)
  File "/usr/lib/python3.7/unittest/mock.py", line 1096, in _importer
    thing = __import__(import_path)
ModuleNotFoundError: No module named 'pydecorate'

======================================================================
ERROR: test_add_decorate_basic_rgb (satpy.tests.test_writers.TestOverlays)
Test basic add_decorate usage with RGB data.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/antonio/debian/git/satpy/satpy/tests/test_writers.py", line 599, in setUp
    self.dw = self.dec_writer.start()
  File "/usr/lib/python3.7/unittest/mock.py", line 1390, in start
    result = self.__enter__()
  File "/usr/lib/python3.7/unittest/mock.py", line 1243, in __enter__
    self.target = self.getter()
  File "/usr/lib/python3.7/unittest/mock.py", line 1413, in <lambda>
    getter = lambda: _importer(target)
  File "/usr/lib/python3.7/unittest/mock.py", line 1096, in _importer
    thing = __import__(import_path)
ModuleNotFoundError: No module named 'pydecorate'

======================================================================
ERROR: test_add_overlay_basic_l (satpy.tests.test_writers.TestOverlays)
Test basic add_overlay usage with L data.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/antonio/debian/git/satpy/satpy/tests/test_writers.py", line 599, in setUp
    self.dw = self.dec_writer.start()
  File "/usr/lib/python3.7/unittest/mock.py", line 1390, in start
    result = self.__enter__()
  File "/usr/lib/python3.7/unittest/mock.py", line 1243, in __enter__
    self.target = self.getter()
  File "/usr/lib/python3.7/unittest/mock.py", line 1413, in <lambda>
    getter = lambda: _importer(target)
  File "/usr/lib/python3.7/unittest/mock.py", line 1096, in _importer
    thing = __import__(import_path)
ModuleNotFoundError: No module named 'pydecorate'

======================================================================
ERROR: test_add_overlay_basic_rgb (satpy.tests.test_writers.TestOverlays)
Test basic add_overlay usage with RGB data.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/antonio/debian/git/satpy/satpy/tests/test_writers.py", line 599, in setUp
    self.dw = self.dec_writer.start()
  File "/usr/lib/python3.7/unittest/mock.py", line 1390, in start
    result = self.__enter__()
  File "/usr/lib/python3.7/unittest/mock.py", line 1243, in __enter__
    self.target = self.getter()
  File "/usr/lib/python3.7/unittest/mock.py", line 1413, in <lambda>
    getter = lambda: _importer(target)
  File "/usr/lib/python3.7/unittest/mock.py", line 1096, in _importer
    thing = __import__(import_path)
ModuleNotFoundError: No module named 'pydecorate'
```

**Environment Info:**
 - Linux (debian sid)
 - SatPy Version: 0.11.0
 - PyResample Version: 1.10.3
 - Readers and writers dependencies (when relevant): 
Readers
=======
Environment variable PYGAC_CONFIG_FILE not set!
abi_l1b: ok
abi_l1b_scmi: ok
acspo: ok
ahi_hrit: ok
ahi_hsd: ok
amsr2_l1b: ok
avhrr_l1b_aapp: ok
avhrr_l1b_eps: ok
avhrr_l1b_gaclac: cannot find module 'satpy.readers.avhrr_l1b_gaclac' (No module named 'ConfigParser')
avhrr_l1b_hrpt: ok
caliop_l2_cloud: cannot find module 'satpy.readers.caliop_l2_cloud' (No module named 'pyhdf')
clavrx: cannot find module 'satpy.readers.clavrx' (No module named 'pyhdf')
electrol_hrit: ok
fci_l1c_fdhsi: ok
generic_image: ok
geocat: ok
ghrsst_l3c_sst: ok
goes-imager_hrit: ok
goes-imager_nc: ok
grib: ok
iasi_l2: ok
jami_hrit: ok
li_l2: ok
maia: ok
modis_l1b: cannot find module 'satpy.readers.modis_l1b' (No module named 'pyhdf')
msi_safe: cannot find module 'satpy.readers.msi_safe' (No module named 'glymur')
mtsat2-imager_hrit: ok
nucaps: ok
nwcsaf-geo: ok
nwcsaf-pps_nc: ok
olci_l1b: ok
olci_l2: ok
omps_edr: ok
sar-c_safe: ok
scatsat1_l2b: ok
seviri_l1b_hrit: ok
seviri_l1b_native: ok
seviri_l1b_nc: ok
slstr_l1b: ok
viirs_compact: ok
viirs_edr_flood: cannot find module 'satpy.readers.viirs_edr_flood' (No module named 'pyhdf')
viirs_l1b: ok
viirs_sdr: ok

Writers
=======
cf: ok
geotiff: ok
mitiff: ok
ninjotiff: cannot find module 'satpy.writers.ninjotiff' (No module named 'pyninjotiff')
scmi: ok
simple_image: ok

### PR DESCRIPTION
**Pull request by djhoese**
Some of the unique optional dependencies for parts of Satpy are missing from the setup.py. By unique I mean dependencies that aren't needed by a lot of readers, only a select few. See #562 for some of the discussion on this.

I also rearranged some of the existing dependencies so they make a little more sense. One odd one I noticed is that abi_l1b is currently listed as needed h5netcdf which isn't actually true (netcdf4-python is fine). Thoughts on this @mraspaud?

 - [x] Closes #562 
 - [ ] Tests added 
 - [ ] Fully documented

### CODE REVIEW

**Comment by mraspaud** [comment]
Regarding abi, I think h5netcdf and python-netcdf 4 might return different types for attributes (eg arrays against strings) so maybe that's why the former was chosen?

**Comment by djhoese** [comment]
I think h5netcdf was just your original preference when you wrote the reader (I think you wrote the first version). I remember the "engine" kwarg being hardcoded to h5netcdf.

**Comment by djhoese** [comment]
@mraspaud I decided to take this PR and add the coveralls upload. CC @adybbroe who I was going to try to pressure to do it, but I beat him to it.

**Review by mraspaud — APPROVED** [review]
LGTM

**Comment by djhoese** [comment]
I'm not really sure what happened with codecov. It says -0.37% lost in the satpy/utils.py module. Basically saying the module is never called. I'm not sure how these changes could have effected this unless the report being generated now doesn't include that. That isn't intended and doesn't make sense. I guess we'll see what happens when it is merged.

**Pull request merged**
