### PR TITLE
Fix geostationary area extent

### LINKED ISSUE #1160: Incorrect area extent of upright SEVIRI image
**Describe the bug**
The helper method `satpy.readers._geos_area.get_area_extent` seems to return an incorrect area extent for an upright SEVIRI image.

**To Reproduce**

```python
from satpy.readers._geos_area import get_area_extent

pdict = {'a': 6378169.00,
         'b': 6356583.80,
         'h': 35785831.00,
         'ssp_lon': 0.0,
         'nlines': 3712,
         'ncols': 3712,
         'a_name': 'geostest',
         'a_desc': 'test area',
         'p_id': 'test_area',
         'cfac': 13642337,
         'lfac': 13642337,
         'coff': 1856,
         'loff': 1856,
         'scandir': 'N2S'}
get_area_extent(pdict)
```

**Expected behavior**
I would expect this to return the extent of the `seviri_0deg` area definition:
```
(-5570248.686685662, -5567248.28340708, 5567248.28340708, 5570248.686685662)
```

**Actual results**
```
(-5567248.28340708, -5567248.28340708, 5570248.686685662, 5570248.686685662)
```

**Environment Info:**
 - OS: Linux
 - Satpy Version: 0.9.2.dev3144+g472c450e

**Additional context**
Here is a notebook describing the problem in more detail. I also tried to provide a fix, and it seems to work, but I do not entirely understand why. I know this is much to read, but I'd appreciate any help very much!

https://gist.github.com/sfinkens/a07ac7982699ed8fc0fb433bb75818b7

### PR DESCRIPTION
**Pull request by sfinkens**
Detailed problem description: https://gist.github.com/sfinkens/a07ac7982699ed8fc0fb433bb75818b7

I think my solution is now ready for a first discussion. Afterwards I would update all the readers and their unit tests.

 - [X] Closes #1160 
 - [ ] Tests added 
 - [ ] Tests passed 
 - [ ] Passes ``flake8 satpy`` 
 - [ ] Fully documented 
 - [ ] Add your name to `AUTHORS.md` if not there already

### CODE REVIEW

**Comment by sfinkens** [comment]
It would be good to be able to specify horizontal and vertical scanning directions separately. As I just learned in the video conference, FCI images are flipped upside-down only (not left-right).

**Comment by mraspaud** [comment]
@sfinkens any news on this?

**Comment by sfinkens** [comment]
@martin I would like to hear @simonrp84's and @ameraner's opinion on this, before I begin updating all the readers.

**Comment by simonrp84** [comment]
I've not been able to test this, but looking through the code it seems fine - good that it includes a detailed explanation as well, the LFAC/CFAC system can be a bit confusing!

**Comment by ameraner** [comment]
Very sorry for the very late reply on this, I could finally take a closer look at the code only now. Thanks a lot for the very nice explanation and implementation! It LGMT, cannot spot any flaw in the reasoning. I also checked the CGMS LRIT/HRIT Global Specification document, which is rather cryptic/confusing on the explanation for this:

> For the common orientation of the image both CFAC shall be positive. In order to support near realtime transmission of image data scanned from south to north LFAC may be selected negative.

See page 32 in[ this document ](https://www.cgms-info.org/documents/cgms-lrit-hrit-global-specification-(v2-8-of-30-oct-2013).pdf).

Regarding your comment above

> It would be good to be able to specify horizontal and vertical scanning directions separately. As I just learned in the video conference, FCI images are flipped upside-down only (not left-right).

I fully agree, although specifically FCI will not use this exact CFAC/COFF mechanism. It is rather using something like the inverse of it, with `x = col*scale_factor + add_offset`, i.e. with the offset being already in projection coordinates units rather than image coordinates units.

**Comment by sfinkens** [comment]
Thanks a lot @ameraner for taking the time! Then I'll continue with updating all the readers as soon I have time.

**Comment by sfinkens** [comment]
Just noticed that the solution attempt does not reproduce MTSAT extents:

```
>       np.testing.assert_allclose(extent, expected)
E       AssertionError: 
E       Not equal to tolerance rtol=1e-07, atol=0
E       
E       Mismatched elements: 2 / 4 (50%)
E       Max absolute difference: 4000.00006472
E       Max relative difference: 0.00072754
E        x: array([-5498000.08896 , -5502000.089025,  5502000.089025,  5498000.08896 ])
E        y: array([-5498000.08896 , -5498000.08896 ,  5502000.089025,  5502000.089025])
```
Is `(-a, -a, b, b)` indeed possible here?

**Pull request closed without merging**
