### PR TITLE
Remove unnecessary string decode in agri_l1 reader

### PR DESCRIPTION
**Pull request by jactry**
This fixs a regression introduced by commit 14d9681a35fe572c9e6dbedb2befa5746aa37936.

 - [x] Passes ``flake8 satpy`` 
 - [x] Add your name to `AUTHORS.md` if not there already

### CODE REVIEW

**Review by djhoese — COMMENTED** [review]
I believe @zxdawn recently ran into this issue as well. The main issue is newer versions of h5py loading/decoding strings differently. After investigating a bit with @zxdawn on slack, we weren't really sure why these strings were encoded with `gbk` anyway since they are all ASCII characters.

I'm OK with this PR, but am still curious why these strings ever needed to be decoded specifically with `gbk` in the first place.

**Comment by zxdawn** [comment]
@djhoese I can test different versions of h5py and report here later.

**Comment by mraspaud** [comment]
@zxdawn any progress here?

**Comment by zxdawn** [comment]
@mraspaud It's not related to the version of h5py.

I have tested `satpy==0.23.0, h5py==2.10.0` and `satpy==0.23.0, h5py==3.1.0`, they both works well without decoding:
```
'band_names': 'band12(band number is range from 1 to 14)'
'long_name': '10.8um channel 4km image data layer'
```

Then, if I test `satpy==0.21.0, h5py==2.10.0`,  these attrs are bytes without decoding:
```
'band_names': b'band12(band number is range from 1 to 14)'
'long_name': b'10.8um channel 4km image data layer'
```

Anyway, LGTM for the newest satpy.

**Review by zxdawn — APPROVED** [review]

**Review by djhoese — APPROVED** [review]

**Comment by djhoese** [comment]
Thanks. Looks good.

**Pull request merged**
