### PR TITLE
Fixed issue with reading fci oca error data and added fci toz product

### LINKED ISSUE #1507: FCI Level2 OCA Data - error parameters have a parameter name change in the latest version of the test data
the latest version of the FCI OCA Level2 Test data has changed the parameter name for the error parameters. retreived has been changed to retrieval and the array dimensions have been changed

try to load an FCI OCA Level2 test data file, for all parameters and it will fail 

**Expected behavior**
We should be able to load all of the FCI Level2 OCA parameters

### PR DESCRIPTION
**Pull request by ColinDuff**
Fixed issue with reading fci oca error data and added fci toz product

only a yaml file update required

 Closes #1507

### CODE REVIEW

**Review by djhoese — APPROVED** [review]
Looks fine at first glance. Would appreciate @sjoro or someone else reviewing and merging.

**Comment by djhoese** [comment]
Oh this is still a draft. Oops.

**Comment by ColinDuff** [comment]
hold for know - checking another problem that may be related.

**Review by mraspaud — APPROVED** [review]
LGTM

**Pull request merged**
