### PR TITLE
Rename duplicate night_overview

### LINKED ISSUE #1964: Duplicate key night_overview in composites/viirs.yaml
**Describe the bug**

In `etc/composite/viirs.yaml`, two competing composites `night_overview` are defined:

https://github.com/pytroll/satpy/blob/279631e5d16015504199035b924a2ded2c1ee5a3/satpy/etc/composites/viirs.yaml#L331-L337

and

https://github.com/pytroll/satpy/blob/279631e5d16015504199035b924a2ded2c1ee5a3/satpy/etc/composites/viirs.yaml#L513-L519

**To Reproduce**

```python
filenames = glob("/media/nas/x21308/scratch/VIIRS/noaa20_20211223_1033_21225/*")
sc = Scene(filenames=filenames, reader=["viirs_sdr"])
sc.load(["night_overview"])
```

**Expected behavior**

A single, unambiguous composite defined in `viirs.yaml`.

**Actual results**

Two composites are defined in `viirs.yaml`.  It seems to be using the version that uses `hncc_dnb`.  That makes the one that uses `DNB` unreachable.

```                                                                                                                                                                                                                                        [DEBUG: 2022-01-05 17:02:31 : satpy.readers.yaml_reader] Reading ('/data/gholl/checkouts/satpy/satpy/etc/readers/viirs_sdr.yaml',)                                                                                                                                                                                           [DEBUG: 2022-01-05 17:02:31 : satpy.readers.yaml_reader] Assigning to viirs_sdr: [...]
[DEBUG: 2022-01-05 17:03:10 : satpy.composites.config_loader] Looking for composites config file viirs.yaml
[DEBUG: 2022-01-05 17:03:10 : satpy.composites.config_loader] Looking for composites config file visir.yaml
[DEBUG: 2022-01-05 17:03:10 : satpy.readers.viirs_sdr] File units and output units are the same (degrees_east)
[DEBUG: 2022-01-05 17:03:10 : satpy.readers.viirs_sdr] No scaling factors found for DataID(name='m_longitude', resolution=742, modifiers=())
[...] (previous message and similar repeated many times)
[DEBUG: 2022-01-05 17:04:07 : satpy.scene] Delaying generation of DataID(name='night_overview') because of incompatible areas
[WARNING: 2022-01-05 17:04:07 : satpy.scene] The following datasets were not created and may require resampling to be generated: DataID(name='night_overview')
[DEBUG: 2022-01-05 17:04:07 : satpy.scene] Unloading dataset: DataID(name='dnb_solar_zenith_angle', resolution=743, modifiers=())
[DEBUG: 2022-01-05 17:04:07 : satpy.scene] Unloading dataset: DataID(name='DNB', wavelength=WavelengthRange(min=0.5, central=0.7, max=0.9, unit='µm'), resolution=743, calibration=<calibration.radiance>, modifiers=())
[DEBUG: 2022-01-05 17:04:07 : satpy.scene] Unloading dataset: DataID(name='dnb_moon_illumination_fraction', modifiers=())
[DEBUG: 2022-01-05 17:04:07 : satpy.scene] Unloading dataset: DataID(name='dnb_lunar_zenith_angle', resolution=743, modifiers=())
```

**Environment Info:**
 - OS: CentOS Linux
 - Satpy Version: v0.33.1-13-g279631e5

**Additional context**

This and perhaps other duplicates would be captured by #1936.

### PR DESCRIPTION
**Pull request by gerritholl**
Rename the duplicate night_overview to dnb_hncc_overview.  Keep standard
name the same, I think that ensures it will use the same enhancement.

 - [x] Closes #1964 
 - [ ] Tests added 
 - [ ] Fully documented 
 - [ ] Add your name to `AUTHORS.md` if not there already

### CODE REVIEW

**Comment by gerritholl** [comment]
I'm doing something wrong, because the two are identical.

**Comment by mraspaud** [comment]
I'm skeptical about DNB, DNB, M15 being useful, especially in twilight. Could we name that one `raw_night_overview` instead and have `night_overview` being the one with normalized dnb?

**Comment by djhoese** [comment]
Do we know if anyone is using the "raw" one? I also can't imagine it being useful. And my guess is that if the "raw" one appeared first in the YAML that it was never actually being used (being overwritten when creating the dictionary).

**Comment by mraspaud** [comment]
we used the raw one before hncc was implemented...

**Comment by djhoese** [comment]
I think this can be closed if my #2531 PR is merged since I include the deletion of the DNB version of the night_overview.

**Comment by djhoese** [comment]
Closed as part of #2531.

**Pull request closed without merging**
