### PR TITLE
Remove duplicate entries of required netcdf variables in FCI reader

### PR DESCRIPTION
**Pull request by pnuu**
While testing things to speed-up FCI reader, I noticed there were some duplicate/triplicate entries in the FCI reader YAML listing the required netcdf variables. Each of these in themselves caused extra file access, so this also speeds up the reader a tiny bit.

### CODE REVIEW

**Review by mraspaud — APPROVED** [review]
LGTM

**Comment by pnuu** [comment]
There could be some others that are read twice even if not listed, like `data/mtg_geos_projection` bringing in all its attributes which are listed also separately. I'll see if this is true and clean also these.

**Comment by pnuu** [comment]
Yep, all the separately listed attributes of `data/mtg_geos_projection` were already read when collecting the parent.

**Review by ameraner — APPROVED** [review]
LGTM, well spotted!

**Pull request merged**
