### PR TITLE
Transverse Mercator section added in cf writer

### PR DESCRIPTION
**Pull request by bornagain1981**
- [x] Tests added and test suite added to parent suite 
 - [x] Tests passed 
 - [x] Passes ``flake8 satpy`` 
 - [x] Fully documented 
 - [x] Add your name to `AUTHORS.md` if not there already

### CODE REVIEW

**Comment by bornagain1981** [comment]
@mraspaud  **during test : 2 errors and some warnings (i receive the same during the test cf writer in branch master)**

> 

 (pytroll) bornagain@bornlaptop:~/satpy/satpy$ python3 tests/writer_tests/test_cf.py 
../home/bornagain/anaconda3/envs/pytroll/lib/python3.7/site-packages/pyresample/geometry.py:1604: DeprecationWarning: 'get_lonlats_dask' is deprecated, please use 'get_lonlats' with the 'chunks' keyword argument specified.
  "'get_lonlats' with the 'chunks' keyword argument specified.", DeprecationWarning)
/home/bornagain/anaconda3/envs/pytroll/lib/python3.7/unittest/case.py:1143: DeprecationWarning: assertDictContainsSubset is deprecated
  DeprecationWarning)
../home/bornagain/anaconda3/envs/pytroll/lib/python3.7/site-packages/xarray/conventions.py:393: UserWarning: Variable 'time' has datetime type and a bounds variable but time.encoding does not have units specified. The units encodings for 'time' and 'time_bnds' will be determined independently and may not be equal, counter to CF-conventions. If this is a concern, specify a units encoding for 'time' before writing to a file.
  UserWarning)
./home/bornagain/anaconda3/envs/pytroll/lib/python3.7/site-packages/xarray/conventions.py:393: UserWarning: Variable 'time' has datetime type and a bounds variable but time.encoding does not have units specified. The units encodings for 'time' and 'time_bnds' will be determined independently and may not be equal, counter to CF-conventions. If this is a concern, specify a units encoding for 'time' before writing to a file.
  UserWarning)
./home/bornagain/anaconda3/envs/pytroll/lib/python3.7/site-packages/xarray/conventions.py:393: UserWarning: Variable 'time' has datetime type and a bounds variable but time.encoding does not have units specified. The units encodings for 'time' and 'time_bnds' will be determined independently and may not be equal, counter to CF-conventions. If this is a concern, specify a units encoding for 'time' before writing to a file.
  UserWarning)
..FFNo time dimension in datasets, skipping time bounds creation.
./home/bornagain/anaconda3/envs/pytroll/lib/python3.7/site-packages/satpy/writers/cf_writer.py:368: UserWarning: Cannot pretty-format "acq_time" coordinates because they are not unique among the given datasets
  'given datasets'.format(coord_name))
No time dimension in datasets of group visir, skipping time bounds creation.
No time dimension in datasets of group hrv, skipping time bounds creation.
.No time dimension in datasets, skipping time bounds creation.
....No time dimension in datasets, skipping time bounds creation.
.No time dimension in datasets, skipping time bounds creation.
../home/bornagain/anaconda3/envs/pytroll/lib/python3.7/site-packages/xarray/conventions.py:393: UserWarning: Variable 'time' has datetime type and a bounds variable but time.encoding does not have units specified. The units encodings for 'time' and 'time_bnds' will be determined independently and may not be equal, counter to CF-conventions. If this is a concern, specify a units encoding for 'time' before writing to a file.
  UserWarning)


FAIL: test_da2cf (__main__.TestCFWriter)
Test the conversion of a DataArray to a CF-compatible DataArray.

Traceback (most recent call last):
  File "tests/writer_tests/test_cf.py", line 483, in test_da2cf
    self.assertDictWithArraysEqual(res.attrs, attrs_expected)
  File "tests/writer_tests/test_cf.py", line 426, in assertDictWithArraysEqual
    self.assertEqual(val1, val2)
AssertionError: 'True' != True

FAIL: test_encode_attrs_nc (__main__.TestCFWriter)
Test attributes encoding.

Traceback (most recent call last):
  File "tests/writer_tests/test_cf.py", line 440, in test_encode_attrs_nc
    self.assertDictWithArraysEqual(expected, encoded)
  File "tests/writer_tests/test_cf.py", line 428, in assertDictWithArraysEqual
    self.assertTrue(isinstance(val2, np.generic))
AssertionError: False is not true


Ran 20 tests in 0.402s

FAILED (failures=2)
(pytroll) bornagain@bornlaptop:~/satpy/satpy$ 

>

**Comment by mraspaud** [comment]
@bornagain1981 ok, do you still have the errors with master ? the warnings are ok I think

**Comment by bornagain1981** [comment]
> @bornagain1981 ok, do you still have the errors with master ? the warnings are ok I think

yes, same error using branch-master, different computers or launching test in another conda environment

**Comment by bornagain1981** [comment]
Test_cf is ok  and passed also the other test:

```python
"""Test the conversion from pyresample area object to CF grid mapping."""
import xarray as xr
import pyresample.geometry
from satpy.writers.cf_writer import area2gridmapping

def assertEqual(var1, var2):
    if var1 == var2:
        return True
    else:
        return False

ds_base = xr.DataArray(data=[[1, 2], [3, 4]], dims=('y', 'x'), coords={'y': [1, 2], 'x': [3, 4]},
                       attrs={'name': 'var1'})
# a) Projection has a corresponding CF representation (e.g. geos)
lat_0= 36.5
lon_0= 15.0
lat_ts= 36.5

tmerc = pyresample.geometry.AreaDefinition(
    area_id='tmerc',
    description='tmerc',
    proj_id='tmerc',
    projection={'proj': 'tmerc', 'ellps': 'WGS84', 'lat_0': 36.5, 'lon_0': 15.0,'lat_ts': 36.5},
    width=2, height=2,
    area_extent=[-1, -1, 1, 1])

tmerc_expected = xr.DataArray(data=0,
                             attrs={'azimuth_of_central_line':'alpha',
                                    'latitude_of_projection_origin':lat_0,
                                    'longitude_of_projection_origin':lon_0,
                                    'latitude_of_meridian_ts':lat_ts,
                                    'grid_mapping_name':'transverse_mercator',
                                    'reference_ellipsoid_name':('ellps', 'WGS84'),
                                    'prime_meridian_name':('pm', 'Greenwich'),
                                    'horizontal_datum_name':('datum', 'unknown'),
                                    'geographic_crs_name':'unknown',
                                    'false_easting':0.,
                                    'false_northing':0.,
                                    'name': 'tmerc'})


ds = ds_base.copy()
ds.attrs['area'] = tmerc
res, grid_mapping = area2gridmapping(ds)
```


```python
assertEqual(grid_mapping, tmerc_expected)
```




    True




```python
assertEqual(res.attrs['grid_mapping'], 'tmerc')

```




    True

**Comment by mraspaud** [comment]
Nice work @bornagain1981 ! I think you just need to add your name to the AUTHORS.md file, the rest looks fine

**Pull request merged**
