### PR TITLE
Switch setuptools_scm to write version.py file

### LINKED ISSUE #1509: Replace pkg_resources usage with version.py file
Related: #678 and #856

This was mentioned in #856, but setuptools_scm has an option to write the version information to a python module version.py. It was decided in my PR that we should use the `pkg_resources` method though which dynamically loads the installed package data to get the version. It has come to my attention since this PR that this is actually a terrible idea. What happens is that for large python environments, `pkg_resources` has to search through all package metadata to get the version information. I'm not sure why it is this way, but it has been reported for other projects I work on (vispy) where it ends up taking **seconds** just to import the package because of the time it takes to get the version number.

Thoughts @mraspaud?

### PR DESCRIPTION
**Pull request by djhoese**
See #1509 for details. This should remove any overhead of using `pkg_resources` when importing satpy.

 - [x] Closes #1509

### CODE REVIEW

**Comment by mraspaud** [comment]
Ok so what happens to the version number when:
- one installs from github
- one has made changes to the code and commited locally?
- one creates a sdist or bdist from a local branch with new commits?

**Comment by djhoese** [comment]
This PR doesn't change anything about the existing behavior as far as local installations except for performance. The version number **still** doesn't update unless you re-install. This *should* fix the github zip/tarball installation now since that was previously not fully enabled (missing dependency). That means someone installing from a github release I think.

**Comment by mraspaud** [comment]
ok

**Review by mraspaud — APPROVED** [review]
LGTM, thanks for looking into this! sounds good with some import optimisation.

**Pull request merged**
