### PR TITLE
Scatsat 1 / MetOp ascat winds fix for xarray/dask

### PR DESCRIPTION
**Pull request by eysteinn**
ScatSat-1 and Metop Ascat readers now use xarray and dask.
Utils can now unzip bz2 and gz to temp file.

 - [x] Passes ``git diff origin/master -- "*py" | flake8 --diff``
 - [x] Fully documented

### CODE REVIEW

**Comment by mraspaud** [comment]
@eysteinn Nice addition, thanks ! Don't forget to add the reader to the table in the documentation (index.rst)
@TAlonglong was it the same product you were working on ?

**Comment by TAlonglong** [comment]
@mraspaud No. Not this one.

**Comment by eysteinn** [comment]
@mraspaud I think I added the details to index.rst correctly.

**Comment by eysteinn** [comment]
@djhoese , thank you for your suggestions, I did modifications accordingly.  I think it looks better now.

**Comment by djhoese** [comment]
@eysteinn Much better. Still have some stickler issues, but I have some other questions. Is this a replacement for #183?

Next, your file handler right now loads *all* of the possible data when it is created. Are these files not very big? Is the only reason for doing this because you are trying to load gzipped files? My initial feeling is that this unzipping should be moved outside of satpy *or* if possible we should make it possible to trick xarray in to loading the gzipped file in memory which I think is possible. Thoughts?

**Comment by djhoese** [comment]
Are these NetCDF3 or NetCDF4 files?

**Comment by eysteinn** [comment]
@djhoese You are right, its due to them being zipped that I preload the data.  However the files are  small (<10MB) so memory footprint should be insignificant. 
The Metop ascat files are NetCDF4

**Comment by djhoese** [comment]
Darn. Looks like xarray has builtin support for reading gzipped netcdf3 files by using scipy.

**Comment by eysteinn** [comment]
#183 Is out of date and this should replace it

**Comment by djhoese** [comment]
Is it? You just made commits to it lol. I'll close it then.

**Comment by ameraner** [comment]
Related to https://github.com/pytroll/satpy/issues/399

**Comment by mraspaud** [comment]
@eysteinn is not active in the community anymore, so I suggest we close this and continue discussing in #399

**Pull request closed without merging**
